import 'dotenv/config';
import prisma from '../lib/db';

export interface UGCSubjectSeed {
  code: string;
  slug: string;
  name: string;
  name_native: string;
  is_paper_1: boolean;
  direction: string;
  primary_language: string;
  secondary_language?: string;
  order_index: number;
}

export const ALL_UGC_NET_SUBJECTS: UGCSubjectSeed[] = [
  // ── Paper 1 (Common) ──
  {
    code: '00',
    slug: 'paper-1',
    name: 'General Paper 1 (Teaching & Research Aptitude)',
    name_native: 'Paper 1 (Common for All Candidates)',
    is_paper_1: true,
    direction: 'ltr',
    primary_language: 'en',
    secondary_language: 'hi',
    order_index: 0,
  },

  // ── Paper 2 Subjects (Official NTA / UGC Codes) ──
  {
    code: '29',
    slug: 'arabic',
    name: 'Arabic',
    name_native: 'اللغة العربية وآدابها',
    is_paper_1: false,
    direction: 'rtl',
    primary_language: 'ar',
    secondary_language: 'en',
    order_index: 1,
  },
  {
    code: '49',
    slug: 'arab-culture-and-islamic-studies',
    name: 'Arab Culture and Islamic Studies',
    name_native: 'الثقافة العربية والدراسات الإسلامية',
    is_paper_1: false,
    direction: 'rtl',
    primary_language: 'ar',
    secondary_language: 'en',
    order_index: 2,
  },
  {
    code: '28',
    slug: 'urdu',
    name: 'Urdu',
    name_native: 'اردو ادب',
    is_paper_1: false,
    direction: 'rtl',
    primary_language: 'ur',
    secondary_language: 'en',
    order_index: 3,
  },
  {
    code: '42',
    slug: 'persian',
    name: 'Persian',
    name_native: 'زبان و ادبیات فارسی',
    is_paper_1: false,
    direction: 'rtl',
    primary_language: 'fa',
    secondary_language: 'en',
    order_index: 4,
  },
  {
    code: '20',
    slug: 'hindi',
    name: 'Hindi',
    name_native: 'हिन्दी साहित्य',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'hi',
    order_index: 5,
  },
  {
    code: '30',
    slug: 'english',
    name: 'English',
    name_native: 'English Literature',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 6,
  },
  {
    code: '25',
    slug: 'sanskrit',
    name: 'Sanskrit',
    name_native: 'संस्कृतम् साहित्यम्',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'sa',
    order_index: 7,
  },
  {
    code: '08',
    slug: 'commerce',
    name: 'Commerce',
    name_native: 'Commerce (Finance, Accounting & Tax)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    secondary_language: 'hi',
    order_index: 8,
  },
  {
    code: '17',
    slug: 'management',
    name: 'Management (Business Admin, Marketing & HR)',
    name_native: 'Management Studies',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 9,
  },
  {
    code: '09',
    slug: 'education',
    name: 'Education',
    name_native: 'शिक्षा शास्त्र (Education)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    secondary_language: 'hi',
    order_index: 10,
  },
  {
    code: '02',
    slug: 'political-science',
    name: 'Political Science',
    name_native: 'राजनीति विज्ञान',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    secondary_language: 'hi',
    order_index: 11,
  },
  {
    code: '06',
    slug: 'history',
    name: 'History',
    name_native: 'इतिहास (Ancient, Medieval & Modern)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    secondary_language: 'hi',
    order_index: 12,
  },
  {
    code: '01',
    slug: 'economics',
    name: 'Economics / Econometrics / Development Planning',
    name_native: 'अर्थशास्त्र (Economics)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    secondary_language: 'hi',
    order_index: 13,
  },
  {
    code: '05',
    slug: 'sociology',
    name: 'Sociology',
    name_native: 'समाजशास्त्र (Sociology)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    secondary_language: 'hi',
    order_index: 14,
  },
  {
    code: '80',
    slug: 'geography',
    name: 'Geography',
    name_native: 'भूगोल (Physical & Human Geography)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    secondary_language: 'hi',
    order_index: 15,
  },
  {
    code: '87',
    slug: 'computer-science-and-applications',
    name: 'Computer Science and Applications',
    name_native: 'Computer Science & IT',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 16,
  },
  {
    code: '58',
    slug: 'law',
    name: 'Law',
    name_native: 'विधि (Jurisprudence & Constitutional Law)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 17,
  },
  {
    code: '63',
    slug: 'mass-communication-and-journalism',
    name: 'Mass Communication and Journalism',
    name_native: 'Mass Media & Journalism',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    secondary_language: 'hi',
    order_index: 18,
  },
  {
    code: '89',
    slug: 'environmental-sciences',
    name: 'Environmental Sciences',
    name_native: 'Environmental Science & Ecology',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 19,
  },
  {
    code: '04',
    slug: 'psychology',
    name: 'Psychology',
    name_native: 'मनोविज्ञान (Psychology)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    secondary_language: 'hi',
    order_index: 20,
  },
  {
    code: '03',
    slug: 'philosophy',
    name: 'Philosophy',
    name_native: 'दर्शनशास्त्र (Indian & Western Philosophy)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    secondary_language: 'hi',
    order_index: 21,
  },
  {
    code: '10',
    slug: 'social-work',
    name: 'Social Work',
    name_native: 'समाज कार्य (Social Work)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 22,
  },
  {
    code: '14',
    slug: 'public-administration',
    name: 'Public Administration',
    name_native: 'लोक प्रशासन (Public Administration)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 23,
  },
  {
    code: '55',
    slug: 'labour-welfare-and-hrm',
    name: 'Labour Welfare / Personnel Management / HRM / IR',
    name_native: 'Labour Welfare & HRM',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 24,
  },
  {
    code: '59',
    slug: 'library-and-information-science',
    name: 'Library and Information Science',
    name_native: 'पुस्तकालय एवं सूचना विज्ञान',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 25,
  },
  {
    code: '100',
    slug: 'yoga',
    name: 'Yoga',
    name_native: 'योग दर्शन एवं अभ्यास',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    secondary_language: 'sa',
    order_index: 26,
  },
  {
    code: '47',
    slug: 'physical-education',
    name: 'Physical Education',
    name_native: 'शारीरिक शिक्षा',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 27,
  },
  {
    code: '12',
    slug: 'home-science',
    name: 'Home Science',
    name_native: 'गृह विज्ञान (Home Science)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 28,
  },
  {
    code: '11',
    slug: 'defence-and-strategic-studies',
    name: 'Defence and Strategic Studies',
    name_native: 'Defence & Security Studies',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 29,
  },
  {
    code: '07',
    slug: 'anthropology',
    name: 'Anthropology',
    name_native: 'मानव विज्ञान (Anthropology)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 30,
  },
  {
    code: '15',
    slug: 'population-studies',
    name: 'Population Studies',
    name_native: 'Demography & Population Studies',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 31,
  },
  {
    code: '16',
    slug: 'music',
    name: 'Music (Hindustani / Carnatic / Rabindra Sangeet / Percussion)',
    name_native: 'संगीत (Music)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 32,
  },
  {
    code: '18',
    slug: 'maithili',
    name: 'Maithili',
    name_native: 'मैथिली भाषा ओ साहित्य',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'hi',
    order_index: 33,
  },
  {
    code: '19',
    slug: 'bengali',
    name: 'Bengali',
    name_native: 'বাংলা ভাষা ও সাহিত্য',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'bn',
    order_index: 34,
  },
  {
    code: '21',
    slug: 'kannada',
    name: 'Kannada',
    name_native: 'ಕನ್ನಡ ಭಾಷೆ ಮತ್ತು ಸಾಹಿತ್ಯ',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'kn',
    order_index: 35,
  },
  {
    code: '22',
    slug: 'malayalam',
    name: 'Malayalam',
    name_native: 'മലയാള ഭാഷയും സാഹിത്യവും',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'ml',
    order_index: 36,
  },
  {
    code: '23',
    slug: 'odia',
    name: 'Odia',
    name_native: 'ଓଡ଼ିଆ ଭାଷା ଓ ସାହିତ୍ୟ',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'or',
    order_index: 37,
  },
  {
    code: '24',
    slug: 'punjabi',
    name: 'Punjabi',
    name_native: 'ਪੰਜਾਬੀ ਭਾਸ਼ਾ ਅਤੇ ਸਾਹਿਤ',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'pa',
    order_index: 38,
  },
  {
    code: '26',
    slug: 'tamil',
    name: 'Tamil',
    name_native: 'தமிழ் மொழியும் இலக்கியமும்',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'ta',
    order_index: 39,
  },
  {
    code: '27',
    slug: 'telugu',
    name: 'Telugu',
    name_native: 'తెలుగు భాష మరియు సాహిత్యం',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'te',
    order_index: 40,
  },
  {
    code: '31',
    slug: 'linguistics',
    name: 'Linguistics',
    name_native: 'भाषा विज्ञान (Linguistics)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 41,
  },
  {
    code: '32',
    slug: 'chinese',
    name: 'Chinese',
    name_native: '中文语言与文学',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'zh',
    order_index: 42,
  },
  {
    code: '33',
    slug: 'dogri',
    name: 'Dogri',
    name_native: 'डोगरी भाषा ते साहित्य',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'hi',
    order_index: 43,
  },
  {
    code: '34',
    slug: 'nepali',
    name: 'Nepali',
    name_native: 'नेपाली भाषा र साहित्य',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'ne',
    order_index: 44,
  },
  {
    code: '35',
    slug: 'manipuri',
    name: 'Manipuri',
    name_native: 'ꯃꯅꯤꯄꯨꯔꯤ ꯂꯣꯟ ꯑꯃꯁꯨꯡ ꯁꯥꯍꯤꯇ꯭ꯌ',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'mni',
    order_index: 45,
  },
  {
    code: '36',
    slug: 'assamese',
    name: 'Assamese',
    name_native: 'অসমীয়া ভাষা আৰু সাহিত্য',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'as',
    order_index: 46,
  },
  {
    code: '37',
    slug: 'gujarati',
    name: 'Gujarati',
    name_native: 'ગુજરાતી ભાષા અને સાહિત્ય',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'gu',
    order_index: 47,
  },
  {
    code: '38',
    slug: 'marathi',
    name: 'Marathi',
    name_native: 'मराठी भाषा आणि साहित्य',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'mr',
    order_index: 48,
  },
  {
    code: '39',
    slug: 'french',
    name: 'French (French Studies)',
    name_native: 'Langue et Littérature Françaises',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'fr',
    order_index: 49,
  },
  {
    code: '40',
    slug: 'spanish',
    name: 'Spanish',
    name_native: 'Lengua y Literatura Españolas',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'es',
    order_index: 50,
  },
  {
    code: '41',
    slug: 'russian',
    name: 'Russian',
    name_native: 'Русский язык и литература',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'ru',
    order_index: 51,
  },
  {
    code: '43',
    slug: 'rajasthani',
    name: 'Rajasthani',
    name_native: 'राजस्थानी भाषा अर साहित्य',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'hi',
    order_index: 52,
  },
  {
    code: '44',
    slug: 'german',
    name: 'German',
    name_native: 'Deutsche Sprache und Literatur',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'de',
    order_index: 53,
  },
  {
    code: '45',
    slug: 'japanese',
    name: 'Japanese',
    name_native: '日本語と日本文学',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'ja',
    order_index: 54,
  },
  {
    code: '46',
    slug: 'adult-education',
    name: 'Adult Education / Continuing Education / Andragogy',
    name_native: 'Adult & Non-Formal Education',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 55,
  },
  {
    code: '50',
    slug: 'indian-culture',
    name: 'Indian Culture',
    name_native: 'भारतीय संस्कृति एवं धरोहर',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 56,
  },
  {
    code: '60',
    slug: 'buddhist-jaina-gandhian-studies',
    name: 'Buddhist, Jaina, Gandhian and Peace Studies',
    name_native: 'बौद्ध, जैन एवं गांधी अध्ययन',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 57,
  },
  {
    code: '62',
    slug: 'comparative-study-of-religions',
    name: 'Comparative Study of Religions',
    name_native: 'धर्मों का तुलनात्मक अध्ययन',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 58,
  },
  {
    code: '65',
    slug: 'performing-art',
    name: 'Performing Art - Dance / Drama / Theatre',
    name_native: 'प्रदर्शन कला (नृत्य, नाटक, रंगमंच)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 59,
  },
  {
    code: '66',
    slug: 'museology-and-conservation',
    name: 'Museology & Conservation',
    name_native: 'संग्रहालय विज्ञान एवं संरक्षण',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 60,
  },
  {
    code: '67',
    slug: 'archaeology',
    name: 'Archaeology',
    name_native: 'पुरातत्व विज्ञान (Archaeology)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 61,
  },
  {
    code: '68',
    slug: 'criminology',
    name: 'Criminology',
    name_native: 'अपराध शास्त्र (Criminology)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 62,
  },
  {
    code: '70',
    slug: 'tribal-and-regional-language',
    name: 'Tribal and Regional Language / Literature',
    name_native: 'जनजातीय एवं क्षेत्रीय भाषाएं',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 63,
  },
  {
    code: '71',
    slug: 'folk-literature',
    name: 'Folk Literature',
    name_native: 'लोक साहित्य (Folk Traditions)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'hi',
    order_index: 64,
  },
  {
    code: '72',
    slug: 'comparative-literature',
    name: 'Comparative Literature',
    name_native: 'तुलनात्मक साहित्य (Comparative Literature)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 65,
  },
  {
    code: '73',
    slug: 'sanskrit-traditional-subjects',
    name: 'Sanskrit Traditional Subjects (Jyotisha / Vyakarna / Veda / Dharmashastra)',
    name_native: 'संस्कृत पारम्परिक विषय (ज्योतिष, व्याकरण, धर्मशास्त्र)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'sa',
    order_index: 66,
  },
  {
    code: '74',
    slug: 'women-studies',
    name: 'Women Studies',
    name_native: 'महिला अध्ययन (Gender & Women Studies)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 67,
  },
  {
    code: '79',
    slug: 'visual-art',
    name: 'Visual Art (Drawing & Painting / Applied Art / History of Art)',
    name_native: 'दृश्य कला (Visual Arts)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 68,
  },
  {
    code: '81',
    slug: 'social-medicine-and-community-health',
    name: 'Social Medicine & Community Health',
    name_native: 'Public Health & Social Medicine',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 69,
  },
  {
    code: '82',
    slug: 'forensic-science',
    name: 'Forensic Science',
    name_native: 'न्यायालयिक विज्ञान (Forensic Science)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 70,
  },
  {
    code: '83',
    slug: 'pali',
    name: 'Pali',
    name_native: 'पालि भाषा एवं साहित्य',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'sa',
    order_index: 71,
  },
  {
    code: '84',
    slug: 'kashmiri',
    name: 'Kashmiri',
    name_native: 'کٲشُر زَبان تِہ اَدَب / कश्मीरी',
    is_paper_1: false,
    direction: 'rtl',
    primary_language: 'ks',
    order_index: 72,
  },
  {
    code: '85',
    slug: 'konkani',
    name: 'Konkani',
    name_native: 'कोंकणी भास आणि साहित्य',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'kok',
    order_index: 73,
  },
  {
    code: '88',
    slug: 'electronic-science',
    name: 'Electronic Science',
    name_native: 'Electronic Science & Engineering',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 74,
  },
  {
    code: '90',
    slug: 'politics-and-international-studies',
    name: 'Politics (including International Relations & Studies)',
    name_native: 'International Relations & Global Studies',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 75,
  },
  {
    code: '91',
    slug: 'prakrit',
    name: 'Prakrit',
    name_native: 'प्राकृत भाषा एवं साहित्य',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'sa',
    order_index: 76,
  },
  {
    code: '92',
    slug: 'human-rights-and-duties',
    name: 'Human Rights and Duties',
    name_native: 'मानव अधिकार एवं कर्तव्य',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 77,
  },
  {
    code: '93',
    slug: 'tourism-administration-and-management',
    name: 'Tourism Administration and Management',
    name_native: 'पर्यटन प्रबंधन (Tourism Management)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 78,
  },
  {
    code: '94',
    slug: 'bodo',
    name: 'Bodo',
    name_native: 'बर’ राव आरो थुनलाइ',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'brx',
    order_index: 79,
  },
  {
    code: '95',
    slug: 'santali',
    name: 'Santali',
    name_native: 'ᱥᱟᱱᱛᱟᱲᱤ ᱯᱟᱹᱨᱥᱤ ᱟᱨ ᱥᱟᱶᱦᱮᱫ',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'sat',
    order_index: 80,
  },
  {
    code: '101',
    slug: 'sindhi',
    name: 'Sindhi',
    name_native: 'سنڌي ٻولي ۽ ادب / सिन्धी',
    is_paper_1: false,
    direction: 'rtl',
    primary_language: 'sd',
    order_index: 81,
  },
  {
    code: '102',
    slug: 'hindu-studies',
    name: 'Hindu Studies',
    name_native: 'हिन्दू अध्ययन (Darshana, Epics & Hermeneutics)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'sa',
    order_index: 82,
  },
  {
    code: '103',
    slug: 'disaster-management',
    name: 'Disaster Management',
    name_native: 'आपदा प्रबंधन (Disaster Management)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 83,
  },
  {
    code: '104',
    slug: 'ayush',
    name: 'Ayush (Ayurveda Biology & Traditional Systems)',
    name_native: 'आयुष (Ayush & Ayurveda Systems)',
    is_paper_1: false,
    direction: 'ltr',
    primary_language: 'en',
    order_index: 84,
  },
];

async function seedAllSubjects() {
  console.log(`🚀 SEEDING ALL ${ALL_UGC_NET_SUBJECTS.length} UGC NET SUBJECTS INTO DATABASE...\n`);

  let createdCount = 0;
  let updatedCount = 0;

  for (const s of ALL_UGC_NET_SUBJECTS) {
    const id = `subj_${s.slug.replace(/[^a-z0-9]/g, '_')}_code${s.code}`;

    const existing = await prisma.subject.findFirst({
      where: {
        OR: [{ code: s.code }, { slug: s.slug }],
      },
    });

    if (existing) {
      await prisma.subject.update({
        where: { id: existing.id },
        data: {
          code: s.code,
          slug: s.slug,
          name: s.name,
          name_native: s.name_native,
          is_paper_1: s.is_paper_1,
          direction: s.direction,
          primary_language: s.primary_language,
          secondary_language: s.secondary_language || null,
          order_index: s.order_index,
          is_active: true,
        },
      });
      updatedCount++;
    } else {
      await prisma.subject.create({
        data: {
          id,
          code: s.code,
          slug: s.slug,
          name: s.name,
          name_native: s.name_native,
          is_paper_1: s.is_paper_1,
          direction: s.direction,
          primary_language: s.primary_language,
          secondary_language: s.secondary_language || null,
          order_index: s.order_index,
          is_active: true,
        },
      });
      createdCount++;
    }
  }

  const totalInDb = await prisma.subject.count();
  console.log(`\n🎉 SEED COMPLETE!`);
  console.log(`  • Created: ${createdCount}`);
  console.log(`  • Updated: ${updatedCount}`);
  console.log(`  • Total Active UGC NET Subjects in Database: ${totalInDb}\n`);
}

seedAllSubjects().catch((e) => {
  console.error('❌ Error seeding subjects:', e);
  process.exit(1);
});
