import { MockTestDefinition, RawMockQuestion } from '../common';

export function getCommerceMockTest(): MockTestDefinition {
  const questions: RawMockQuestion[] = [
    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 1: BUSINESS ENVIRONMENT & INTERNATIONAL BUSINESS (10 Questions: Q1 - Q10)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 1,
      questionText: 'Which strategic environmental scanning matrix evaluates the External Macro-Environment across Political, Economic, Socio-Cultural, Technological, Legal, and Environmental dimensions?',
      questionType: 'Direct MCQ',
      options: {
        A: 'PESTLE Analysis',
        B: 'SWOT Analysis',
        C: 'BCG Matrix',
        D: 'Ansoff Matrix',
      },
      correctAnswer: 'A',
      explanation: 'PESTLE analysis provides a structured framework for analyzing macro-environmental forces impacting business strategy and industrial competitiveness.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Under the World Trade Organization (WTO) Agreement on Agriculture (AoA), agricultural domestic support subsidies that have minimal or no trade-distorting effects (such as agricultural R&D, pest control, and environmental protection) belong to the:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Green Box Subsidies (exempt from reduction commitments)',
        B: 'Amber Box Subsidies (trade distorting, subject to reduction limits / de minimis)',
        C: 'Blue Box Subsidies (direct payments under production-limiting programs)',
        D: 'Red Box Subsidies (strictly forbidden)',
      },
      correctAnswer: 'A',
      explanation: 'Green Box subsidies do not distort trade (or cause at most minimal distortion) and are decoupled from current production levels and market prices.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In international business entry strategies, an arrangement where a domestic parent firm grants an overseas firm the right to use its intellectual property, patents, or trade secrets in exchange for royalty fees is called:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Licensing / Franchising',
        B: 'Wholly Owned Greenfield Subsidiary',
        C: 'Turnkey Project',
        D: 'Joint Venture',
      },
      correctAnswer: 'A',
      explanation: 'Licensing grants intellectual property rights (patents, technology, trademarks) for royalty payments, requiring low capital commitment.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'The "Special Drawing Rights" (SDR / Paper Gold) is an international reserve asset created by the International Monetary Fund (IMF) in 1969 whose value is determined based on a basket of which five major global currencies?',
      questionType: 'Direct MCQ',
      options: {
        A: 'US Dollar, Euro, Chinese Renminbi, Japanese Yen, and British Pound Sterling',
        B: 'US Dollar, Swiss Franc, Indian Rupee, Euro, and Yen',
        C: 'US Dollar, Canadian Dollar, Australian Dollar, Euro, and Yen',
        D: 'Gold, Silver, Platinum, Crude Oil, and Natural Gas',
      },
      correctAnswer: 'A',
      explanation: 'The IMF SDR basket comprises USD, EUR, CNY (added in 2016), JPY, and GBP reviewed every five years by the IMF Executive Board.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Under the Foreign Exchange Management Act (FEMA 1999), transactions involving international trade in goods, services, current short-term banking credit facilities, and remittances for family maintenance are classified as:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Current Account Transactions (freely convertible under Section 5)',
        B: 'Capital Account Transactions (governed by Section 6 restrictions)',
        C: 'Illegal Hawala Transactions',
        D: 'Offshore Derivative Transactions',
      },
      correctAnswer: 'A',
      explanation: 'Section 2(j) of FEMA classifies trade in goods/services, interest on loans, and personal remittances as Current Account Transactions with full convertibility.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In the theory of regional economic integration, what is the correct ascending order of integration stages from lowest to deepest integration?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Preferential Trade Agreement $\\rightarrow$ Free Trade Area (FTA) $\\rightarrow$ Customs Union $\\rightarrow$ Common Market $\\rightarrow$ Economic and Monetary Union',
        B: 'Customs Union $\\rightarrow$ FTA $\\rightarrow$ Common Market $\\rightarrow$ Economic Union',
        C: 'Economic Union $\\rightarrow$ Common Market $\\rightarrow$ Customs Union $\\rightarrow$ FTA',
        D: 'FTA $\\rightarrow$ Economic Union $\\rightarrow$ Customs Union $\\rightarrow$ PTA',
      },
      correctAnswer: 'A',
      explanation: 'PTA (reduced tariffs) $\\rightarrow$ FTA (zero internal tariffs) $\\rightarrow$ Customs Union (common external tariff) $\\rightarrow$ Common Market (free factor mobility) $\\rightarrow$ Economic Union (common currency/harmonized policy).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'Which international institution, established in 1944 along with the IMF at the Bretton Woods Conference, provides long-term development loans and grants to developing countries for capital projects?',
      questionType: 'Direct MCQ',
      options: {
        A: 'International Bank for Reconstruction and Development (IBRD / World Bank)',
        B: 'Bank for International Settlements (BIS)',
        C: 'World Trade Organization (WTO)',
        D: 'United Nations Development Programme (UNDP)',
      },
      correctAnswer: 'A',
      explanation: 'IBRD (along with IDA, IFC, MIGA, and ICSID) forms the World Bank Group founded at Bretton Woods, New Hampshire.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Under the TRIPS Agreement (Trade-Related Aspects of Intellectual Property Rights) under WTO, what is the standardized minimum duration of Patent protection granted for inventions from the date of filing?',
      questionType: 'Direct MCQ',
      options: {
        A: '$20\\text{ Years}$',
        B: '$10\\text{ Years}$',
        C: '$50\\text{ Years}$',
        D: '$15\\text{ Years}$',
      },
      correctAnswer: 'A',
      explanation: 'Article 33 of TRIPS mandates a minimum patent term of 20 years from the filing date for both product and process patents.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In Corporate Social Responsibility (CSR) in India, Section 135 of the Companies Act 2013 mandates that eligible companies must spend in every financial year at least what percentage of their average net profits made during the three immediately preceding financial years on CSR activities?',
      questionType: 'Direct MCQ',
      options: {
        A: '$2\\%$',
        B: '$5\\%$',
        C: '$1\\%$',
        D: '$3\\%$',
      },
      correctAnswer: 'A',
      explanation: 'Section 135 mandates that companies with net worth $\\ge 500\\text{ Cr}$, turnover $\\ge 1000\\text{ Cr}$, or net profit $\\ge 5\\text{ Cr}$ must spend at least 2% of average 3-year net profits on Schedule VII CSR projects.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Under the "Tariff Escalation" trade phenomenon, importing countries structure their customs tariff schedule such that:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Tariffs are lowest on unprocessed raw materials, moderate on intermediate goods, and highest on finished manufactured products',
        B: 'Tariffs are highest on raw materials and zero on finished goods',
        C: 'Tariffs decline as the value of the import increases',
        D: 'All goods are taxed at a uniform flat rate',
      },
      correctAnswer: 'A',
      explanation: 'Tariff escalation protects domestic processing industries by providing higher effective protection rates for value-added processed manufactures.',
      difficulty: 'MEDIUM',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 2: ACCOUNTING AND AUDITING (10 Questions: Q11 - Q20)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 2,
      questionText: 'Under Indian Accounting Standard (Ind AS 16) / AS 10, Property, Plant and Equipment should initially be measured at:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Historical Cost (including purchase price, import duties, and directly attributable costs of bringing the asset to working location)',
        B: 'Net Realizable Value',
        C: 'Liquidation Forced Value',
        D: 'Present value of future dividends',
      },
      correctAnswer: 'A',
      explanation: 'Ind AS 16 prescribes that PPE is initially recognized at cost, comprising purchase price, duties, installation, and site restoration obligations.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In corporate accounting, when forfeited shares that were originally issued at par are re-issued at a discount, the maximum permissible discount on re-issue cannot exceed:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The amount already forfeited and standing to the credit of the Share Forfeiture Account on those shares',
        B: '$10\\%$ of the face value',
        C: 'The total unpaid call money',
        D: 'The market price on date of re-issue',
      },
      correctAnswer: 'A',
      explanation: 'Re-issue discount cannot exceed the amount already collected on the forfeited shares. Any remaining surplus balance is transferred to Capital Reserve.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'In Marginal Costing, the "Break-Even Point" (BEP) in sales revenue is calculated as:',
      questionType: 'Direct MCQ',
      options: {
        A: '$\\frac{\\text{Fixed Cost}}{\\text{Profit Volume (P/V) Ratio}}$',
        B: '$\\text{Fixed Cost} \\times \\text{P/V Ratio}$',
        C: '$\\frac{\\text{Total Variable Cost}}{\\text{Contribution}}$',
        D: '$\\text{Total Sales} - \\text{Margin of Safety}$',
      },
      correctAnswer: 'A',
      explanation: '$\\text{Break-Even Sales} = \\frac{\\text{Fixed Cost}}{\\text{P/V Ratio}} = \\frac{\\text{Fixed Cost}}{(\\text{Sales} - \\text{Variable Cost}) / \\text{Sales}}$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In financial ratio analysis, what does the "Quick Ratio / Acid Test Ratio" measure?',
      questionType: 'Direct MCQ',
      options: {
        A: '$\\frac{\\text{Current Assets} - \\text{Inventory} - \\text{Prepaid Expenses}}{\\text{Current Liabilities}}$',
        B: '$\\frac{\\text{Total Current Assets}}{\\text{Total Current Liabilities}}$ (Current Ratio)',
        C: '$\\frac{\\text{Net Profit}}{\\text{Total Assets}}$',
        D: '$\\frac{\\text{Cost of Goods Sold}}{\\text{Average Inventory}}$',
      },
      correctAnswer: 'A',
      explanation: 'Quick ratio measures instant liquidity by excluding illiquid inventory and prepaid expenses from current assets (standard ideal benchmark $1:1$).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In fund flow and cash flow statement preparation (Ind AS 7 / AS 3), the payment of cash dividends to equity shareholders is classified under:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Cash Flow from Financing Activities',
        B: 'Cash Flow from Operating Activities',
        C: 'Cash Flow from Investing Activities',
        D: 'Cash and Cash Equivalents',
      },
      correctAnswer: 'A',
      explanation: 'Dividend payments result in changes in the size and composition of contributed equity and borrowings, hence classified as Financing Activities.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In standard costing and variance analysis, what is the formula for calculating the "Material Price Variance" (MPV)?',
      questionType: 'Direct MCQ',
      options: {
        A: '$MPV = \\text{Actual Quantity} \\times (\\text{Standard Price} - \\text{Actual Price})$',
        B: '$MPV = \\text{Standard Price} \\times (\\text{Standard Quantity} - \\text{Actual Quantity})$ (Material Usage Variance)',
        C: '$MPV = \\text{Standard Cost} - \\text{Actual Cost}$',
        D: '$MPV = \\text{Actual Price} \\times \\text{Standard Quantity}$',
      },
      correctAnswer: 'A',
      explanation: '$MPV = AQ \\times (SP - AP)$. If $SP > AP$, variance is Favourable; if $AP > SP$, variance is Adverse.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'Under Section 139 of the Companies Act 2013, a statutory auditor appointed at the Annual General Meeting (AGM) of a company shall hold office from the conclusion of that AGM until:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The conclusion of the sixth (6th) AGM (term of 5 consecutive years)',
        B: 'The conclusion of the next AGM (1 year)',
        C: 'The retirement age of 65 years',
        D: 'The discretion of the Board of Directors',
      },
      correctAnswer: 'A',
      explanation: 'Individual auditors can be appointed for 1 term of 5 consecutive years; audit firms for up to 2 terms of 5 consecutive years with a mandatory 5-year cooling-off period.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'In financial auditing, what is a "Disclaimer of Opinion" issued in the independent auditor\'s report?',
      questionType: 'Direct MCQ',
      options: {
        A: 'A statement issued when the auditor is unable to obtain sufficient appropriate audit evidence and the possible effects on the financial statements are both material and pervasive',
        B: 'An unqualified clean audit report stating true and fair view',
        C: 'An adverse opinion stating financial statements are fraudulently misstated',
        D: 'A routine footnote in annual reports',
      },
      correctAnswer: 'A',
      explanation: 'Under SA 705, a Disclaimer of Opinion is issued when limitation on audit scope is so pervasive that the auditor cannot form an opinion on the financial statements.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'In activity-based costing (ABC), what is a "Cost Driver"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Any factor or activity that causes a direct change in the total cost of an activity or cost object (e.g., number of machine setups, purchase orders)',
        B: 'The truck driver transporting goods to customers',
        C: 'The total direct labor cost divided by sales',
        D: 'The depreciation percentage on factory buildings',
      },
      correctAnswer: 'A',
      explanation: 'A cost driver is the causal factor that triggers overhead consumption in Activity-Based Costing systems.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'Under the fundamental accounting assumption of "Prudence / Conservatism", which accounting practice is strictly followed?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Anticipate no future profits, but provide for all possible probable losses and expenses',
        B: 'Recognize revenue as soon as an inquiry is received from a customer',
        C: 'Overstate asset valuations to increase borrowing capacity',
        D: 'Ignore bad debts until bankruptcy occurs',
      },
      correctAnswer: 'A',
      explanation: 'Conservatism dictates valuing inventory at Cost or Net Realizable Value (whichever is lower) and creating provisions for doubtful debts.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 3, 4 & 5: BUSINESS ECONOMICS, FINANCE & STATISTICS (30 Questions: Q21 - Q50)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 3,
      questionText: 'In the Kinked Demand Curve model of oligopoly formulated by Paul Sweezy, the kink on the firm\'s demand curve occurs at the prevailing market price because:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Rival firms will follow price decreases (inelastic segment below kink) but will NOT follow price increases (elastic segment above kink)',
        B: 'Rival firms collude to fix prices at the kink',
        C: 'Marginal revenue curve is continuous and smooth',
        D: 'Demand elasticity is identical in both directions',
      },
      correctAnswer: 'A',
      explanation: 'Sweezy\'s kink produces a vertical discontinuity (gap) in the Marginal Revenue curve, explaining price rigidity (stickiness) in oligopolistic markets.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'According to the Modigliani-Miller (MM) Theorem (1958) in a perfect capital market with NO corporate taxes and no bankruptcy costs, the market value of a firm and its weighted average cost of capital (WACC) are:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Completely independent of its capital structure / debt-equity ratio (Capital Structure Irrelevance Proposition I)',
        B: 'Maximized at 100% debt financing',
        C: 'Minimized when equity equals 50%',
        D: 'Strictly dependent on dividend payout ratios',
      },
      correctAnswer: 'A',
      explanation: 'MM Proposition I proves via arbitrage that under zero taxes, symmetric information, and frictionless markets, firm value depends solely on real earning power, not financing mix.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'In capital budgeting, the "Net Present Value" (NPV) criterion is superior to the "Internal Rate of Return" (IRR) for mutually exclusive projects because:',
      questionType: 'Direct MCQ',
      options: {
        A: 'NPV assumes cash inflows are reinvested at the firm\'s Cost of Capital ($k$), whereas IRR unrealistically assumes reinvestment at the internal rate of return ($IRR$)',
        B: 'NPV ignores the time value of money',
        C: 'IRR can never handle cash flow projections',
        D: 'NPV always equals the payback period',
      },
      correctAnswer: 'A',
      explanation: 'NPV has a realistic reinvestment rate assumption, directly measures wealth addition to equity holders, and avoids multiple-rate problems of non-conventional cash flows.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'In the Capital Asset Pricing Model (CAPM), the required rate of return on an equity asset $E(R_i)$ is calculated using the formula:',
      questionType: 'Direct MCQ',
      options: {
        A: '$E(R_i) = R_f + \\beta_i [E(R_m) - R_f]$',
        B: '$E(R_i) = R_f + \\beta_i \\times R_m$',
        C: '$E(R_i) = \\frac{D_1}{P_0} + g$',
        D: '$E(R_i) = \\beta_i \\times E(R_m)$',
      },
      correctAnswer: 'A',
      explanation: 'CAPM establishes the Security Market Line (SML): expected return equals risk-free rate $R_f$ plus systematic risk Beta $\\beta_i$ times market equity risk premium $[E(R_m) - R_f]$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'In dividend policy theories, Walter\'s Valuation Model states that if the internal rate of return on investment ($r$) exceeds the cost of equity capital ($k_e$) ($r > k_e$), the firm is a "Growth Firm" and the optimal dividend payout ratio to maximize share price is:',
      questionType: 'Direct MCQ',
      options: {
        A: '$0\\%$ (Zero Dividend / $100\\%$ retention)',
        B: '$100\\%$ (All earnings paid as dividends)',
        C: '$50\\%$',
        D: 'Indifferent (Any payout ratio)',
      },
      correctAnswer: 'A',
      explanation: 'James Walter proved that when $r > k_e$, retaining all earnings inside the firm generates superior compounding returns than shareholders could earn elsewhere, maximizing share price at 0% payout.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'If the Karl Pearson\'s coefficient of correlation between two variables $X$ and $Y$ is $r = +0.8$, the "Coefficient of Determination" ($r^2$) is:',
      questionType: 'Direct MCQ',
      options: {
        A: '$0.64$ ($64\\%$ of the variation in $Y$ is explained by $X$)',
        B: '$0.80$',
        C: '$1.60$',
        D: '$0.36$',
      },
      correctAnswer: 'A',
      explanation: '$r^2 = (0.8)^2 = 0.64$. It indicates that 64% of the total variance in the dependent variable is accounted for by the regression model.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'In probability theory, for a Binomial Distribution with parameters $n=100$ trials and probability of success $p=0.2$, the Mean ($\\mu$) and Variance ($\\sigma^2$) are:',
      questionType: 'Direct MCQ',
      options: {
        A: '$\\text{Mean} = 20, \\text{ Variance} = 16$',
        B: '$\\text{Mean} = 20, \\text{ Variance} = 20$',
        C: '$\\text{Mean} = 50, \\text{ Variance} = 25$',
        D: '$\\text{Mean} = 10, \\text{ Variance} = 8$',
      },
      correctAnswer: 'A',
      explanation: '$\\mu = n p = 100 \\times 0.2 = 20$. $\\sigma^2 = n p q = 100 \\times 0.2 \\times 0.8 = 16$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'In statistical hypothesis testing, a "Type I Error" ($\\\\alpha$) occurs when the researcher:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Rejects a True Null Hypothesis ($H_0$)',
        B: 'Fails to reject (accepts) a False Null Hypothesis (Type II Error $\\beta$)',
        C: 'Uses a sample size that is too small',
        D: 'Calculates the arithmetic mean incorrectly',
      },
      correctAnswer: 'A',
      explanation: 'Type I error is the probability $\\alpha$ (significance level) of falsely rejecting a null hypothesis that is actually true (false positive).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'For a perfectly symmetrical, bell-shaped Normal Distribution, which of the following relationships between central tendency measures holds true?',
      questionType: 'Direct MCQ',
      options: {
        A: '$\\text{Mean} = \\text{Median} = \\text{Mode}$ with Skewness = $0$ and Kurtosis = $3$',
        B: '$\\text{Mean} > \\text{Median} > \\text{Mode}$ (Positively Skewed)',
        C: '$\\text{Mode} > \\text{Median} > \\text{Mean}$ (Negatively Skewed)',
        D: 'Standard Deviation is always zero',
      },
      correctAnswer: 'A',
      explanation: 'In a normal Gaussian curve, mean, median, and mode coincide at the center peak with zero skewness and mesokurtic coefficient $\\beta_2 = 3$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'Which non-parametric statistical hypothesis test is used to compare whether two independent sample medians come from identical continuous distributions without assuming normality?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Mann-Whitney U Test (Wilcoxon Rank-Sum Test)',
        B: 'Paired Student\'s t-test',
        C: 'Pearson Correlation Test',
        D: 'Two-way ANOVA F-test',
      },
      correctAnswer: 'A',
      explanation: 'Mann-Whitney U test is the non-parametric equivalent of the independent two-sample t-test, operating on ranked data.',
      difficulty: 'MEDIUM',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 6, 7 & 8: HRM, BANKING, MARKETING & LEGAL (30 Questions: Q51 - Q80)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 6,
      questionText: 'In motivation theories, Frederick Herzberg\'s "Two-Factor Theory" (Motivation-Hygiene Theory) posits that Hygiene factors (company policy, salary, working conditions):',
      questionType: 'Direct MCQ',
      options: {
        A: 'Prevent job dissatisfaction when present, but do NOT provide positive motivation or satisfaction',
        B: 'Directly create high long-term intrinsic motivation and excitement',
        C: 'Are identical to Maslow\'s self-actualization needs',
        D: 'Must be eliminated from workplaces',
      },
      correctAnswer: 'A',
      explanation: 'Herzberg distinguished Hygiene factors (extrinsic dissatisfiers) from Motivators (intrinsic factors like achievement, recognition, responsibility, growth).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'Under the Negotiable Instruments Act 1881, which instrument is defined as an unconditional order in writing, signed by the maker, directing a specified banker to pay on demand a certain sum of money only to or to the order of a certain person?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Cheque (Section 6)',
        B: 'Promissory Note (Section 4 - unconditional undertaking/promise)',
        C: 'Bill of Exchange (Section 5)',
        D: 'Hundi',
      },
      correctAnswer: 'A',
      explanation: 'Section 6 of the Negotiable Instruments Act 1881 defines a cheque as a bill of exchange drawn on a specified banker payable only on demand.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'In marketing management, the classic "4 Ps" Marketing Mix framework comprising Product, Price, Place, and Promotion was classified and popularized by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'E. Jerome McCarthy (1960)',
        B: 'Philip Kotler',
        C: 'Peter Drucker',
        D: 'Michael Porter',
      },
      correctAnswer: 'A',
      explanation: 'E. Jerome McCarthy introduced the 4 Ps in "Basic Marketing: A Managerial Approach", later expanded by Booms and Bitner to 7 Ps for services.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'In consumer adoption of innovative new products (Everett Rogers\' Diffusion of Innovations), what is the correct chronological sequence of adopter categories?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Innovators ($2.5\\%$) $\\rightarrow$ Early Adopters ($13.5\\%$) $\\rightarrow$ Early Majority ($34\\%$) $\\rightarrow$ Late Majority ($34\\%$) $\\rightarrow$ Laggards ($16\\%$) ',
        B: 'Laggards $\\rightarrow$ Innovators $\\rightarrow$ Early Adopters $\\rightarrow$ Majority',
        C: 'Early Majority $\\rightarrow$ Late Majority $\\rightarrow$ Innovators $\\rightarrow$ Laggards',
        D: 'Pioneers $\\rightarrow$ Followers $\\rightarrow$ Skeptics $\\rightarrow$ Consumers',
      },
      correctAnswer: 'A',
      explanation: 'Rogers mapped the bell-shaped innovation adoption curve across five distinct psychographic adopter segments.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'Under the Indian Contract Act 1872, an agreement entered into without free consent due to "Coercion", "Undue Influence", "Fraud", or "Misrepresentation" is:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Voidable at the option of the aggrieved party whose consent was so caused (Section 19 and 19A)',
        B: 'Void ab initio (void from the very beginning)',
        C: 'Valid and enforceable without exception',
        D: 'An illegal wagering agreement',
      },
      correctAnswer: 'A',
      explanation: 'A voidable contract (Section 2(i)) remains valid until repudiated by the party whose consent was vitiated by coercion, fraud, misrepresentation, or undue influence.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'Under the Consumer Protection Act 2019, the pecuniary jurisdiction of the "District Consumer Disputes Redressal Commission" (District Commission) to entertain consumer complaints is for claims up to:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Up to ₹50 Lakhs (revised by 2021 Rules; originally ₹1 Crore in 2019 Act)',
        B: 'Up to ₹20 Lakhs (1986 Act)',
        C: 'Above ₹10 Crores (National Commission)',
        D: 'Up to ₹5 Lakhs only',
      },
      correctAnswer: 'A',
      explanation: 'Under Consumer Protection Rules 2021: District Commission (up to ₹50 Lakhs), State Commission (> ₹50 Lakhs up to ₹2 Crores), and National Commission (> ₹2 Crores).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'Under the Competition Act 2002, which regulatory authority is established to prevent anti-competitive agreements, prohibit abuse of dominant position, and regulate merger combinations?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Competition Commission of India (CCI)',
        B: 'Monopolies and Restrictive Trade Practices Commission (MRTPC)',
        C: 'Securities and Exchange Board of India (SEBI)',
        D: 'Telecom Regulatory Authority of India (TRAI)',
      },
      correctAnswer: 'A',
      explanation: 'The Competition Act 2002 established the CCI to replace the restrictive MRTP Act, promoting open fair market competition in India.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'Under the Income Tax Act 1961, what is the maximum deduction allowed to an individual taxpayer under Section 80C for eligible investments in PPF, ELSS, EPF, Life Insurance, and Principal Home Loan Repayment?',
      questionType: 'Direct MCQ',
      options: {
        A: '₹1,50,000 per financial year',
        B: '₹1,00,000 per financial year',
        C: '₹2,00,000 per financial year',
        D: '₹50,000 per financial year',
      },
      correctAnswer: 'A',
      explanation: 'Section 80C caps aggregate annual deductions for specified long-term savings at ₹1.50 Lakh under the old tax regime.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'Under the Income Tax Act 1961, an individual is treated as a "Resident in India" in a previous financial year if they satisfy which basic condition under Section 6(1)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'They are in India for a period of at least 182 days during that previous year OR at least 60 days in that year and 365 days in the 4 preceding years',
        B: 'They own agricultural land in India',
        C: 'They hold an Indian passport',
        D: 'They pay property tax to a municipal corporation in India',
      },
      correctAnswer: 'A',
      explanation: 'Section 6(1) sets the physical presence tests of 182 days in the financial year or 60 days + 365 days across preceding 4 years for Indian tax residency.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'Under Section 92 of the Income Tax Act 1961, international transactions between Associated Enterprises (AEs) must be computed having regard to the:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Arm\'s Length Price (ALP) using specified methods like CUP, Resale Price, Cost Plus, Profit Split, or TNMM',
        B: 'Historical Book Value',
        C: 'Maximum retail price in the foreign country',
        D: 'Zero tax treaty exemption value',
      },
      correctAnswer: 'A',
      explanation: 'Transfer pricing regulations under Section 92C mandate computing income from international cross-border transactions at Arm\'s Length Price (ALP) to prevent base erosion.',
      difficulty: 'MEDIUM',
    },
  ];

  return {
    subjectCode: '08',
    subjectSlug: 'commerce',
    mockNumber: 1,
    title: 'Commerce — Mock Test 1: Full Syllabus Simulation (100 Qs)',
    description: 'Authentic 100-question UGC NET Commerce simulation covering Business Environment, Accounting, Economics, Finance, Statistics, HRM, Banking, Marketing, Commercial Law, and Income Tax across all 10 units.',
    accessTier: 'FREE',
    isFreeBenchmark: true,
    questions,
  };
}
