import { MockTestDefinition, RawMockQuestion } from '../common';

export function getComputerScienceMockTest(): MockTestDefinition {
  const questions: RawMockQuestion[] = [
    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 1: DISCRETE STRUCTURES AND OPTIMIZATION (10 Questions: Q1 - Q10)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 1,
      questionText: 'For a simple connected planar graph with $V$ vertices, $E$ edges, and $F$ faces, Euler\'s formula states that:',
      questionType: 'Direct MCQ',
      options: {
        A: '$V - E + F = 2$',
        B: '$V + E - F = 2$',
        C: '$V - E - F = 2$',
        D: '$V + E + F = 2$',
      },
      correctAnswer: 'A',
      explanation: 'Euler\'s formula for connected planar graphs is $V - E + F = 2$. For example, a triangle has $V=3, E=3, F=2$ (1 interior + 1 exterior) $\\implies 3 - 3 + 2 = 2$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'How many different simple undirected graphs can be constructed on $n$ labeled vertices?',
      questionType: 'Direct MCQ',
      options: {
        A: '$2^{n(n-1)/2}$',
        B: '$2^n$',
        C: '$n!$',
        D: '$n(n-1)/2$',
      },
      correctAnswer: 'A',
      explanation: 'Between $n$ vertices, there are $\\binom{n}{2} = \\frac{n(n-1)}{2}$ possible edges. Since each edge can either be present or absent, the total number of graphs is $2^{\\binom{n}{2}} = 2^{n(n-1)/2}$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In mathematical logic, the proposition $(P \\to Q) \\equiv (\\neg P \\lor Q)$ represents which fundamental equivalence?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Material Implication Law',
        B: 'De Morgan\'s Law',
        C: 'Absorption Law',
        D: 'Distributive Law',
      },
      correctAnswer: 'A',
      explanation: 'The Law of Material Implication establishes that a conditional statement $P \\to Q$ is logically equivalent to $\\neg P \\lor Q$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In group theory, a group $(G, *)$ in which the group operation is commutative ($a * b = b * a$ for all $a, b \\in G$) is termed an:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Abelian group (named after Niels Henrik Abel)',
        B: 'Cyclic monoid',
        C: 'Semi-group',
        D: 'Coset ring',
      },
      correctAnswer: 'A',
      explanation: 'An Abelian group is a group satisfying closure, associativity, identity, invertibility, and commutativity.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In linear programming problems (LPP), the Simplex Method developed by George Dantzig finds the optimal solution by moving between adjacent:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Extreme points / Basic Feasible Solutions (BFS) on the convex feasible polyhedron boundary',
        B: 'Interior points along the center of gravity',
        C: 'Unbounded infinite rays',
        D: 'Random coordinate points outside constraints',
      },
      correctAnswer: 'A',
      explanation: 'The Fundamental Theorem of Linear Programming guarantees that an optimal solution occurs at an extreme vertex (Basic Feasible Solution) of the convex polyhedral feasible region.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'According to the Pigeonhole Principle, what is the minimum number of students needed in a classroom to guarantee that at least two of them share the same birth month?',
      questionType: 'Direct MCQ',
      options: {
        A: '$13$',
        B: '$12$',
        C: '$24$',
        D: '$365$',
      },
      correctAnswer: 'A',
      explanation: 'With 12 months (pigeonholes), having $12 + 1 = 13$ students (pigeons) guarantees by $\\lceil 13/12 \\rceil = 2$ that at least one month contains at least 2 birthdays.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'A binary relation $R$ on a set $A$ is defined as an "Equivalence Relation" if and only if it satisfies:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Reflexivity, Symmetry, and Transitivity',
        B: 'Reflexivity, Antisymmetry, and Transitivity (Partial Order)',
        C: 'Irreflexivity, Asymmetry, and Intransitivity',
        D: 'Symmetry and Antisymmetry simultaneously',
      },
      correctAnswer: 'A',
      explanation: 'An equivalence relation partitions a set into disjoint equivalence classes and must be Reflexive ($aRa$), Symmetric ($aRb \\implies bRa$), and Transitive ($aRb \\land bRc \\implies aRc$).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'What is the chromatic number $\\chi(K_n)$ of a complete graph $K_n$ with $n$ vertices?',
      questionType: 'Direct MCQ',
      options: {
        A: '$n$',
        B: '$n-1$',
        C: '$2$',
        D: '$\\lfloor n/2 \\rfloor$',
      },
      correctAnswer: 'A',
      explanation: 'In a complete graph $K_n$, every vertex is adjacent to all other $n-1$ vertices. Therefore, no two vertices can share the same colour, requiring exactly $n$ distinct colours ($\\\\chi(K_n) = n$).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In propositional satisfiability (Boolean logic), which normal form consists of a conjunction (AND) of one or more clauses, where each clause is a disjunction (OR) of literals?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Conjunctive Normal Form (CNF / Product of Sums)',
        B: 'Disjunctive Normal Form (DNF / Sum of Products)',
        C: 'Prenex Normal Form',
        D: 'Skolem Normal Form',
      },
      correctAnswer: 'A',
      explanation: 'CNF is an expression of the structure $\\bigwedge_i \\left(\\bigvee_j L_{ij}\\right)$, such as $(A \\lor \\neg B) \\land (C \\lor D)$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In Boolean algebra, the dual of the identity $A + (B \\cdot C) = (A + B) \\cdot (A + C)$ obtained by swapping $+$ with $\\cdot$ and $0$ with $1$ is:',
      questionType: 'Direct MCQ',
      options: {
        A: '$A \\cdot (B + C) = (A \\cdot B) + (A \\cdot C)$',
        B: '$A + B = B + A$',
        C: '$A \\cdot A = A$',
        D: '$\\neg(A + B) = \\neg A \\cdot \\neg B$',
      },
      correctAnswer: 'A',
      explanation: 'By the Principle of Duality in Boolean algebra, replacing all OR ($+$) with AND ($\\cdot$) and vice-versa yields the dual distributive law $A(B+C) = AB + AC$.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 2: COMPUTER SYSTEM ARCHITECTURE (10 Questions: Q11 - Q20)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 2,
      questionText: 'In 8-bit Two\'s Complement representation, what is the binary encoding of the decimal number $-45_{10}$?',
      questionType: 'Direct MCQ',
      options: {
        A: '$11010011_2$',
        B: '$11010010_2$',
        C: '$10101101_2$',
        D: '$00101101_2$',
      },
      correctAnswer: 'A',
      explanation: '$+45 = 00101101_2$. One\'s complement = $11010010_2$. Adding $1 \\implies 11010011_2$.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'In computer memory hierarchy, what is the typical order of storage technologies from fastest access time (lowest latency) to slowest access time?',
      questionType: 'Direct MCQ',
      options: {
        A: 'CPU Registers $\\rightarrow$ L1 Cache $\\rightarrow$ L2 Cache $\\rightarrow$ Main Memory (DRAM) $\\rightarrow$ Secondary SSD / Hard Disk',
        B: 'Main Memory $\\rightarrow$ L1 Cache $\\rightarrow$ CPU Registers $\\rightarrow$ SSD',
        C: 'L1 Cache $\\rightarrow$ CPU Registers $\\rightarrow$ Main Memory $\\rightarrow$ Hard Disk',
        D: 'SSD $\\rightarrow$ Main Memory $\\rightarrow$ L2 Cache $\\rightarrow$ L1 Cache $\\rightarrow$ Registers',
      },
      correctAnswer: 'A',
      explanation: 'Registers ($<1\\text{ ns}$) $\\rightarrow$ L1 SRAM Cache ($1\\text{ ns}$) $\\rightarrow$ L2 SRAM ($3-5\\text{ ns}$) $\\rightarrow$ DRAM ($50-100\\text{ ns}$) $\\rightarrow$ SSD/HDD ($100\\,\\mu\\text{s} - 10\\text{ ms}$).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In instruction pipelining, a "Data Hazard" (such as Read-After-Write / RAW dependency) occurs when:',
      questionType: 'Direct MCQ',
      options: {
        A: 'An instruction depends on the result of a prior instruction that is still executing in the pipeline and has not yet written back to the register file',
        B: 'Two instructions attempt to access the same memory port simultaneously',
        C: 'A branch instruction changes the Program Counter unexpectedly',
        D: 'The clock frequency fluctuates during arithmetic overflow',
      },
      correctAnswer: 'A',
      explanation: 'RAW data hazards occur when instruction $J$ tries to read operand $R$ before prior instruction $I$ writes its computed result to $R$. This is resolved via Operand Forwarding / Bypassing or pipeline stalls (NOPs).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'According to Amdahl\'s Law, if $80\\%$ of a computer program can be parallelized across $N$ parallel processor cores ($P = 0.8$), what is the theoretical maximum speedup limit as $N \\to \\infty$?',
      questionType: 'Direct MCQ',
      options: {
        A: '$5\\times$',
        B: '$4\\times$',
        C: '$10\\times$',
        D: '$\\infty$',
      },
      correctAnswer: 'A',
      explanation: '$\\text{Speedup} = \\frac{1}{(1-P) + P/N}$. As $N \\to \\infty$, $\\text{Speedup} = \\frac{1}{1 - 0.8} = \\frac{1}{0.2} = 5\\times$.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'In Direct Memory Access (DMA) data transfer, what happens during "Cycle Stealing" mode?',
      questionType: 'Direct MCQ',
      options: {
        A: 'The DMA controller takes control of the system bus from the CPU for transferring one single byte or word at a time, pausing the CPU for one bus cycle',
        B: 'The DMA transfers entire blocks of data continuously while holding the bus locked for millions of cycles',
        C: 'The CPU directly executes polling instructions inside the memory controller',
        D: 'The system clock speed is doubled during interrupts',
      },
      correctAnswer: 'A',
      explanation: 'Cycle Stealing allows the DMA controller to interleave single-word memory transfers with CPU operations without stalling CPU execution for prolonged durations.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'In microprogrammed control unit architecture, a "Horizontal Microinstruction" is characterized by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Wide control word where each control bit directly activates a separate hardware control signal without decoding, allowing high parallelism',
        B: 'Highly compressed, encoded control fields requiring decoders to generate control signals (Vertical)',
        C: 'Hardwired logic implemented purely through combinational NAND gates',
        D: 'Execution of assembly language instructions without microcode ROM',
      },
      correctAnswer: 'A',
      explanation: 'Horizontal microinstructions have 1 bit per control signal (unencoded), resulting in wide words, minimal decoding delay, and high concurrency.',
      difficulty: 'HARD',
    },
    {
      unitNumber: 2,
      questionText: 'A cache memory with a block size of 64 bytes is designed as 4-way Set Associative with 512 total cache lines. How many sets does the cache contain?',
      questionType: 'Direct MCQ',
      options: {
        A: '$128\\text{ sets}$',
        B: '$256\\text{ sets}$',
        C: '$512\\text{ sets}$',
        D: '$64\\text{ sets}$',
      },
      correctAnswer: 'A',
      explanation: '$\\text{Number of Sets} = \\frac{\\text{Total Cache Lines}}{\\text{Associativity (Ways)}} = \\frac{512}{4} = 128\\text{ sets}$ ($2^7 \\implies 7\\text{ set index bits}$).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'In IEEE 754 Single-Precision Floating-Point standard (32-bit), the bit allocation for Sign ($S$), Biased Exponent ($E$), and Fraction/Mantissa ($M$) is:',
      questionType: 'Direct MCQ',
      options: {
        A: '1 Sign bit, 8 Exponent bits (Bias = 127), 23 Mantissa bits',
        B: '1 Sign bit, 11 Exponent bits (Bias = 1023), 52 Mantissa bits (Double Precision)',
        C: '2 Sign bits, 6 Exponent bits, 24 Mantissa bits',
        D: '1 Sign bit, 16 Exponent bits, 15 Mantissa bits',
      },
      correctAnswer: 'A',
      explanation: 'Single precision allocates: Bit 31 (Sign), Bits 30-23 (8-bit exponent with bias 127), and Bits 22-0 (23-bit normalized significand with implicit leading 1).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'Which addressing mode specifies the operand directly within the instruction itself without requiring any memory or register lookup (e.g., `MOV R1, #25`)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Immediate Addressing Mode',
        B: 'Direct Addressing Mode',
        C: 'Register Indirect Addressing Mode',
        D: 'Indexed Addressing Mode',
      },
      correctAnswer: 'A',
      explanation: 'In Immediate Addressing, the operand value is part of the instruction opcode bytes, providing fastest operand access.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'What is the minimum number of 2-input NAND gates required to construct a 2-input XOR gate?',
      questionType: 'Direct MCQ',
      options: {
        A: '$4$',
        B: '$3$',
        C: '$5$',
        D: '$2$',
      },
      correctAnswer: 'A',
      explanation: 'A 2-input XOR ($A \\oplus B = A\\bar{B} + \\bar{A}B$) can be implemented using exactly 4 universal 2-input NAND gates.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 3: PROGRAMMING LANGUAGES AND GRAPHICS (10 Questions: Q21 - Q30)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 3,
      questionText: 'In Object-Oriented Programming, what mechanism allows a subclass to provide a specific implementation of a method that is already defined in its superclass, resolved at runtime?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Method Overriding (Dynamic / Runtime Polymorphism via vtable)',
        B: 'Method Overloading (Compile-time / Static Polymorphism)',
        C: 'Data Encapsulation',
        D: 'Private Inheritance',
      },
      correctAnswer: 'A',
      explanation: 'Method Overriding allows dynamic method dispatch at runtime based on the actual instantiated object type using virtual method tables (vtables).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In computer graphics line-drawing algorithms, Bresenham\'s Algorithm is computationally superior to the Digital Differential Analyzer (DDA) because:',
      questionType: 'Direct MCQ',
      options: {
        A: 'It uses only fast incremental integer arithmetic (addition and shift) without floating-point calculations or rounding operations',
        B: 'It calculates trigonometric cosine functions for each pixel',
        C: 'It anti-aliases every polygon using supersampling',
        D: 'It relies on GPU ray tracing shaders',
      },
      correctAnswer: 'A',
      explanation: 'Bresenham\'s algorithm uses integer decision parameters ($d = 2\\Delta y - \\Delta x$), avoiding all floating-point division and multiplications in the inner raster loop.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'In 3D computer graphics transformations, why are 4x4 "Homogeneous Coordinates" standardly used for 3D geometric transformations?',
      questionType: 'Direct MCQ',
      options: {
        A: 'They allow translation, rotation, scaling, and perspective projection to be represented uniformly as matrix multiplications and concatenated easily',
        B: 'They reduce floating point numbers to 8-bit integers',
        C: 'They automatically eliminate hidden surfaces',
        D: 'They prevent color clipping in the frame buffer',
      },
      correctAnswer: 'A',
      explanation: 'Homogeneous coordinates represent affine transformations (including translation $[x, y, z, 1]^T$) and perspective projections as linear matrix multiplications that compose through matrix product.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'Which polygon clipping algorithm uses a divide-and-conquer pipeline against four clipping boundary planes (Left, Right, Bottom, Top) in 2D space?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Sutherland-Hodgman Polygon Clipping Algorithm',
        B: 'Cohen-Sutherland Line Clipping (Outcodes)',
        C: 'Liang-Barsky Line Clipping (Parametric)',
        D: 'Weiler-Atherton Polygon Clipping',
      },
      correctAnswer: 'A',
      explanation: 'Sutherland-Hodgman clips a polygon sequentially against each infinite clip boundary edge, outputting a valid new polygon vertex list.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'In C++, a class that contains at least one "pure virtual function" (`virtual void draw() = 0;`) is termed an:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Abstract Base Class (cannot be directly instantiated)',
        B: 'Singleton Class',
        C: 'Template Specialization',
        D: 'Static Friend Class',
      },
      correctAnswer: 'A',
      explanation: 'An Abstract Class defines an interface with pure virtual functions and cannot be instantiated directly; concrete derived classes must implement all pure virtual methods.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'What is the output of the following recursive C function when invoked as `f(5)`?\n```c\nint f(int n) {\n    if (n <= 1) return 1;\n    return n * f(n - 1);\n}\n```',
      questionType: 'Direct MCQ',
      options: {
        A: '$120$',
        B: '$24$',
        C: '$720$',
        D: '$15$',
      },
      correctAnswer: 'A',
      explanation: 'The function computes the factorial $n!$. For $n=5$: $5 \\times 4 \\times 3 \\times 2 \\times 1 = 120$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In 3D computer animation, the process of interpolating smooth intermediate frames between two keyframes specified by the animator is known as:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Tweening (Inbetweening)',
        B: 'Morphing',
        C: 'Rigging',
        D: 'Rasterization',
      },
      correctAnswer: 'A',
      explanation: 'Tweening generates in-between frames between keyframes using linear, Bezier, or spline interpolation curves.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'Which parameter passing mechanism evaluates the argument expression every time it is referenced inside the called function (lazy evaluation via thunk)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Pass by Name (ALGOL 60)',
        B: 'Pass by Value',
        C: 'Pass by Reference',
        D: 'Pass by Value-Result (Copy-in Copy-out)',
      },
      correctAnswer: 'A',
      explanation: 'Pass-by-name substitutes the argument expression textually into the function body and evaluates it dynamically each time it is used (Jensen\'s Device).',
      difficulty: 'HARD',
    },
    {
      unitNumber: 3,
      questionText: 'In Phong Reflection Model in 3D computer graphics, total reflected surface illumination is calculated as the sum of which three components?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Ambient reflection, Diffuse reflection (Lambertian), and Specular reflection (Highlights)',
        B: 'Refraction, Transmission, and Absorption',
        C: 'Shadow, Halftone, and Vignette',
        D: 'RGB, CMYK, and HSV channels',
      },
      correctAnswer: 'A',
      explanation: 'Phong reflection model combines Ambient ($I_a k_a$), Diffuse ($I_d k_d (N \\cdot L)$), and Specular ($I_s k_s (R \\cdot V)^n$) light components.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'In Java, which garbage collection algorithm identifies live objects by traversing object reference graphs starting from "GC Roots" and reclaims unvisited memory?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Mark and Sweep / Tracing Garbage Collection',
        B: 'Reference Counting (suffers from cyclic leak)',
        C: 'Manual Stack Deallocation',
        D: 'Static Array Compaction',
      },
      correctAnswer: 'A',
      explanation: 'Mark-and-Sweep marks all reachable objects starting from root pointers (local variables, active threads, static fields) and sweeps away unreferenced garbage memory.',
      difficulty: 'MEDIUM',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 4: DATABASE MANAGEMENT SYSTEMS (10 Questions: Q31 - Q40)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 4,
      questionText: 'In relational database theory, a relation $R$ is in Third Normal Form (3NF) if for every non-trivial functional dependency $X \\to Y$:',
      questionType: 'Direct MCQ',
      options: {
        A: '$X$ is a Superkey OR $Y$ is a Prime Attribute (member of a candidate key)',
        B: '$X$ is always a foreign key',
        C: '$Y$ is a multi-valued attribute',
        D: 'There are no candidate keys in the relation',
      },
      correctAnswer: 'A',
      explanation: '3NF eliminates transitive dependencies: for every non-trivial $X \\to Y$, either $X$ is a superkey or $Y$ is prime. If $X$ must strictly be a superkey for all dependencies, it satisfies BCNF.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'In transaction processing, the "ACID" properties ensuring reliability and data consistency stand for:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Atomicity, Consistency, Isolation, and Durability',
        B: 'Availability, Concurrency, Integrity, and Distribution',
        C: 'Authentication, Cryptography, Identity, and Decryption',
        D: 'Abstraction, Cardinality, Inheritance, and Delegation',
      },
      correctAnswer: 'A',
      explanation: 'ACID: Atomicity (all or nothing via undo logs), Consistency (preserves schema constraints), Isolation (concurrency control via 2PL/MVCC), Durability (committed data survives crashes via redo logs).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'In database indexing, a B+ Tree is preferred over a standard B-Tree for disk storage indexing primarily because:',
      questionType: 'Direct MCQ',
      options: {
        A: 'All actual data records/pointers are stored exclusively in the leaf nodes, and leaf nodes are linked sequentially in a doubly-linked list, enabling extremely fast range queries',
        B: 'B+ trees do not require any balancing operations',
        C: 'B+ trees have a fixed height of 2 regardless of table size',
        D: 'B+ trees eliminate the need for primary keys',
      },
      correctAnswer: 'A',
      explanation: 'B+ Trees store search keys only in internal routing nodes (maximizing fan-out) and keep all data pointers in linked leaf nodes for rapid range scans and high storage density.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'In Two-Phase Locking (2PL) concurrency control protocol, which of the following guarantees Conflict Serializability?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Basic Two-Phase Locking (Growing phase where locks are acquired, followed by Shrinking phase where locks are released)',
        B: 'Releasing locks before acquiring new ones',
        C: 'Unconstrained shared lock acquisition',
        D: 'Immediate commit without write locks',
      },
      correctAnswer: 'A',
      explanation: 'The 2PL theorem guarantees that any schedule produced by 2PL is conflict-serializable (though Strict 2PL is required to prevent cascading aborts).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'What relational algebra operator performs a Cartesian Product followed by a Selection condition matching common attribute values?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Theta Join / Natural Join ($\\bowtie$)',
        B: 'Projection ($\\Pi$)',
        C: 'Selection ($\\sigma$)',
        D: 'Division ($\\div$)',
      },
      correctAnswer: 'A',
      explanation: 'A Join ($R \\bowtie_{condition} S$) is mathematically defined as $\\sigma_{condition}(R \\times S)$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'In SQL, what is the key difference between the `WHERE` clause and the `HAVING` clause?',
      questionType: 'Direct MCQ',
      options: {
        A: '`WHERE` filters individual rows before grouping; `HAVING` filters aggregated groups created by `GROUP BY`',
        B: '`WHERE` is used only in subqueries; `HAVING` is used only in delete operations',
        C: '`HAVING` cannot use comparison operators like `>` or `=`',
        D: '`WHERE` applies only to string columns',
      },
      correctAnswer: 'A',
      explanation: '`WHERE` filters base tuples before aggregate functions are computed. `HAVING` applies filtering predicates to aggregated summary groups (e.g. `HAVING COUNT(*) > 5`).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'In transaction recovery, the Write-Ahead Logging (WAL) protocol dictates that:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The log record describing an update must be flushed to stable non-volatile storage before the corresponding modified data page is written to disk',
        B: 'Data pages must be written to disk before log records are generated',
        C: 'Transactions must not write any logs during commit',
        D: 'Log records are stored exclusively in volatile RAM',
      },
      correctAnswer: 'A',
      explanation: 'WAL ensures Atomicity and Durability by requiring log updates to reach stable disk storage before dirty buffer pool pages are written to database files.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'Given relation $R(A, B, C, D, E)$ with functional dependencies $F = \\{ A \\to B, B \\to C, C \\to D, D \\to E, E \\to A \\}$. How many Candidate Keys does relation $R$ have?',
      questionType: 'Direct MCQ',
      options: {
        A: '$5$ candidate keys ($\\{A\\}, \\{B\\}, \\{C\\}, \\{D\\}, \\{E\\}$)',
        B: '$1$ candidate key ($\\{A\\}$)',
        C: '$2$ candidate keys',
        D: '$0$',
      },
      correctAnswer: 'A',
      explanation: 'Because the dependencies form a complete directed cycle ($A \\to B \\to C \\to D \\to E \\to A$), the closure of any single attribute contains all five attributes: $A^+ = B^+ = C^+ = D^+ = E^+ = \\{A,B,C,D,E\\}$. Thus each singleton is a candidate key.',
      difficulty: 'HARD',
    },
    {
      unitNumber: 4,
      questionText: 'In ER modelling, an entity set that does not possess sufficient attributes to form a primary key of its own and depends on an identifying relationship with an owner entity is called a:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Weak Entity Set (represented by a double rectangle)',
        B: 'Strong Entity Set',
        C: 'Associative Entity',
        D: 'Recursive Entity',
      },
      correctAnswer: 'A',
      explanation: 'A Weak Entity Set lacks a primary key and is identified by combining its partial key (discriminator) with the primary key of its identifying owner entity.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'In NoSQL database systems, the CAP Theorem (Brewer\'s Theorem) states that a distributed data store can simultaneously provide at most two of which three guarantees?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Consistency, Availability, and Partition Tolerance',
        B: 'Atomicity, Concurrency, and Performance',
        C: 'Capacity, Authentication, and Privacy',
        D: 'Caching, Compression, and Parallelism',
      },
      correctAnswer: 'A',
      explanation: 'CAP Theorem proves that in the inevitable presence of network partitions ($P$), a distributed system must trade off between strict consistency ($C$) or high availability ($A$).',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 5: SYSTEM SOFTWARE AND OPERATING SYSTEM (10 Questions: Q41 - Q50)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 5,
      questionText: 'Which four necessary and sufficient conditions formulated by E.G. Coffman must hold simultaneously for a system Deadlock to occur?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait',
        B: 'Starvation, Aging, Thrashing, and Swapping',
        C: 'Paging, Segmentation, Fragmentation, and Compaction',
        D: 'Race Condition, Critical Section, Semaphore, and Mutex',
      },
      correctAnswer: 'A',
      explanation: 'Coffman conditions: (1) Mutual Exclusion (non-shareable resources), (2) Hold & Wait (holding resources while requesting others), (3) No Preemption (resources cannot be forcibly confiscated), (4) Circular Wait ($P_0 \\to P_1 \\to \\dots \\to P_0$).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'In virtual memory management, "Belady\'s Anomaly" refers to the counter-intuitive phenomenon where:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Increasing the number of allocated physical page frames results in an INCREASE in the number of page faults (under FIFO page replacement)',
        B: 'The CPU utilization drops to zero during thrashing',
        C: 'LRU page replacement runs in exponential time',
        D: 'Virtual addresses become smaller than physical addresses',
      },
      correctAnswer: 'A',
      explanation: 'Belady\'s Anomaly occurs in non-stack page replacement algorithms such as FIFO, where adding memory frames can increase page faults for specific reference strings.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'In operating systems, the Banker\'s Algorithm developed by Edsger Dijkstra is used for:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Deadlock Avoidance (ensuring the system remains in a Safe State before granting resource requests)',
        B: 'Deadlock Prevention by eliminating Mutual Exclusion',
        C: 'Deadlock Detection after system freeze',
        D: 'CPU Burst Time estimation',
      },
      correctAnswer: 'A',
      explanation: 'The Banker\'s algorithm tests whether granting a resource request leaves the system in a "Safe State" where a valid process execution sequence exists satisfying all maximum resource claims.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'In process synchronization, what is a "Race Condition"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'A situation where multiple concurrent threads access and manipulate shared data, and the final outcome depends on the exact order of execution and scheduling',
        B: 'A contest between processes to consume maximum CPU cycles',
        C: 'A high-speed DMA bus transmission',
        D: 'A network packet routing loop',
      },
      correctAnswer: 'A',
      explanation: 'A race condition occurs when unsynchronized concurrent access to shared resources produces unpredictable outputs depending on non-deterministic thread interleavings.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'Consider 4 processes with CPU burst times $P_1=6, P_2=8, P_3=7, P_4=3$ arriving at time $t=0$. Under Non-Preemptive Shortest Job First (SJF) scheduling, what is the average waiting time?',
      questionType: 'Direct MCQ',
      options: {
        A: '$7\\text{ ms}$',
        B: '$8\\text{ ms}$',
        C: '$9\\text{ ms}$',
        D: '$10.25\\text{ ms}$',
      },
      correctAnswer: 'A',
      explanation: 'Execution order: $P_4(3) \\rightarrow P_1(6) \\rightarrow P_3(7) \\rightarrow P_2(8)$. Waiting times: $P_4=0, P_1=3, P_3=3+6=9, P_2=9+7=16$. Total waiting time = $0 + 3 + 9 + 16 = 28$. Average = $28 / 4 = 7\\text{ ms}$.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'In memory management, "Thrashing" occurs when:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The operating system spends significantly more time swapping pages in and out of secondary storage than executing actual application instructions',
        B: 'The CPU cache experiences 100% hit rate',
        C: 'A process causes a divide-by-zero hardware exception',
        D: 'The hard drive platter physically vibrates',
      },
      correctAnswer: 'A',
      explanation: 'Thrashing occurs when the sum of locality working sets across active processes exceeds total available physical RAM, causing continuous cascade page faulting and near-zero CPU utilization.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'In UNIX / Linux operating systems, what is the system call used to create a duplicate child process that inherits the parent\'s address space and file descriptors?',
      questionType: 'Direct MCQ',
      options: {
        A: '`fork()`',
        B: '`exec()`',
        C: '`wait()`',
        D: '`kill()`',
      },
      correctAnswer: 'A',
      explanation: '`fork()` creates an exact clone child process returning $0$ to the child process and the child\'s PID to the parent process.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'A Counting Semaphore $S$ is initialized to $10$. Subsequently, $6$ `P(S)` (Wait / decrement) operations and $4$ `V(S)` (Signal / increment) operations are completed. What is the final value of $S$?',
      questionType: 'Direct MCQ',
      options: {
        A: '$8$',
        B: '$6$',
        C: '$12$',
        D: '$0$',
      },
      correctAnswer: 'A',
      explanation: 'Initial value = 10. Each `P(S)` decrements by 1 ($-6$). Each `V(S)` increments by 1 ($+4$). Final value = $10 - 6 + 4 = 8$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'In language translation and compilers, the phase of the compiler that analyzes lexical tokens against context-free grammar production rules to generate a Parse Tree is:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Syntax Analysis (Parsing)',
        B: 'Lexical Analysis (Scanning)',
        C: 'Semantic Analysis (Type checking)',
        D: 'Code Optimization',
      },
      correctAnswer: 'A',
      explanation: 'Syntax Analysis / Parsing takes a stream of tokens from the lexer and constructs an Abstract Syntax Tree (AST) validating grammatical syntax.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'In disk scheduling algorithms, which algorithm moves the disk arm across the disk from one end to the other servicing requests, then immediately reverses direction servicing requests in reverse (Elevator Algorithm)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'SCAN Algorithm',
        B: 'C-SCAN (Circular SCAN)',
        C: 'FCFS (First Come First Served)',
        D: 'SSTF (Shortest Seek Time First)',
      },
      correctAnswer: 'A',
      explanation: 'SCAN moves the head bidirectionally like an elevator, servicing cylinders on the way up, reversing at the boundary and servicing on the way down.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 6: SOFTWARE ENGINEERING (10 Questions: Q51 - Q60)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 6,
      questionText: 'In modular software design, high-quality software architecture is characterized by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'High Cohesion (elements within a module are closely related) and Low Coupling (minimal inter-module dependencies)',
        B: 'Low Cohesion and High Coupling',
        C: 'High Coupling and High Duplication',
        D: 'Zero Cohesion and Direct Global Variable sharing',
      },
      correctAnswer: 'A',
      explanation: 'Good software engineering enforces High Functional Cohesion (single focused responsibility) and Loose Coupling (independence, encapsulation).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'In Barry Boehm\'s Basic COCOMO (Constructive Cost Model), software development effort $E$ in Person-Months is estimated using the formula:',
      questionType: 'Direct MCQ',
      options: {
        A: '$E = a \\times (\\text{KLOC})^b$',
        B: '$E = a + b \\times \\text{KLOC}$',
        C: '$E = \\text{KLOC} / (a \\times b)$',
        D: '$E = a^b \\times \\log(\\text{KLOC})$',
      },
      correctAnswer: 'A',
      explanation: 'COCOMO models effort non-linearly as $E = a(\\text{KLOC})^b$, with parameters $a, b$ calibrated for Organic, Semi-Detached, and Embedded project modes.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 6,
      questionText: 'Thomas McCabe\'s Cyclomatic Complexity $V(G)$ for a structured software control flow graph with $E$ edges, $N$ nodes, and $P$ connected components ($P=1$) is given by:',
      questionType: 'Direct MCQ',
      options: {
        A: '$V(G) = E - N + 2P$',
        B: '$V(G) = E + N - P$',
        C: '$V(G) = N - E + 2$',
        D: '$V(G) = E / N$',
      },
      correctAnswer: 'A',
      explanation: 'McCabe\'s Cyclomatic Complexity formula is $V(G) = E - N + 2P$ (or number of enclosed binary decision regions $+ 1$), measuring the number of linearly independent execution paths.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 6,
      questionText: 'In Software Testing methodology, "Cyclomatic complexity", "Branch coverage", and "Basis path testing" are techniques belonging to:',
      questionType: 'Direct MCQ',
      options: {
        A: 'White-Box Testing (Structural / Glass-Box Testing)',
        B: 'Black-Box Testing (Functional / Specification-Based)',
        C: 'User Acceptance Alpha Testing',
        D: 'Stress and Volume Testing',
      },
      correctAnswer: 'A',
      explanation: 'White-box testing inspects internal code paths, control logic, loops, and branch conditions.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'In Agile Scrum framework, what is the fixed time-boxed development cycle (typically 1 to 4 weeks) during which a cross-functional team delivers a potentially shippable product increment?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Sprint',
        B: 'Epic',
        C: 'Backlog Grooming',
        D: 'Water-Scrum',
      },
      correctAnswer: 'A',
      explanation: 'A Sprint is the fundamental time-boxed iteration in Scrum during which planned user stories are developed, tested, and demonstrated.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'The Capability Maturity Model Integration (CMMI) defines five progressive levels of software process maturity. What is the correct ascending order?',
      questionType: 'Direct MCQ',
      options: {
        A: '1: Initial $\\rightarrow$ 2: Managed $\\rightarrow$ 3: Defined $\\rightarrow$ 4: Quantitatively Managed $\\rightarrow$ 5: Optimizing',
        B: '1: Ad-hoc $\\rightarrow$ 2: Defined $\\rightarrow$ 3: Repeatable $\\rightarrow$ 4: Testing $\\rightarrow$ 5: Final',
        C: '1: Managed $\\rightarrow$ 2: Initial $\\rightarrow$ 3: Quantitatively Managed $\\rightarrow$ 4: Defined $\\rightarrow$ 5: Complete',
        D: '1: Level A $\\rightarrow$ 2: Level B $\\rightarrow$ 3: Level C $\\rightarrow$ 4: Level D $\\rightarrow$ 5: Level E',
      },
      correctAnswer: 'A',
      explanation: 'CMMI Levels: 1 (Initial - unpredictable), 2 (Managed - project level), 3 (Defined - organization standards), 4 (Quantitatively Managed - measured), 5 (Optimizing - continuous innovation).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 6,
      questionText: 'Which software design pattern ensures that a class has only one single instance globally throughout the entire application lifecycle and provides a global access point to it?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Singleton Pattern',
        B: 'Factory Method Pattern',
        C: 'Observer Pattern',
        D: 'Adapter Pattern',
      },
      correctAnswer: 'A',
      explanation: 'The GoF Singleton Creational Pattern restricts class instantiation to a single object with a private constructor and a static `getInstance()` method.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'In software maintenance, modifying a software system after delivery to correct newly discovered runtime bugs and operational defects is called:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Corrective Maintenance',
        B: 'Adaptive Maintenance (adapting to new OS / hardware)',
        C: 'Perfective Maintenance (adding new features)',
        D: 'Preventive Maintenance (refactoring for future reliability)',
      },
      correctAnswer: 'A',
      explanation: 'Corrective maintenance repairs defects/bugs. Adaptive modifies for changed environments. Perfective enhances performance/features. Preventive refactors to prevent decay.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'Which software development process model incorporates explicit Risk Analysis and Risk Management in each iterative loop before moving to development?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Boehm\'s Spiral Model',
        B: 'Classical Waterfall Model',
        C: 'V-Model (Verification and Validation)',
        D: 'RAD Model',
      },
      correctAnswer: 'A',
      explanation: 'Barry Boehm\'s Spiral Model is risk-driven, combining iterative prototyping with structured milestone gates and risk assessment quadrants.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'In black-box testing, dividing the input domain into partitions of valid and invalid data values where all values in a partition are assumed to behave identically is termed:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Equivalence Class Partitioning (ECP)',
        B: 'Boundary Value Analysis (BVA)',
        C: 'Cause-Effect Graphing',
        D: 'Mutation Testing',
      },
      correctAnswer: 'A',
      explanation: 'Equivalence Partitioning reduces redundant test cases by selecting representative test values from each valid and invalid input equivalence class.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 7: DATA COMMUNICATIONS AND NETWORKS (10 Questions: Q61 - Q70)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 7,
      questionText: 'In the 7-Layer OSI Reference Model, which layer is responsible for logical IP addressing, end-to-end packet routing, and subnet management across heterogeneous networks?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Network Layer (Layer 3)',
        B: 'Data Link Layer (Layer 2 - MAC frames)',
        C: 'Transport Layer (Layer 4 - Port segments)',
        D: 'Session Layer (Layer 5)',
      },
      correctAnswer: 'A',
      explanation: 'Layer 3 (Network Layer) manages IP addressing, packet forwarding, routing algorithms (OSPF, BGP), and fragmentation.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'In TCP congestion control, how does the Congestion Window ($cwnd$) grow during the "Slow Start" phase upon the receipt of each successful acknowledgement (ACK)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Exponentially ($cwnd$ doubles every Round Trip Time / RTT)',
        B: 'Linearly (Additive Increase of 1 MSS per RTT)',
        C: 'Multiplicatively decreases by half',
        D: 'Remains constant at maximum bandwidth',
      },
      correctAnswer: 'A',
      explanation: 'During Slow Start, $cwnd$ increases by 1 MSS for every received ACK, doubling the congestion window every RTT until the Slow Start Threshold ($ssthresh$) is reached.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 7,
      questionText: 'What is the network address and broadcast address for an IPv4 address `192.168.10.75/26`?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Network Address: `192.168.10.64`, Broadcast Address: `192.168.10.127`',
        B: 'Network Address: `192.168.10.0`, Broadcast Address: `192.168.10.255`',
        C: 'Network Address: `192.168.10.75`, Broadcast Address: `192.168.10.128`',
        D: 'Network Address: `192.168.10.64`, Broadcast Address: `192.168.10.255`',
      },
      correctAnswer: 'A',
      explanation: 'A `/26` subnet mask has block size $256 - 192 = 64$. Subnets: $0-63, 64-127, 128-191, 192-255$. $75$ falls in $64-127$. Network address = `192.168.10.64`, Broadcast address = `192.168.10.127`.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 7,
      questionText: 'In asymmetric public-key cryptography (such as RSA algorithm), if User A wants to send an encrypted confidential message to User B that ONLY User B can decrypt, User A must encrypt the message with:',
      questionType: 'Direct MCQ',
      options: {
        A: 'User B\'s Public Key',
        B: 'User A\'s Private Key (Digital Signature)',
        C: 'User A\'s Public Key',
        D: 'User B\'s Private Key',
      },
      correctAnswer: 'A',
      explanation: 'For confidentiality, the sender encrypts using the recipient\'s public key; only the recipient possessing the corresponding private key can decrypt it.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'Which transport layer protocol provides connectionless, unreliable, best-effort datagram delivery without handshakes, retransmissions, or flow control overhead?',
      questionType: 'Direct MCQ',
      options: {
        A: 'User Datagram Protocol (UDP)',
        B: 'Transmission Control Protocol (TCP)',
        C: 'Stream Control Transmission Protocol (SCTP)',
        D: 'Internet Control Message Protocol (ICMP)',
      },
      correctAnswer: 'A',
      explanation: 'UDP is a lightweight, connectionless protocol ideal for low-latency, real-time multimedia streaming, DNS queries, and online gaming.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'The Address Resolution Protocol (ARP) operates to map a known:',
      questionType: 'Direct MCQ',
      options: {
        A: '32-bit Logical IP Address to a 48-bit Physical MAC Address',
        B: 'Physical MAC Address to a Logical IP Address (RARP / BOOTP)',
        C: 'Domain Name to an IP Address (DNS)',
        D: 'Port Number to a Process ID',
      },
      correctAnswer: 'A',
      explanation: 'ARP broadcasts on the local link to find the hardware physical MAC address corresponding to a target logical IP address.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'In CSMA/CD (Carrier Sense Multiple Access with Collision Detection) used in legacy Ethernet, the minimum frame length $L_{\\min}$ required to reliably detect collisions with bandwidth $B$ and propagation delay $T_p$ is:',
      questionType: 'Direct MCQ',
      options: {
        A: '$L_{\\min} = 2 \\times T_p \\times B$',
        B: '$L_{\\min} = T_p \\times B$',
        C: '$L_{\\min} = T_p / B$',
        D: '$L_{\\min} = 4 \\times T_p$',
      },
      correctAnswer: 'A',
      explanation: 'To ensure a transmitting node detects collisions before finishing its transmission, the transmission time $T_{tx} \\ge 2 T_p \\implies L_{\\min}/B \\ge 2 T_p \\implies L_{\\min} = 2 \\times T_p \\times B$.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 7,
      questionText: 'In Distance Vector Routing (Bellman-Ford algorithm), the vulnerability where a disconnected link causes adjacent routers to endlessly increment hop counts to infinity is known as the:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Count-to-Infinity Problem (mitigated by Split Horizon and Poison Reverse)',
        B: 'Routing Blackhole',
        C: 'Broadcast Storm',
        D: 'SYN Flood',
      },
      correctAnswer: 'A',
      explanation: 'Count-to-infinity is a classic distance-vector routing loop defect resolved via Split Horizon with Poison Reverse and hold-down timers.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 7,
      questionText: 'What standard well-known TCP port number is used by HTTPS (Hypertext Transfer Protocol Secure) running over TLS/SSL?',
      questionType: 'Direct MCQ',
      options: {
        A: '$443$',
        B: '$80$ (HTTP)',
        C: '$22$ (SSH)',
        D: '$25$ (SMTP)',
      },
      correctAnswer: 'A',
      explanation: 'HTTPS encrypted traffic listens on default TCP port 443.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'In Sliding Window protocols, in "Selective Repeat ARQ" with an $n$-bit sequence number, what is the maximum allowed sender window size $W_s$ to avoid sequence ambiguity?',
      questionType: 'Direct MCQ',
      options: {
        A: '$2^{n-1}$',
        B: '$2^n - 1$ (Go-Back-N)',
        C: '$2^n$',
        D: '$n$',
      },
      correctAnswer: 'A',
      explanation: 'In Selective Repeat ARQ, $W_s + W_r \\le 2^n$. Since $W_s = W_r$, $2 W_s \\le 2^n \\implies W_s \\le 2^{n-1}$.',
      difficulty: 'HARD',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 8: THEORY OF COMPUTATION AND COMPILERS (10 Questions: Q71 - Q80)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 8,
      questionText: 'According to the Chomsky Hierarchy of formal grammars, Context-Free Languages (Type 2) are accepted by which abstract theoretical automaton?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Pushdown Automata (PDA - using a single LIFO stack)',
        B: 'Deterministic Finite Automata (DFA - Type 3 Regular)',
        C: 'Linear Bounded Automata (LBA - Type 1 Context-Sensitive)',
        D: 'Turing Machine (Type 0 Recursively Enumerable)',
      },
      correctAnswer: 'A',
      explanation: 'Type 2 Context-Free Languages (CFLs) generated by Context-Free Grammars are recognized by Pushdown Automata equipped with a stack memory.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'Which of the following formal language problems is famously UNDECIDABLE (Turing Unrecognizable / Halting Problem)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Determining whether an arbitrary Turing Machine $M$ will halt on input string $w$ (Halting Problem $A_{TM}$)',
        B: 'Determining whether a DFA accepts an empty language ($E_{DFA}$)',
        C: 'Determining whether two DFAs are equivalent ($EQ_{DFA}$)',
        D: 'Determining whether a string $w$ is generated by a given Context-Free Grammar ($A_{CFG}$ via CYK algorithm)',
      },
      correctAnswer: 'A',
      explanation: 'Alan Turing (1936) proved that the Halting Problem is undecidable using a diagonal Cantor proof, establishing the absolute mathematical limits of algorithmic computation.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'The language $L = \\{ a^n b^n c^n \\mid n \\ge 1 \\}$ over alphabet $\\Sigma = \\{a, b, c\\}$ is:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Context-Sensitive Language (Type 1), but NOT Context-Free',
        B: 'Regular Language (Type 3)',
        C: 'Deterministic Context-Free Language',
        D: 'Non-Recursively Enumerable',
      },
      correctAnswer: 'A',
      explanation: 'Proved via the Pumping Lemma for CFLs: a single stack cannot simultaneously count three independent matching symbol blocks ($a^n b^n c^n$). It is context-sensitive and recognized by a 2-stack PDA or LBA.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'For a Deterministic Finite Automaton (DFA) and a Non-deterministic Finite Automaton (NFA), their computational language recognition power is:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Identical (Every NFA can be converted to an equivalent DFA using Powerset Construction)',
        B: 'NFA is strictly more expressive and powerful than DFA',
        C: 'DFA is strictly more powerful than NFA',
        D: 'NFAs can accept context-free languages that DFAs cannot',
      },
      correctAnswer: 'A',
      explanation: 'By the Subset / Powerset Construction algorithm (Rabin and Scott), every $n$-state NFA has an equivalent DFA with at most $2^n$ states accepting the exact same class of Regular Languages.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'In Context-Free Grammars, a grammar $G$ is declared "Ambiguous" if there exists at least one string $w \\in L(G)$ that has:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Two or more distinct leftmost derivations (or two distinct parse trees)',
        B: 'An infinite number of non-terminal symbols',
        C: 'No valid parse tree',
        D: 'Epsilon production rules',
      },
      correctAnswer: 'A',
      explanation: 'Grammar ambiguity means a string possesses multiple distinct syntax trees, causing semantic compilation ambiguity (e.g. dangling-else problem).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'In compiler design, what is an LR(1) parser?',
      questionType: 'Direct MCQ',
      options: {
        A: 'A Bottom-Up parser that reads input from Left-to-right, constructs a Rightmost derivation in reverse, and uses 1 token of lookahead',
        B: 'A Top-Down parser that uses Leftmost derivation with 1 lookahead (LL(1))',
        C: 'A lexical scanner based on regular expressions',
        D: 'A syntax-directed translation interpreter',
      },
      correctAnswer: 'A',
      explanation: 'LR(k): L = Left-to-right scan; R = Rightmost derivation in reverse (Shift-Reduce parsing); k = lookahead symbol count.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'The Pumping Lemma for Regular Languages is primarily used to:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Prove that a given formal language is NOT regular by contradiction',
        B: 'Prove that a language is regular',
        C: 'Minimize the number of states in a DFA',
        D: 'Generate regular expression code',
      },
      correctAnswer: 'A',
      explanation: 'The Pumping Lemma is a necessary property of all regular languages; if a language violates the pumping condition for any string longer than pumping length $p$, it is proven non-regular.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'In bottom-up shift-reduce parsing, what is a "Shift-Reduce Conflict"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'The parser cannot determine whether to shift the next input symbol onto the stack or reduce the current top-of-stack symbols using a grammar production rule',
        B: 'The parser cannot decide between two reduce actions (Reduce-Reduce)',
        C: 'The stack overflows available memory',
        D: 'The lexical scanner generates invalid character tokens',
      },
      correctAnswer: 'A',
      explanation: 'A shift-reduce conflict occurs in an LR parser state where both a shift action and a reduce action are simultaneously valid for a given lookahead token.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'A Context-Free Grammar is in Chomsky Normal Form (CNF) if all its production rules are of the form:',
      questionType: 'Direct MCQ',
      options: {
        A: '$A \\to BC$ OR $A \\to a$ (where $A, B, C$ are non-terminals and $a$ is a terminal)',
        B: '$A \\to a B$ (Greibach Normal Form)',
        C: '$A \\to \\alpha$ where $\\alpha$ is any combination of symbols',
        D: '$A \\to B$',
      },
      correctAnswer: 'A',
      explanation: 'In CNF, every production rule yields either exactly two non-terminals ($A \\to BC$) or exactly one terminal symbol ($A \\to a$), enabling $O(n^3)$ CYK parsing.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'Which class of languages is closed under Union, Concatenation, Kleene Star, Intersection, AND Complementation?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Regular Languages AND Recursive (Decidable) Languages',
        B: 'Context-Free Languages (not closed under intersection or complement)',
        C: 'Recursively Enumerable Languages (not closed under complement)',
        D: 'Deterministic Context-Free Languages (not closed under union)',
      },
      correctAnswer: 'A',
      explanation: 'Regular languages form a Boolean algebra closed under union, intersection, complement, concatenation, and star. Context-free languages fail closure under intersection and complementation.',
      difficulty: 'HARD',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 9 & 10: DATA SCIENCE, BIG DATA & ARTIFICIAL INTELLIGENCE (20 Questions: Q81 - Q100)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 9,
      questionText: 'In supervised machine learning, what does the "Bias-Variance Tradeoff" describe?',
      questionType: 'Direct MCQ',
      options: {
        A: 'High bias causes underfitting (oversimplified model missing true patterns); High variance causes overfitting (model captures noise in training data and fails on test data)',
        B: 'Bias measures training time; Variance measures memory usage',
        C: 'Bias applies to classification; Variance applies only to regression',
        D: 'High variance always guarantees zero test error',
      },
      correctAnswer: 'A',
      explanation: 'Total generalization error = $\\text{Bias}^2 + \\text{Variance} + \\text{Irreducible Error}$. Balancing model complexity minimizes test error.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'In Apache Hadoop ecosystem, which distributed file system provides high-throughput streaming access to large datasets across commodity clusters using 128MB block replication?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Hadoop Distributed File System (HDFS)',
        B: 'Network File System (NFS)',
        C: 'FAT32',
        D: 'Ext4 File System',
      },
      correctAnswer: 'A',
      explanation: 'HDFS uses a master NameNode and worker DataNodes with default $3\\times$ replication for scalable fault-tolerant distributed storage.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'In dimensionality reduction and unsupervised feature extraction, Principal Component Analysis (PCA) identifies new orthogonal axes (principal components) that maximize:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The variance (dispersion) of the projected data points',
        B: 'The classification cross-entropy loss',
        C: 'The correlation between distinct features',
        D: 'The number of categorical cluster labels',
      },
      correctAnswer: 'A',
      explanation: 'PCA computes the eigenvectors of the data covariance matrix; the principal components corresponding to the largest eigenvalues capture maximal variance while removing multicollinearity.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'In Apache Spark distributed data processing framework, what is the core fault-tolerant, immutable distributed collection of objects partitioned across cluster nodes called?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Resilient Distributed Dataset (RDD)',
        B: 'HDFS Block Map',
        C: 'Shared Memory Queue',
        D: 'MapReduce Split',
      },
      correctAnswer: 'A',
      explanation: 'RDD (Resilient Distributed Dataset) is Spark\'s fundamental in-memory abstraction, supporting lazy transformations (map, filter) and actions (count, collect) with automatic lineage-based recovery.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'In classification evaluation metrics, the "F1-Score" is mathematically defined as the Harmonic Mean of:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Precision and Recall (Sensitivity)',
        B: 'Accuracy and Specificity',
        C: 'True Positive Rate and False Positive Rate',
        D: 'Mean Squared Error and $R^2$',
      },
      correctAnswer: 'A',
      explanation: '$F_1 = 2 \\times \\frac{\\text{Precision} \\times \\text{Recall}}{\\text{Precision} + \\text{Recall}}$. The harmonic mean penalizes extreme disparities between precision and recall.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'In MapReduce distributed processing paradigm (Dean and Ghemawat, 2004), what does the "Shuffle and Sort" phase perform between Map and Reduce phases?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Groups and sorts all intermediate key-value pairs generated by Map workers by key, routing all values associated with a given key to the same Reducer',
        B: 'Encrypts disk data with RSA keys',
        C: 'Deletes all intermediate files from HDFS',
        D: 'Converts CSV files into JSON format',
      },
      correctAnswer: 'A',
      explanation: 'Shuffle and Sort collects intermediate `(k, v)` pairs from all map nodes, partitions them by hash of key, and sorts them before feeding them to reducers.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'In clustering and unsupervised learning, the $k$-Means algorithm minimizes which objective cost function?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Within-Cluster Sum of Squares (WCSS / Inertia): $\\sum_{i=1}^k \\sum_{x \\in S_i} \\| x - \\mu_i \\|^2$',
        B: 'Cross-entropy loss function',
        C: 'Hinge loss function',
        D: 'Kullback-Leibler divergence',
      },
      correctAnswer: 'A',
      explanation: 'k-Means partitions $n$ observations into $k$ clusters by iteratively assigning points to nearest centroid $\\mu_i$ and recomputing cluster centroids to minimize WCSS.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'In Big Data analytics and streaming data, what is Apache Kafka?',
      questionType: 'Direct MCQ',
      options: {
        A: 'A distributed event streaming platform / message broker utilizing partitioned, fault-tolerant commit logs',
        B: 'A relational SQL query optimizer',
        C: 'A graphic design vector rendering engine',
        D: 'A web browser layout renderer',
      },
      correctAnswer: 'A',
      explanation: 'Apache Kafka provides high-throughput, low-latency, fault-tolerant pub-sub messaging and stream processing using distributed partition logs.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'In decision tree algorithms (such as ID3 and C4.5), the metric used by ID3 to select the best splitting attribute at each node is:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Information Gain based on Shannon Entropy ($H(S) = -\\sum p_i \\log_2 p_i$)',
        B: 'Gini Impurity (used in CART)',
        C: 'Mean Absolute Error',
        D: 'R-squared coefficient',
      },
      correctAnswer: 'A',
      explanation: 'ID3 calculates Information Gain $Gain(S, A) = Entropy(S) - \\sum \\frac{|S_v|}{|S|} Entropy(S_v)$ to choose the attribute maximizing entropy reduction.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'In Support Vector Machines (SVM), what is the "Kernel Trick"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Implicitly mapping input data points into a higher-dimensional feature space using an inner product kernel function (e.g. RBF / Polynomial) to find a linear separating hyperplane without computing explicit coordinate transformations',
        B: 'Reducing matrix rank using SVD',
        C: 'Accelerating GPU clock speeds',
        D: 'Pruning decision tree branches',
      },
      correctAnswer: 'A',
      explanation: 'The Kernel Trick computes $K(x_i, x_j) = \\langle \\phi(x_i), \\phi(x_j) \\rangle$ in high dimensions directly in input space, enabling non-linear maximum margin classification.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'In Artificial Intelligence search algorithms, the $A^*$ search algorithm is guaranteed to find the optimal shortest path (Admissible) if the heuristic function $h(n)$:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Never overestimates the true actual cost to reach the goal state ($h(n) \\le h^*(n)$ for all nodes $n$)',
        B: 'Always overestimates the true cost by at least $50\\%$',
        C: 'Equals zero for all nodes (Breadth First Search)',
        D: 'Is strictly negative for non-goal states',
      },
      correctAnswer: 'A',
      explanation: '$A^*$ evaluates $f(n) = g(n) + h(n)$. If $h(n)$ is admissible (never overestimates), tree search $A^*$ is mathematically guaranteed to be optimal.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'In game theory and adversarial search, what algorithm prunes branches in the game tree that cannot possibly influence the final decision of the Minimax root node?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Alpha-Beta Pruning (maintains $\\alpha$ lower bound and $\\beta$ upper bound)',
        B: 'Simulated Annealing',
        C: 'Hill Climbing with Random Restarts',
        D: 'Genetic Crossover',
      },
      correctAnswer: 'A',
      explanation: 'Alpha-Beta pruning cuts off subtrees when a node evaluation falls outside $[\alpha, \beta]$ (where $\alpha$ is best max value and $\beta$ is best min value), doubling search depth.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'In deep neural networks, the "Vanishing Gradient Problem" during backpropagation training of deep networks with Sigmoid activation functions occurs because:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The derivative of the Sigmoid function $\\sigma\'(x) \\le 0.25$, so multiplying many small gradients across layers causes backpropagated error gradients to exponentially shrink towards zero',
        B: 'The weights become infinitely large causing arithmetic overflow',
        C: 'The learning rate is automatically multiplied by 10 at every epoch',
        D: 'The training dataset has too many duplicate rows',
      },
      correctAnswer: 'A',
      explanation: 'Chain rule multiplication of small derivatives ($<0.25$) across deep layers decays gradients exponentially, preventing early layers from updating weights. Rectified Linear Unit (ReLU) resolves this.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'In Natural Language Processing and Modern AI architectures, the "Transformer" architecture (Vaswani et al., 2017 - "Attention Is All You Need") replaced sequential RNNs by utilizing:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Multi-Head Self-Attention mechanisms and positional encodings allowing fully parallel sequence computation',
        B: 'Markov Decision Process tables',
        C: 'Expert Systems Rule Engines in PROLOG',
        D: 'Manual phonetic dictionary lookups',
      },
      correctAnswer: 'A',
      explanation: 'Transformers compute self-attention matrix ($Q, K, V$) across all tokens simultaneously ($O(1)$ path length), eliminating sequential bottleneck of LSTMs/RNNs and powering LLMs.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'In Reinforcement Learning, what equation expresses the optimal state-value function $V^*(s)$ as the immediate reward plus the discounted expected value of the next optimal state?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Bellman Optimality Equation: $V^*(s) = \\max_a \\sum_{s\', r} p(s\', r \\mid s, a) [r + \\gamma V^*(s\')]$',
        B: 'Bayes Theorem Probability Equation',
        C: 'Euler-Lagrange Equation',
        D: 'Navier-Stokes Equation',
      },
      correctAnswer: 'A',
      explanation: 'The Bellman Equation breaks down value functions into immediate reward $R_t$ plus discounted future value $\\gamma V(S_{t+1})$, forming the foundation of Q-Learning and Dynamic Programming in RL.',
      difficulty: 'HARD',
    },
    {
      unitNumber: 10,
      questionText: 'In Fuzzy Logic systems, what defuzzification method computes the center of gravity of the aggregated fuzzy output membership area?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Centroid Method (Center of Gravity / COG: $z^* = \\frac{\\int z \\mu_C(z) dz}{\\int \\mu_C(z) dz}$)',
        B: 'First of Maxima (FOM)',
        C: 'Mean of Maxima (MOM)',
        D: 'Boolean Rounding',
      },
      correctAnswer: 'A',
      explanation: 'Centroid defuzzification calculates the geometric center of gravity of the combined fuzzy output distribution to generate a crisp scalar value.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'In Genetic Algorithms (GAs), what genetic operator maintains genetic diversity in the candidate solution chromosome population to prevent premature convergence to local optima?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Mutation Operator (random bit-flipping with low probability $p_m$)',
        B: 'Crossover Operator (recombination)',
        C: 'Roulette Wheel Selection (fitness proportionate)',
        D: 'Tournament Selection',
      },
      correctAnswer: 'A',
      explanation: 'Mutation introduces novel alleles into the population, preventing search stagnation and exploring uncharted regions of the fitness landscape.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'In Artificial Neural Networks, what is the standard Backpropagation learning algorithm based on?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Gradient Descent optimization utilizing the Calculus Chain Rule to propagate errors backward from output to input layers',
        B: 'Brute force random search',
        C: 'Linear programming simplex pivots',
        D: 'Depth-first tree traversal',
      },
      correctAnswer: 'A',
      explanation: 'Backpropagation (Rumelhart, Hinton, Williams, 1986) computes partial derivatives $\\frac{\\partial E}{\\partial w_{ij}}$ using the chain rule to update weights via gradient descent.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'In Convolutional Neural Networks (CNNs), what is the function of the "Pooling Layer" (such as Max-Pooling)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'To downsample spatial dimensions (height and width) of feature maps, reducing parameters and computation while providing translational invariance',
        B: 'To compute softmax classification probabilities',
        C: 'To initialize random weights',
        D: 'To normalize mini-batch gradients',
      },
      correctAnswer: 'A',
      explanation: 'Max-pooling extracts the maximum value in local sliding windows (e.g. $2 \\times 2$ with stride 2), reducing spatial dimensionality by $75\\%$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'In knowledge representation and First-Order Predicate Logic (FOL), what process resolves variables when matching two atomic sentences by finding a substitution $\\theta$ that makes them identical?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Unification Algorithm ($UNIFY(p, q) = \\theta$)',
        B: 'Skolemization (eliminating existential quantifiers)',
        C: 'Modus Ponens inference',
        D: 'Forward Chaining',
      },
      correctAnswer: 'A',
      explanation: 'Unification finds the Most General Unifier (MGU) substitution mapping variables to terms so two FOL expressions become syntactically identical for resolution refutation.',
      difficulty: 'HARD',
    },
  ];

  return {
    subjectCode: '87',
    subjectSlug: 'computer-science-and-applications',
    mockNumber: 1,
    title: 'Computer Science & Applications — Mock Test 1: Full Syllabus Simulation (100 Qs)',
    description: 'Authentic 100-question UGC NET Computer Science & Applications simulation covering Discrete Math, Architecture, Programming, DBMS, OS, Software Engineering, Networks, TOC, Data Science, and AI across all 10 units.',
    accessTier: 'FREE',
    isFreeBenchmark: true,
    questions,
  };
}
