import { MockTestDefinition, RawMockQuestion } from '../common';

export function getEconomicsMockTest(): MockTestDefinition {
  const questions: RawMockQuestion[] = [
    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 1: MICROECONOMIC ANALYSIS (10 Questions: Q1 - Q10)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 1,
      questionText: 'Under the Revealed Preference Theory of consumer behaviour formulated by Paul Samuelson, which axiom asserts that if bundle A is directly revealed preferred to bundle B, bundle B can never be revealed preferred to bundle A when A is affordable?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Weak Axiom of Revealed Preference (WARP)',
        B: 'Strong Axiom of Revealed Preference (SARP - transitivity)',
        C: 'Generalized Axiom of Revealed Preference (GARP)',
        D: 'Non-Satiation Axiom',
      },
      correctAnswer: 'A',
      explanation: 'WARP states that if consumer chooses bundle $x$ over bundle $y$ when both were affordable, they will never choose $y$ over $x$ when $x$ is affordable at new price vectors.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In consumer theory, the Slutsky Equation decomposes the total price effect of a price change on demand into:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Substitution Effect (always negative) and Income Effect',
        B: 'Veblen Effect and Bandwagon Effect',
        C: 'Marginal Rate of Substitution and Marginal Cost',
        D: 'Consumer Surplus and Producer Surplus',
      },
      correctAnswer: 'A',
      explanation: '$\\frac{\\partial x_i}{\\partial p_j} = \\left(\\frac{\\partial x_i}{\\partial p_j}\\right)_{u=\\text{const}} - x_j \\frac{\\partial x_i}{\\partial m}$. The substitution effect reflects change in relative prices holding real purchasing power constant.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'For a Cobb-Douglas production function $Q = A K^\\alpha L^\\beta$, the elasticity of substitution ($\\sigma$) between capital ($K$) and labour ($L$) is always identically equal to:',
      questionType: 'Direct MCQ',
      options: {
        A: '$1$',
        B: '$\\alpha + \\beta$',
        C: '$0$ (Leontief fixed proportions)',
        D: '$\\infty$ (Linear perfect substitutes)',
      },
      correctAnswer: 'A',
      explanation: 'For all Cobb-Douglas production functions, the elasticity of factor substitution $\\sigma = \\frac{\\% \\Delta(K/L)}{\\% \\Delta(MRTS)} = 1$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In general equilibrium and welfare economics, the "First Fundamental Theorem of Welfare Economics" states that:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Any competitive market equilibrium is Pareto optimal (efficient), provided consumers are locally non-satiated and there are no externalities or asymmetric information',
        B: 'Any Pareto efficient allocation can be supported as a competitive equilibrium through lump-sum redistribution (Second Theorem)',
        C: 'Monopoly pricing maximizes social welfare',
        D: 'Income inequality is eliminated in competitive equilibrium',
      },
      correctAnswer: 'A',
      explanation: 'The First Welfare Theorem formalizes Adam Smith\'s "invisible hand": under complete competitive markets and perfect information, market clearing prices yield a Pareto-efficient resource allocation.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In oligopoly market models, the "Cournot Duopoly Model" assumes that each competing firm chooses its optimal output level assuming that the rival firm\'s:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Output quantity remains constant',
        B: 'Price remains constant (Bertrand Model)',
        C: 'Reaction curve is non-linear',
        D: 'Profit is zero',
      },
      correctAnswer: 'A',
      explanation: 'Cournot duopoly assumes simultaneous quantity-setting where each firm treats the rival\'s output volume as fixed, determining equilibrium at the intersection of their Reaction Functions.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Which price discrimination type (Pigou classification) occurs when a monopolist charges each consumer their exact maximum willingness-to-pay (reservation price), completely capturing all consumer surplus?',
      questionType: 'Direct MCQ',
      options: {
        A: 'First-Degree (Perfect) Price Discrimination',
        B: 'Second-Degree (Menu / Quantity discount) Discrimination',
        C: 'Third-Degree (Market segmentation by elasticity) Discrimination',
        D: 'Peak-Load Pricing',
      },
      correctAnswer: 'A',
      explanation: 'First-degree price discrimination extracts the entire consumer surplus triangle, converting all surplus into monopoly super-normal profit with zero deadweight loss.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In game theory, a strategy profile is in "Nash Equilibrium" if:',
      questionType: 'Direct MCQ',
      options: {
        A: 'No player has an incentive to unilaterally deviate from their chosen strategy given the strategies chosen by all other players',
        B: 'Both players maximize collective joint payoffs (Pareto optimal)',
        C: 'One player completely eliminates the other player',
        D: 'All players choose dominated strategies',
      },
      correctAnswer: 'A',
      explanation: 'In a Nash Equilibrium (John Nash, 1950), each player\'s strategy is a best response to the strategies of all other players in the strategic-form game.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'A good for which the income effect is negative and strictly outweighs the substitution effect, resulting in an upward-sloping demand curve, is termed a:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Giffen Good',
        B: 'Veblen Conspicuous Good',
        C: 'Public Good',
        D: 'Normal Good',
      },
      correctAnswer: 'A',
      explanation: 'A Giffen good is an extreme inferior good where the negative income effect dominates the substitution effect, violating the Law of Demand ($dQ/dP > 0$).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In environmental economics and property rights, the "Coase Theorem" demonstrates that in the presence of externalities, private bargaining will lead to a Pareto efficient outcome regardless of initial property rights allocation, provided that:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Transaction costs are zero (or negligible) and property rights are well-defined',
        B: 'The government imposes Pigouvian emission taxes on polluters',
        C: 'Output markets are monopolistic',
        D: 'There are millions of affected parties',
      },
      correctAnswer: 'A',
      explanation: 'Ronald Coase (1960) proved that costless negotiation between private parties internalizes externalities efficiently without requiring government regulation.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In Arrow\'s Impossibility Theorem (Kenneth Arrow, 1951), it is mathematically proven that no collective social welfare voting system can simultaneously satisfy which set of reasonable democratic criteria?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Unrestricted Domain (U), Pareto Efficiency (P), Independence of Irrelevant Alternatives (IIA), and Non-Dictatorship (D)',
        B: 'Proportionality, Equality, Fraternity, and Liberty',
        C: 'Majority rule, Monarchy, Oligarchy, and Anarchy',
        D: 'Zero taxation, Free trade, Balanced budget, and Inflation control',
      },
      correctAnswer: 'A',
      explanation: 'Arrow\'s Theorem proves that when voters rank three or more distinct alternatives, no voting rule can convert individual preference rankings into a coherent social preference order without violating Non-Dictatorship or IIA.',
      difficulty: 'HARD',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 2: MACROECONOMIC ANALYSIS (10 Questions: Q11 - Q20)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 2,
      questionText: 'In John Maynard Keynes\' "General Theory of Employment, Interest and Money" (1936), the "Liquidity Preference Theory" identifies which three motives for holding money balances?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Transactions motive, Precautionary motive, and Speculative motive',
        B: 'Investment motive, Saving motive, and Consumption motive',
        C: 'Export motive, Import motive, and Arbitrage motive',
        D: 'Inflation motive, Deflation motive, and Stagnation motive',
      },
      correctAnswer: 'A',
      explanation: 'Keynes categorized money demand $M_d = L_1(Y) + L_2(r)$, where $L_1$ covers transaction/precautionary needs dependent on income ($Y$), and $L_2$ covers speculative demand inversely related to the interest rate ($r$).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In the IS-LM Model (Hicks-Hansen Synthesis), what is the "Liquidity Trap"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'A horizontal segment of the LM curve at critically low interest rates where speculative demand for money becomes infinitely elastic, rendering monetary expansion ineffective in stimulating output',
        B: 'A vertical IS curve during hyperinflation',
        C: 'A banking crisis where all credit dries up',
        D: 'A stock market crash due to foreign exchange depreciation',
      },
      correctAnswer: 'A',
      explanation: 'In a liquidity trap, nominal interest rates approach zero; people hold all additional money as idle cash balances rather than bonds, making monetary policy powerless and fiscal stimulus paramount.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'Milton Friedman\'s "Permanent Income Hypothesis" (PIH) posits that consumer consumption expenditure is determined primarily by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Permanent long-term expected lifetime income ($Y_p$), rather than current transitory windfall income ($Y_t$)',
        B: 'Current absolute disposable income (Keynesian Absolute Income Hypothesis)',
        C: 'Relative income compared to neighbours (Duesenberry Relative Income Hypothesis)',
        D: 'Past peak consumption standards exclusively',
      },
      correctAnswer: 'A',
      explanation: 'Friedman showed that households smooth consumption based on perceived permanent wealth and lifetime earnings, with the marginal propensity to consume out of transitory income close to zero.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'The "Original Phillips Curve" (A.W. Phillips, 1958) demonstrated an empirical inverse relationship between:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Rate of unemployment and the rate of change of money wage rates (inflation)',
        B: 'Interest rate and money supply',
        C: 'Economic growth and income inequality (Kuznets Curve)',
        D: 'Tax rate and total tax revenue (Laffer Curve)',
      },
      correctAnswer: 'A',
      explanation: 'Phillips found a non-linear inverse relationship in UK data: lower unemployment was associated with higher wage inflation, suggesting a short-run policy trade-off.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In Monetarist economics (Milton Friedman and Edmund Phelps), the "Long-Run Phillips Curve" (LRPC) is:',
      questionType: 'Direct MCQ',
      options: {
        A: 'A vertical straight line at the Natural Rate of Unemployment (NAIRU)',
        B: 'Downward sloping showing a permanent trade-off',
        C: 'Horizontal at zero inflation',
        D: 'Upward sloping',
      },
      correctAnswer: 'A',
      explanation: 'Under adaptive expectations, workers adjust inflation expectations in the long run. Unemployment returns to its natural rate (NAIRU), making the LRPC completely vertical.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In the Solow-Swan Neoclassical Growth Model, steady-state long-run per capita income growth is determined exclusively by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Exogenous rate of technological progress ($g$)',
        B: 'The national saving rate ($s$ - affects only output level, not long-run growth rate)',
        C: 'The population growth rate ($n$)',
        D: 'The depreciation rate of capital ($\\delta$)',
      },
      correctAnswer: 'A',
      explanation: 'In the Solow model, diminishing returns to capital imply that in the steady state, output per worker grows at the exogenous rate of labor-augmenting technological progress ($g$).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'The "Mundell-Fleming Model" (IS-LM-BP model for an open economy) demonstrates that under PERFECT CAPITAL MOBILITY and a FLOATING EXCHANGE RATE regime:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Monetary policy is highly effective in altering output, while Fiscal policy is completely ineffective due to exchange rate appreciation crowding out net exports',
        B: 'Fiscal policy is highly effective while monetary policy is powerless',
        C: 'Both monetary and fiscal policies are completely ineffective',
        D: 'Exchange rates remain permanently fixed',
      },
      correctAnswer: 'A',
      explanation: 'Under floating rates with mobile capital, fiscal expansion raises interest rates, attracting capital inflows and appreciating the currency, which crowds out net exports ($NX$) until output returns to original equilibrium.',
      difficulty: 'HARD',
    },
    {
      unitNumber: 2,
      questionText: 'The "Rational Expectations Hypothesis" (associated with Robert Lucas, Thomas Sargent, and Neil Wallace in New Classical Macroeconomics) implies the "Policy Ineffectiveness Proposition", which asserts that:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Systematic, anticipated monetary policy cannot affect real output or employment even in the short run; only unanticipated policy shocks have temporary real effects',
        B: 'Central banks can permanently eliminate unemployment using predictable money supply growth',
        C: 'Fiscal deficits have no impact on government bond yields',
        D: 'Economic agents always form expectations by extrapolating past trends (adaptive)',
      },
      correctAnswer: 'A',
      explanation: 'Under Lucas\'s rational expectations, rational forward-looking agents incorporate announced policy rules immediately into wage/price contracts, neutralizing anticipated monetary policy.',
      difficulty: 'HARD',
    },
    {
      unitNumber: 2,
      questionText: 'In national income accounting, if Gross Domestic Product at Market Prices ($GDP_{MP}$) is ₹10,000 Crores, Net Factor Income from Abroad ($NFIA$) is ₹-200 Crores, Depreciation is ₹800 Crores, and Net Indirect Taxes ($NIT$) are ₹1,000 Crores, what is Net National Product at Factor Cost ($NNP_{FC}$ / National Income)?',
      questionType: 'Direct MCQ',
      options: {
        A: '₹8,000 Crores',
        B: '₹8,200 Crores',
        C: '₹8,400 Crores',
        D: '₹9,000 Crores',
      },
      correctAnswer: 'A',
      explanation: '$NNP_{FC} = GDP_{MP} + NFIA - \\text{Depreciation} - NIT = 10000 + (-200) - 800 - 1000 = 8000\\text{ Crores}$.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'In business cycle theory, the "Real Business Cycle" (RBC) school (Kydland and Prescott, 1982) explains macroeconomic fluctuations as equilibrium responses to:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Real exogenous technological productivity shocks and supply-side disturbances in competitive markets',
        B: 'Unstable shifts in Keynesian "Animal Spirits" and aggregate demand',
        C: 'Erratic money supply printing by central banks',
        D: 'Sticky nominal prices and wage contracts',
      },
      correctAnswer: 'A',
      explanation: 'RBC theory models fluctuations as optimal Pareto-efficient responses of rational agents adjusting labor and leisure in response to stochastic total factor productivity (TFP) shocks.',
      difficulty: 'MEDIUM',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 3: STATISTICS AND ECONOMETRICS (10 Questions: Q21 - Q30)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 3,
      questionText: 'In the Classical Linear Regression Model (Ordinary Least Squares / OLS), the Gauss-Markov Theorem establishes that the OLS estimators are BLUE, which stands for:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Best Linear Unbiased Estimator (having minimum variance among all linear unbiased estimators)',
        B: 'Biased Linear Universal Estimator',
        C: 'Basic Logarithmic Unitary Estimator',
        D: 'Bayesian Linear Unconstrained Estimator',
      },
      correctAnswer: 'A',
      explanation: 'Under assumptions of linearity, strict exogeneity $E(u|X)=0$, homoscedasticity, and no autocorrelation, OLS estimators have the smallest sampling variance among all linear unbiased estimators.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In econometric regression analysis, the violation of the classical assumption of constant error variance ($Var(u_i \\mid X_i) = \\sigma^2$), where error variance varies across observations ($Var(u_i) = \\sigma_i^2$), is known as:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Heteroscedasticity',
        B: 'Multicollinearity',
        C: 'Autocorrelation / Serial Correlation',
        D: 'Endogeneity',
      },
      correctAnswer: 'A',
      explanation: 'Heteroscedasticity (detected via White, Breusch-Pagan, or Goldfeld-Quandt tests) leaves OLS estimators unbiased but inefficient, invalidating standard hypothesis t-tests and F-tests.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'Which statistical test statistic is standardly used to detect first-order autoregressive serial correlation ($AR(1)$) in the residuals of an OLS regression time series model?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Durbin-Watson Test ($d \\approx 2(1 - \\hat{\\rho})$)',
        B: 'Dickey-Fuller Unit Root Test',
        C: 'Chow Test for structural break',
        D: 'Granger Causality Test',
      },
      correctAnswer: 'A',
      explanation: 'The Durbin-Watson $d$ statistic ranges between 0 and 4: $d \\approx 2$ indicates no serial correlation, $d < 2$ suggests positive autocorrelation, and $d > 2$ suggests negative autocorrelation.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In multiple linear regression, when two or more independent explanatory variables are highly linearly correlated, making it difficult to isolate their individual impacts, the econometric problem is:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Multicollinearity (measured by high Variance Inflation Factor / VIF $> 10$)',
        B: 'Simultaneous Equation Bias',
        C: 'Specification Error',
        D: 'Omitted Variable Bias',
      },
      correctAnswer: 'A',
      explanation: 'Multicollinearity inflates standard errors of OLS estimators, resulting in high $R^2$ with statistically insignificant individual $t$-ratios.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In time-series econometrics, a non-stationary time series whose first difference is stationary is said to be Integrated of Order:',
      questionType: 'Direct MCQ',
      options: {
        A: '$I(1)$ (Integrated of order 1)',
        B: '$I(0)$ (Stationary in levels)',
        C: '$I(2)$',
        D: '$I(\\infty)$',
      },
      correctAnswer: 'A',
      explanation: 'A series $Y_t$ is $I(1)$ if differencing it once ($\\Delta Y_t = Y_t - Y_{t-1}$) yields a mean-reverting stationary series with constant mean and finite autocovariance.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'In the simultaneous equations framework, what is the "Order Condition" for the identification of a single structural equation in a system of $M$ endogenous equations?',
      questionType: 'Direct MCQ',
      options: {
        A: '$K - k \\ge m - 1$ (The number of excluded predetermined variables must be at least the number of included endogenous variables minus 1)',
        B: '$K + k = M$',
        C: '$m = M$',
        D: 'Determinant of the structural matrix must be zero',
      },
      correctAnswer: 'A',
      explanation: 'The Order Condition is a necessary condition for identification: $K - k \\ge m - 1$ (if equal: exactly identified; if greater: over-identified, estimated via Two-Stage Least Squares / 2SLS).',
      difficulty: 'HARD',
    },
    {
      unitNumber: 3,
      questionText: 'When an independent explanatory variable is correlated with the regression error term ($Cov(X, u) \\ne 0$), resulting in biased and inconsistent OLS estimators (Endogeneity), the standard econometric remedy is:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Instrumental Variable (IV) Estimation / Two-Stage Least Squares (2SLS)',
        B: 'Weighted Least Squares (WLS)',
        C: 'Logarithmic transformation',
        D: 'Deleting the intercept term',
      },
      correctAnswer: 'A',
      explanation: 'An instrumental variable $Z$ that is correlated with endogenous regressor $X$ (instrument relevance) and uncorrelated with error $u$ (instrument exogeneity) provides consistent parameter estimates.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'In testing for unit roots in time series data to avoid spurious regressions, which augmented econometric test is standardly employed?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Augmented Dickey-Fuller (ADF) Test',
        B: 'Student\'s t-test on levels',
        C: 'Kruskal-Wallis Test',
        D: 'Mann-Whitney U Test',
      },
      correctAnswer: 'A',
      explanation: 'The ADF test tests the null hypothesis $H_0: \\gamma = 0$ (unit root / non-stationarity) against $H_1: \\gamma < 0$ using non-standard Dickey-Fuller tau distributions.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'In binary choice models where the dependent variable is qualitative ($Y_i \\in \\{0, 1\\}$), the model that uses the cumulative standard logistic distribution function is called the:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Logit Model ($P_i = \\frac{1}{1 + e^{-Z_i}}$)',
        B: 'Probit Model (Standard Normal CDF)',
        C: 'Linear Probability Model (LPM - suffers from non-normality and probabilities outside $[0,1]$)',
        D: 'Tobit Model (Censored regression)',
      },
      correctAnswer: 'A',
      explanation: 'The Logit model guarantees predicted probabilities remain strictly bounded between 0 and 1 using the odds-ratio and logistic link function estimated via Maximum Likelihood.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In panel data econometrics, the "Hausman Specification Test" is standardly used to decide between:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Fixed Effects Model (FEM) versus Random Effects Model (REM)',
        B: 'OLS versus Generalized Least Squares',
        C: 'Logit versus Probit',
        D: 'Autocorrelation versus Multicollinearity',
      },
      correctAnswer: 'A',
      explanation: 'The Hausman test tests whether unobserved individual-specific effects are correlated with regressors. If $p < 0.05$, REM is inconsistent and Fixed Effects (FEM) must be preferred.',
      difficulty: 'MEDIUM',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 4 & 5: INTERNATIONAL & PUBLIC ECONOMICS (20 Questions: Q31 - Q50)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 4,
      questionText: 'In classical international trade theory, David Ricardo demonstrated the Law of Comparative Advantage using which classic two-country, two-commodity model?',
      questionType: 'Direct MCQ',
      options: {
        A: 'England producing Cloth and Portugal producing Wine based on comparative labour productivity differences',
        B: 'US producing Wheat and UK producing Iron',
        C: 'India producing Spices and China producing Silk',
        D: 'Germany producing Automobiles and France producing Cheese',
      },
      correctAnswer: 'A',
      explanation: 'Ricardo showed that trade is mutually beneficial even if Portugal has an absolute advantage in both goods, as long as England specializes in the good where its comparative opportunity cost is lowest.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'The Heckscher-Ohlin (H-O) Factor Endowment Theory of trade predicts that a country will export the commodity that intensively utilizes its:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Abundant and cheap factor of production, and import the commodity that intensively utilizes its scarce factor',
        B: 'Most expensive technological component',
        C: 'Heaviest raw mineral material',
        D: 'Locally subsidized domestic monopolies',
      },
      correctAnswer: 'A',
      explanation: 'The $2 \\times 2 \\times 2$ H-O theorem states that a capital-abundant country exports capital-intensive goods and imports labour-intensive goods, while labour-abundant countries do the reverse.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'Wassily Leontief\'s empirical test of the Heckscher-Ohlin theorem on US trade data (1953) produced the famous "Leontief Paradox", which revealed that:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The capital-abundant United States was surprisingly exporting labour-intensive commodities and importing capital-intensive commodities',
        B: 'Trade volumes between developed countries had fallen to zero',
        C: 'Tariffs increased global welfare',
        D: 'Labour productivity in developing countries exceeded the US',
      },
      correctAnswer: 'A',
      explanation: 'Using input-output tables, Leontief found that US exports were more labour-intensive than US import-competing products, directly contradicting H-O theory predictions (resolved by factoring in human capital).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'The "Stolper-Samuelson Theorem" demonstrates that the imposition of an import tariff on an import-competing good will unambiguously:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Increase the real return/reward of the factor used intensively in the production of that import-competing good, and decrease the real return of the other factor',
        B: 'Equally raise the incomes of all domestic workers and capitalists',
        C: 'Reduce government tariff revenue to zero',
        D: 'Eliminate international terms of trade',
      },
      correctAnswer: 'A',
      explanation: 'Stolper-Samuelson links commodity prices directly to factor returns: a tariff raising the relative price of labour-intensive goods increases real wages while lowering the real return on capital.',
      difficulty: 'HARD',
    },
    {
      unitNumber: 4,
      questionText: 'The "Marshall-Lerner Condition" states that a currency devaluation will successfully improve a country\'s trade balance (current account) if and only if:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The sum of the price elasticities of demand for exports and imports is strictly greater than 1 ($|e_x + e_m| > 1$)',
        B: 'The price elasticity of exports is equal to zero',
        C: 'The country operates a budget surplus',
        D: 'Import tariffs are set at 100%',
      },
      correctAnswer: 'A',
      explanation: 'If $|e_x + e_m| > 1$, the volume effect of increased export quantities and reduced import volumes outweighs the adverse price effect of costlier imports, curing trade deficits (following the J-Curve lag).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'In public economics, a pure "Public Good" is defined by which two essential economic characteristics?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Non-Rivalry in consumption and Non-Excludability in access (e.g. National Defence, Streetlighting)',
        B: 'Rivalry and Excludability (Private Goods)',
        C: 'High marginal cost and profit maximization',
        D: 'Direct state subsidization with private rationing',
      },
      correctAnswer: 'A',
      explanation: 'Pure public goods cannot exclude non-payers (Free-Rider Problem) and one person\'s consumption does not diminish available supply for others ($MC=0$), causing private market failure.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'The "Wagner\'s Law of Increasing State Activity" (Adolph Wagner, 1892) posits that:',
      questionType: 'Direct MCQ',
      options: {
        A: 'As real per capita income and industrialization grow in an economy, public government expenditure grows at an even faster rate as a share of GDP',
        B: 'Government spending automatically collapses to zero during industrialization',
        C: 'Taxes must strictly equal military expenditure',
        D: 'Public debt causes hyperinflation in agricultural states',
      },
      correctAnswer: 'A',
      explanation: 'Wagner observed that modern economic development demands expanded state regulatory oversight, complex infrastructure, education, and welfare expenditures ($dG/dY > 1$).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'The "Peacock-Wiseman Hypothesis" explains the historical growth of public expenditure in terms of structural shocks (wars, major crises) through which mechanism?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Displacement Effect (displacing lower revenue tolerance upward), Inspection Effect, and Concentration Effect',
        B: 'Permanent Income smoothing',
        C: 'Continuous linear compounding',
        D: 'Automatic fiscal stabilizers',
      },
      correctAnswer: 'A',
      explanation: 'Alan Peacock and Jack Wiseman showed that public expenditure grows in step-like jerks during national crises (displacement effect) because taxpayers accept higher tax burdens that persist post-crisis.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'In optimal taxation theory, the "Ramsey Rule" (Frank Ramsey, 1927) states that to minimize total deadweight loss / excess burden when raising a given tax revenue from commodities, tax rates should be set:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Inversely proportional to the price elasticity of demand for each commodity (Inverse Elasticity Rule)',
        B: 'Equal across all goods at a flat 10%',
        C: 'Highest on goods with highly elastic demand',
        D: 'Zero on all agricultural commodities',
      },
      correctAnswer: 'A',
      explanation: 'The Ramsey Rule minimizes economic distortion by taxing price-inelastic necessities (where quantities consumed respond least) at higher ad valorem rates than elastic luxury goods.',
      difficulty: 'HARD',
    },
    {
      unitNumber: 5,
      questionText: 'Under Article 280 of the Constitution of India, the Finance Commission is constituted by the President every five years primarily to recommend:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The vertical devolution of net tax proceeds between the Union and the States and the horizontal distribution among States, alongside Grants-in-Aid under Article 275',
        B: 'The monetary policy repo rate of the RBI',
        C: 'The annual central budget expenditure allocations for central ministries',
        D: 'Foreign direct investment caps in retail',
      },
      correctAnswer: 'A',
      explanation: 'The Finance Commission (e.g. 15th Finance Commission chaired by N.K. Singh recommending 41% vertical devolution) determines statutory fiscal federalism transfers in India.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 6 & 7: MONEY, BANKING & GROWTH ECONOMICS (20 Questions: Q51 - Q70)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 6,
      questionText: 'In monetary economics, the "Money Multiplier" ($m$) in an economy with Currency-Deposit ratio $c$ and Cash Reserve Ratio $r$ is given by:',
      questionType: 'Direct MCQ',
      options: {
        A: '$m = \\frac{1 + c}{c + r}$',
        B: '$m = \\frac{1}{c + r}$',
        C: '$m = \\frac{c}{r}$',
        D: '$m = 1 - (c \\times r)$',
      },
      correctAnswer: 'A',
      explanation: 'Total Money Supply $M = C + D$. High Powered Money $H = C + R$. Dividing by $D$: $m = M/H = \\frac{c + 1}{c + r}$.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 6,
      questionText: 'Under the Reserve Bank of India (RBI) Monetary Policy Framework Agreement enacted in 2016, the statutory inflation target assigned to the Monetary Policy Committee (MPC) is:',
      questionType: 'Direct MCQ',
      options: {
        A: '$4\\%$ Consumer Price Index (CPI) with a tolerance band of $\\pm 2\\%$ ($2\\%$ to $6\\%$)',
        B: '$5\\%$ Wholesale Price Index (WPI)',
        C: '$0\\%$ zero inflation strictly',
        D: '$8\\%$ to promote rapid industrial growth',
      },
      correctAnswer: 'A',
      explanation: 'Section 45ZA of the RBI Act mandates a flexible inflation targeting framework of 4% Headline CPI inflation with a 2-6% tolerance band.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'Under the Basel III international regulatory banking framework, what is the minimum required Common Equity Tier 1 (CET1) ratio and Capital to Risk-Weighted Assets Ratio (CRAR) prescribed for commercial banks?',
      questionType: 'Direct MCQ',
      options: {
        A: 'CET1 of $4.5\\%$ and Total Minimum Capital (CRAR) of $8.0\\%$ ($9.0\\%$ in India as per RBI)',
        B: 'CRAR of $2.0\\%$',
        C: 'CRAR of $25\\%$',
        D: 'Cash holding equal to 100% of all deposits',
      },
      correctAnswer: 'A',
      explanation: 'Basel III strengthened bank capital adequacy, introducing a 4.5% CET1 requirement, 2.5% Capital Conservation Buffer (CCB), and strict Liquidity Coverage Ratios (LCR).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 7,
      questionText: 'In W.W. Rostow\'s "Stages of Economic Growth" (1960), what are the five historical evolutionary stages in chronological order?',
      questionType: 'Direct MCQ',
      options: {
        A: '1: Traditional Society $\\rightarrow$ 2: Preconditions for Take-off $\\rightarrow$ 3: The Take-off $\\rightarrow$ 4: Drive to Maturity $\\rightarrow$ 5: Age of High Mass Consumption',
        B: '1: Feudal $\\rightarrow$ 2: Capitalist $\\rightarrow$ 3: Socialist $\\rightarrow$ 4: Communist $\\rightarrow$ 5: Globalized',
        C: '1: Agrarian $\\rightarrow$ 2: Industrial $\\rightarrow$ 3: Service $\\rightarrow$ 4: Digital $\\rightarrow$ 5: Post-Modern',
        D: '1: Primitive $\\rightarrow$ 2: Mercantilist $\\rightarrow$ 3: Laissez-faire $\\rightarrow$ 4: Welfare $\\rightarrow$ 5: Stagnant',
      },
      correctAnswer: 'A',
      explanation: 'Rostow\'s non-communist manifesto outlined 5 structural stages driven by net investment rates exceeding 10% of national income during the decisive Take-off phase.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'In Arthur Lewis\'s "Two-Sector Dual Economy Model" (1954 - Economic Development with Unlimited Supplies of Labour), economic development is generated by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Transferring surplus labour with zero marginal productivity ($MP_L = 0$) from the traditional subsistence agricultural sector to the modern capitalist industrial sector at a constant institutional wage',
        B: 'Importing foreign heavy agricultural machinery',
        C: 'Depreciating domestic fiat currency',
        D: 'Privatizing national forests',
      },
      correctAnswer: 'A',
      explanation: 'Lewis showed that industrial capital accumulation generates reinvestable capitalist profits by hiring disguisedly unemployed rural workers at a subsistence wage slightly above rural living standards.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 7,
      questionText: 'In the Harrod-Domar growth model, the condition for steady-state equilibrium "Razor\'s Edge" growth requires the equality of which three growth rates?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Actual Growth Rate ($G$), Warranted Growth Rate ($G_w = s/v$), and Natural Growth Rate ($G_n = n + g$)',
        B: 'Inflation rate, Interest rate, and Tax rate',
        C: 'Export growth, Import growth, and Tariff rate',
        D: 'Consumption, Investment, and Government expenditure',
      },
      correctAnswer: 'A',
      explanation: 'Harrod proved that if $G = G_w = G_n$, the economy experiences full-employment non-inflationary growth; any deviation between $G$ and $G_w$ creates cumulative instability (Razor\'s Edge).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 7,
      questionText: 'The "Human Development Index" (HDI) formulated in 1990 by Mahbub ul Haq and Amartya Sen measures composite national achievement across which three fundamental dimensions?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Health (Life Expectancy at birth), Education (Mean and Expected Years of Schooling), and Standard of Living (GNI per capita in PPP $)',
        B: 'GDP, Military strength, and Steel production',
        C: 'Calorie intake, Infant mortality, and Literacy only',
        D: 'Foreign exchange reserves, Internet bandwidth, and Road network',
      },
      correctAnswer: 'A',
      explanation: 'UNDP HDI computes the geometric mean of normalized indices across a long and healthy life, knowledge, and a decent standard of living.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'In development economics, the "Big Push Theory" which advocates massive, synchronized, indivisible capital investments across complementary manufacturing sectors to overcome market failure was propounded by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Paul Rosenstein-Rodan (1943)',
        B: 'Ragnar Nurkse (Vicious Circle of Poverty)',
        C: 'Albert O. Hirschman (Strategy of Unbalanced Growth)',
        D: 'Gunnar Myrdal (Cumulative Causation)',
      },
      correctAnswer: 'A',
      explanation: 'Rosenstein-Rodan argued that bit-by-bit piecemeal investments fail due to demand externalities; a massive coordinated Big Push creates reciprocal markets and achieves economies of scale.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 7,
      questionText: 'The "Gini Coefficient", measuring statistical economic inequality derived from the Lorenz Curve, equals:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The ratio of the area between the Line of Perfect Equality ($45^\\circ$ line) and the Lorenz Curve to the total area below the Line of Perfect Equality (ranging from $0$ to $1$)',
        B: 'The ratio of total debt to GDP',
        C: 'The percentage of population living below poverty line',
        D: 'The variance of export revenues divided by mean income',
      },
      correctAnswer: 'A',
      explanation: 'Gini = $A / (A + B)$. $0$ represents perfect equality (everyone has identical income); $1$ represents absolute maximal inequality (one person owns all national income).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'The concept of the "Capability Approach" to human development and freedom, defining poverty as "capability deprivation" rather than mere low income, was pioneered by Nobel Laureate:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Amartya Sen (author of Development as Freedom)',
        B: 'Abhijit Banerjee',
        C: 'Angus Deaton',
        D: 'Joseph Stiglitz',
      },
      correctAnswer: 'A',
      explanation: 'Amartya Sen focused on substantive freedoms (Capabilities) that enable individuals to lead lives they have reason to value (Functionings), transforming development ethics.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 8, 9 & 10: INDIAN ECONOMY & ENVIRONMENTAL DEMOGRAPHY (30 Questions: Q71 - Q100)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 8,
      questionText: 'Which expert committee appointed by the Planning Commission in 2012 recommended poverty lines based on consumption expenditure of ₹32 per day in rural areas and ₹47 per day in urban areas (Poverty ratio: 29.5% in 2011-12)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'C. Rangarajan Committee (2014)',
        B: 'Suresh Tendulkar Committee (2009 - ₹27 rural / ₹33 urban)',
        C: 'Y.K. Alagh Committee (1979 - 2400/2100 calories)',
        D: 'D.T. Lakdawala Committee (1993)',
      },
      correctAnswer: 'A',
      explanation: 'The Rangarajan Committee updated Tendulkar methodologies, setting the poverty line at monthly per capita consumption of ₹972 (rural) and ₹1407 (urban).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'The Goods and Services Tax (GST) in India was introduced on 1 July 2017 via which landmark Constitutional Amendment Act?',
      questionType: 'Direct MCQ',
      options: {
        A: '101st Constitutional Amendment Act 2016',
        B: '99th Constitutional Amendment Act',
        C: '103rd Constitutional Amendment Act (EWS)',
        D: '122nd Constitutional Amendment Bill',
      },
      correctAnswer: 'A',
      explanation: 'The 101st Constitutional Amendment Act inserted Article 246A and Article 279A, establishing the dual GST structure and the federal GST Council.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'Under the "Fiscal Responsibility and Budget Management Act" (FRBM Act 2003) as reviewed by the N.K. Singh Committee (2017), what are the targeted Fiscal Deficit and General Government Debt-to-GDP ratios?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Fiscal Deficit of $3.0\\%$ of GDP and Debt-to-GDP ratio of $60\\%$ ($40\\%$ for Centre, $20\\%$ for States)',
        B: 'Fiscal Deficit of $0\\%$',
        C: 'Debt-to-GDP ratio of $100\\%$',
        D: 'Revenue deficit of $5\\%$',
      },
      correctAnswer: 'A',
      explanation: 'The N.K. Singh FRBM Committee recommended adopting Debt-to-GDP as the primary fiscal anchor ($60\\%$ combined limit) with a 3.0% Central Fiscal Deficit target.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'The "Environmental Kuznets Curve" (EKC) hypothesis posits an inverted-U shaped relationship between:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Per capita income (economic development) and environmental degradation (pollution rises in early industrialization, peaks, and declines as income rises further)',
        B: 'Inflation and unemployment',
        C: 'Tax rate and tax avoidance',
        D: 'Population density and fertility rate',
      },
      correctAnswer: 'A',
      explanation: 'The EKC suggests that economic growth initially worsens environmental pollution, but beyond a critical turning point per capita income, cleaner technologies and green preferences reduce environmental damage.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'In demographic transition theory, which stage is characterized by high birth rates alongside rapidly declining death rates due to modern healthcare and sanitation, resulting in explosive population growth?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Stage II (Early Expanding / Population Explosion Phase)',
        B: 'Stage I (High Stationary - high birth and death rates)',
        C: 'Stage III (Late Expanding - falling birth rate)',
        D: 'Stage IV (Low Stationary - low birth and death rates)',
      },
      correctAnswer: 'A',
      explanation: 'Stage 2 experiences the classic demographic lag where mortality plummets due to medical interventions while cultural birth rates remain stubbornly high, causing rapid population growth.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'Under the Pradhan Mantri Jan Dhan Yojana (PMJDY) launched in August 2014, the core mandate was universal financial inclusion providing zero-balance bank accounts with:',
      questionType: 'Direct MCQ',
      options: {
        A: 'RuPay debit card, inbuilt accident insurance, and overdraft facility',
        B: 'Free municipal housing loans',
        C: 'Mandatory stock market equity shares',
        D: 'Foreign exchange trading allowances',
      },
      correctAnswer: 'A',
      explanation: 'PMJDY formed the backbone of the JAM Trinity (Jan Dhan, Aadhaar, Mobile) enabling Direct Benefit Transfers (DBT) directly into beneficiary accounts.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'Which sector contributes the highest share to India\'s Gross Value Added (GVA) at current prices (~53-54%), followed by Industry (~28-29%) and Agriculture (~17-18%)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Services Sector (Tertiary Sector)',
        B: 'Agriculture & Allied Activities',
        C: 'Mining & Quarrying',
        D: 'Manufacturing Sector',
      },
      correctAnswer: 'A',
      explanation: 'The Services sector (financial services, IT/ITeS, telecommunications, hospitality, transport) dominates India\'s GVA, driving structural economic output.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'In India, the headline Consumer Price Index (CPI-Combined, Base Year 2012=100) is compiled and released monthly by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'National Statistical Office (NSO), Ministry of Statistics and Programme Implementation (MoSPI)',
        B: 'Reserve Bank of India (RBI)',
        C: 'Office of Economic Adviser, Ministry of Commerce (releases WPI)',
        D: 'NITI Aayog',
      },
      correctAnswer: 'A',
      explanation: 'The NSO (under MoSPI) calculates and releases the CPI-Combined index monthly covering rural, urban, and national consumer price inflation.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'The "Insolvency and Bankruptcy Code" (IBC 2016) introduced a time-bound, creditor-in-control Corporate Insolvency Resolution Process (CIRP) to resolve corporate non-performing assets (NPAs) through which adjudicating tribunal?',
      questionType: 'Direct MCQ',
      options: {
        A: 'National Company Law Tribunal (NCLT)',
        B: 'Debt Recovery Tribunal (DRT - for individuals/partnerships)',
        C: 'Competition Commission of India (CCI)',
        D: 'Securities Appellate Tribunal (SAT)',
      },
      correctAnswer: 'A',
      explanation: 'NCLT acts as the Adjudicating Authority for corporate insolvency resolution processes under IBC 2016 with a statutory 180+90=270/330 day timeline.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'Under India\'s Foreign Trade Policy, Special Economic Zones (SEZs) established under the SEZ Act 2005 are deemed to be:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Foreign territory for the purposes of trade operations, duties, and tariffs within the geographical territory of India',
        B: 'State government tax departments',
        C: 'Domestic tariff areas without tax incentives',
        D: 'Exclusively agricultural research zones',
      },
      correctAnswer: 'A',
      explanation: 'SEZs are designated duty-free enclaves treated as foreign territory for trade operations, customs tariffs, and tax holidays to promote merchandise and services export.',
      difficulty: 'EASY',
    },
  ];

  return {
    subjectCode: '01',
    subjectSlug: 'economics',
    mockNumber: 1,
    title: 'Economics — Mock Test 1: Full Syllabus Simulation (100 Qs)',
    description: 'Authentic 100-question UGC NET Economics simulation covering Microeconomics, Macroeconomics, Statistics/Econometrics, International Trade, Public Finance, Money/Banking, Growth & Development, Environmental Demography, and Indian Economy across all 10 units.',
    accessTier: 'FREE',
    isFreeBenchmark: true,
    questions,
  };
}
