import { MockTestDefinition, RawMockQuestion } from '../common';

export function getEnglishMockTest(): MockTestDefinition {
  const questions: RawMockQuestion[] = [
    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 1: DRAMA (10 Questions: Q1 - Q10)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 1,
      questionText: 'In Christopher Marlowe\'s "Doctor Faustus", for how many years of worldly omnipotence, esoteric knowledge, and necromantic power does Faustus barter his soul to Lucifer and Mephistophilis?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Twenty-four (24) years',
        B: 'Twelve (12) years',
        C: 'Thirty (30) years',
        D: 'Seven (7) years',
      },
      correctAnswer: 'A',
      explanation: 'Faustus signs a deed in his own congealing blood surrendering his soul to Lucifer in exchange for 24 years of having Mephistophilis serve his every command.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In Shakespeare\'s "Hamlet", the "Mousetrap" (The Murder of Gonzago) is staged by Hamlet before King Claudius specifically to:',
      questionType: 'Direct MCQ',
      options: {
        A: '"Catch the conscience of the King" and test the veracity of the Ghost\'s accusation of fratricide',
        B: 'Entertain Ophelia and Polonius on the royal anniversary',
        C: 'Mock the visiting Rosencrantz and Guildenstern',
        D: 'Declare war on Prince Fortinbras of Norway',
      },
      correctAnswer: 'A',
      explanation: 'Hamlet re-enacts his father\'s murder by poison poured into the ear to observe Claudius\'s guilt reaction: "The play\'s the thing / Wherein I\'ll catch the conscience of the King."',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In Samuel Beckett\'s landmark Theatre of the Absurd masterpiece "Waiting for Godot" (1953), which two central tramps spend the entirety of the two-act play waiting near a solitary tree beside a country road for an enigmatic figure who never arrives?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Vladimir (Didi) and Estragon (Gogo)',
        B: 'Pozzo and Lucky',
        C: 'Hamm and Clov (Endgame)',
        D: 'Rosencrantz and Guildenstern',
      },
      correctAnswer: 'A',
      explanation: 'Vladimir and Estragon pass time with vaudevillian banter, existential philosophical despair, and circular dialogues waiting in vain for Godot.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In John Webster\'s Jacobean revenge tragedy "The Duchess of Malfi" (1614), who serves as the melancholic court spy and hired assassin who strangles the Duchess under the orders of Duke Ferdinand and the Cardinal?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Daniel de Bosola',
        B: 'Antonio Bologna (the Duchess\'s secret husband)',
        C: 'Delio',
        D: 'Castruccio',
      },
      correctAnswer: 'A',
      explanation: 'Bosola is Webster\'s complex malcontent and intelligencer who murders the Duchess and her children, but later seeks repentance and vengeance against his corrupt aristocratic employers.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In Bertolt Brecht\'s Epic Theatre, what dramatic technique (Verfremdungseffekt / Alienation Effect) is systematically employed to prevent passive emotional catharsis and induce critical socio-political reflection in the audience?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Directly addressing the audience, visible stage lighting, projected placards/titles, episodic non-linear structure, and interrupting songs',
        B: 'Realistic Stanislavski method acting',
        C: 'Strict adherence to classical Aristotelian unities of time, place, and action',
        D: 'Elaborate illusionistic stage sets',
      },
      correctAnswer: 'A',
      explanation: 'Brecht\'s "A-effect" deliberately shatters dramatic theatrical illusion so spectators remain active, rational, critical analysts of socioeconomic structures rather than passive weeping observers.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In Restoration Comedy of Manners, William Congreve\'s "The Way of the World" (1700) features the celebrated "Proviso Scene" (bargaining marital conditions before marriage) between which two witty lovers?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Mirabell and Millamant',
        B: 'Fainall and Mrs. Marwood',
        C: 'Sir Wilfull Witwoud and Lady Wishfort',
        D: 'Dorimant and Harriet (The Man of Mode)',
      },
      correctAnswer: 'A',
      explanation: 'The Proviso scene between Mirabell and Millamant is the pinnacle of Restoration wit, negotiating individual liberty and mutual respect within the institution of marriage.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In Harold Pinter\'s "Comedy of Menace" play "The Birthday Party" (1957), which two mysterious sinister visitors arrive at a dilapidated seaside boarding house to interrogate and psychologically destroy the reclusive pianist Stanley Webber?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Goldberg and McCann',
        B: 'Ben and Gus (The Dumb Waiter)',
        C: 'Mick and Aston (The Caretaker)',
        D: 'Teddy and Lenny (The Homecoming)',
      },
      correctAnswer: 'A',
      explanation: 'Nat Goldberg and Seamus McCann represent oppressive, ambiguous external authority who subject Stanley to absurd interrogation, blindfold him, and take him away catatonic.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In Girish Karnad\'s celebrated Indian play "Tughlaq" (1964), the idealistic 14th-century Delhi Sultan is portrayed as an existential tragic figure whose vision of secular harmony collapses into paranoia and tyranny, functioning as an allegory for:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The disillusionment of the Nehruvian era in post-independence India',
        B: 'The Mughal war of succession under Aurangzeb',
        C: 'The British partition of Bengal in 1905',
        D: 'The 1857 Sepoy Mutiny',
      },
      correctAnswer: 'A',
      explanation: 'Karnad\'s Tughlaq is a profound political allegory reflecting the disenchantment with Jawaharlal Nehru\'s socialist idealism in the 1960s as grand state projects collapsed into cynicism.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In Arthur Miller\'s "Death of a Salesman" (1949), what is the tragic protagonist Willy Loman\'s tragic delusion regarding the American Dream?',
      questionType: 'Direct MCQ',
      options: {
        A: 'That commercial success and wealth depend on being "well-liked" and possessing superficial personal charm rather than genuine skill or substantive labour',
        B: 'That farming in Texas is superior to city life',
        C: 'That his son Biff will become a corporate lawyer',
        D: 'That life insurance policies are illegal',
      },
      correctAnswer: 'A',
      explanation: 'Willy Loman destroys himself chasing the empty consumerist myth that being attractive and well-liked guarantees financial prosperity in capitalist America.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In George Bernard Shaw\'s problem play "Pygmalion" (1913), the phonetics professor Henry Higgins wagers with Colonel Pickering that he can transform which Cockney flower girl into a refined lady passing in high society?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Eliza Doolittle',
        B: 'Clara Eynsford-Hill',
        C: 'Mrs. Pearce',
        D: 'Major Barbara',
      },
      correctAnswer: 'A',
      explanation: 'Shaw explores class hierarchy, gender autonomy, and phonetics as Higgins trains Eliza Doolittle to speak received pronunciation.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 2: POETRY (10 Questions: Q11 - Q20)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 2,
      questionText: 'In Geoffrey Chaucer\'s "The General Prologue to The Canterbury Tales" (c. 1387), the spring pilgrimage of 29 pilgrims to the shrine of Saint Thomas Becket begins in April from which Southwark tavern?',
      questionType: 'Direct MCQ',
      options: {
        A: 'The Tabard Inn (hosted by Harry Bailly)',
        B: 'The Boar\'s Head Tavern',
        C: 'The Mermaid Tavern',
        D: 'The Red Lion Inn',
      },
      correctAnswer: 'A',
      explanation: '"Whan that Aprill with his shoures soote... At The Tabard as I lay / Redy to wenden on my pilgrymage / To Caunterbury with ful devout corage."',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In John Milton\'s epic "Paradise Lost" (1667), what is the declared supreme theological argument and poetic objective stated in Book I (Line 26)?',
      questionType: 'Direct MCQ',
      options: {
        A: '"To assert Eternal Providence, / And justify the ways of God to men"',
        B: '"To celebrate the rebellion of Satan in Hell"',
        C: '"To establish the divine right of British Stuart kings"',
        D: '"To describe the astronomy of Galileo\'s telescope"',
      },
      correctAnswer: 'A',
      explanation: 'Milton invokes the Heavenly Muse in Book I, seeking divine inspiration to encompass the Fall of Man and vindicate divine justice.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In John Donne\'s Metaphysical poem "A Valediction: Forbidding Mourning", the spiritual union and constant love of two physically separated lovers is famously compared in a celebrated metaphysical conceit to:',
      questionType: 'Direct MCQ',
      options: {
        A: 'A pair of stiff twin drafting compasses ("Thy soul, the fixed foot, makes no show / To move, but doth, if th\' other do")',
        B: 'A flea that mingles blood',
        C: 'Two globes on a celestial sphere',
        D: 'Sunlight passing through a stained-glass prism',
      },
      correctAnswer: 'A',
      explanation: 'Donne\'s famous compass conceit demonstrates how the fixed foot leans and hearkens after the roving foot, making their circle just and true.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In Alexander Pope\'s mock-heroic epic "The Rape of the Lock" (1714), who is the Guardian Sylph assigned to protect the lock of Belinda\'s hair from the shears of the Baron?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Ariel',
        B: 'Umbriel (the melancholic gnome who descends to the Cave of Spleen)',
        C: 'Brillante',
        D: 'Crispissa',
      },
      correctAnswer: 'A',
      explanation: 'Pope utilizes Rosicrucian supernatural machinery (Sylphs, Gnomes, Nymphs, Salamanders); Ariel directs fifty chosen sylphs to guard Belinda\'s sacred petticoat and coiffure.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'William Wordsworth and Samuel Taylor Coleridge launched the English Romantic Movement with the joint publication of "Lyrical Ballads" in 1798. Which landmark poem opens the collection, and which poem concludes it?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Opens with Coleridge\'s "The Rime of the Ancient Mariner" and concludes with Wordsworth\'s "Lines Written a Few Miles above Tintern Abbey"',
        B: 'Opens with "Kubla Khan" and concludes with "Ode: Intimations of Immortality"',
        C: 'Opens with "We Are Seven" and concludes with "Christabel"',
        D: 'Opens with "The Prelude" and concludes with "Frost at Midnight"',
      },
      correctAnswer: 'A',
      explanation: 'The 1798 anonymous edition opened with Coleridge\'s supernatural ballad of the albatross and concluded with Wordsworth\'s sublime pantheistic meditation on the banks of Wye.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In John Keats\'s "Ode on a Grecian Urn" (1819), the speaker addresses the cold pastoral urn, concluding with which immortal aesthetic aphorism?',
      questionType: 'Direct MCQ',
      options: {
        A: '"\'Beauty is truth, truth beauty,\'—that is all / Ye know on earth, and all ye need to know"',
        B: '"A thing of beauty is a joy for ever" (Endymion)',
        C: '"Heard melodies are sweet, but those unheard / Are sweeter"',
        D: '"Now more than ever seems it rich to die" (Ode to a Nightingale)',
      },
      correctAnswer: 'A',
      explanation: 'Keats reflects on eternal art versus fleeting human passion on the Attic marble urn, concluding with the paradox of Beauty and Truth.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In Robert Browning\'s Victorian dramatic monologue "My Last Duchess" (1842), the Duke of Ferrara is negotiating a second marriage with an envoy while admiring a portrait of his deceased young duchess painted on the wall by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Fra Pandolf',
        B: 'Claus of Innsbruck (who cast a bronze Neptune taming a sea-horse)',
        C: 'Andrea del Sarto',
        D: 'Fra Lippo Lippi',
      },
      correctAnswer: 'A',
      explanation: 'The Duke chillingly reveals his possessive, authoritarian jealousy over his late wife\'s democratic smile: "I gave commands; / Then all smiles stopped together."',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In T.S. Eliot\'s High Modernist masterwork "The Waste Land" (1922), what are the titles of the five sections in correct chronological sequence?',
      questionType: 'Direct MCQ',
      options: {
        A: 'I. The Burial of the Dead $\\rightarrow$ II. A Game of Chess $\\rightarrow$ III. The Fire Sermon $\\rightarrow$ IV. Death by Water $\\rightarrow$ V. What the Thunder Said',
        B: 'I. The Fire Sermon $\\rightarrow$ II. What the Thunder Said $\\rightarrow$ III. Death by Water $\\rightarrow$ IV. A Game of Chess $\\rightarrow$ V. The Hollow Men',
        C: 'I. April is the Cruelest Month $\\rightarrow$ II. Madame Sosostris $\\rightarrow$ III. Tiresias $\\rightarrow$ IV. Phlebas $\\rightarrow$ V. Shantih',
        D: 'I. East Coker $\\rightarrow$ II. Burnt Norton $\\rightarrow$ III. The Dry Salvages $\\rightarrow$ IV. Little Gidding $\\rightarrow$ V. Ash Wednesday',
      },
      correctAnswer: 'A',
      explanation: 'Edited by Ezra Pound ("il miglior fabbro"), The Waste Land moves across the 5 structural movements culminating in the Upanishadic benediction: "Datta. Dayadhvam. Damyata. / Shantih shantih shantih".',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In W.B. Yeats\'s apocalyptic Modernist poem "The Second Coming" (1919), written in the aftermath of World War I and the Russian Revolution, what iconic image represents the unraveling of modern civilization?',
      questionType: 'Direct MCQ',
      options: {
        A: '"Turning and turning in the widening gyre / The falcon cannot hear the falconer; / Things fall apart; the centre cannot hold"',
        B: '"I have measured out my life with coffee spoons"',
        C: '"The woods are lovely, dark and deep"',
        D: '"An aged man is but a paltry thing, / A tattered coat upon a stick"',
      },
      correctAnswer: 'A',
      explanation: 'Yeats\'s vision of the gyre and the rough beast slouching towards Bethlehem to be born provided the title for Chinua Achebe\'s famous African novel "Things Fall Apart".',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In Indian English poetry, which bilingual poet authored the autobiographical confessional poem "An Introduction" ("I am Indian, very brown, born in Malabar, / I speak three languages, write in / Two, dream in one") and "The Old Playhouse"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Kamala Das (Madhavikutty)',
        B: 'Nissim Ezekiel (author of Night of the Scorpion)',
        C: 'A.K. Ramanujan',
        D: 'Toru Dutt (Our Casuarina Tree)',
      },
      correctAnswer: 'A',
      explanation: 'Kamala Das pioneered uninhibited, confessional feminist poetry in Indian English exploring female sexuality, patriarchy, and linguistic freedom.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 3: FICTION AND SHORT STORY (10 Questions: Q21 - Q30)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 3,
      questionText: 'In Daniel Defoe\'s "Robinson Crusoe" (1719), what name does Crusoe give to the native Carib captive whom he rescues from cannibals on the deserted island?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Friday (named after the day of the week on which his life was saved)',
        B: 'Monday',
        C: 'Sunday',
        D: 'Xury',
      },
      correctAnswer: 'A',
      explanation: 'Defoe\'s foundational novel depicts Crusoe naming Friday, teaching him English and Christianity, reflecting 18th-century colonialist and master-servant paradigms.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In Jane Austen\'s "Pride and Prejudice" (1813), who embodies "Pride" and who embodies "Prejudice" in the central romantic dynamic between the protagonists?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Mr. Fitzwilliam Darcy embodies aristocratic Pride; Elizabeth Bennet embodies hasty Prejudice against him',
        B: 'Mr. Bingley embodies Pride; Jane Bennet embodies Prejudice',
        C: 'Mr. Wickham embodies Pride; Lydia Bennet embodies Prejudice',
        D: 'Mr. Collins embodies Pride; Lady Catherine de Bourgh embodies Prejudice',
      },
      correctAnswer: 'A',
      explanation: 'Austen traces the moral and intellectual maturation of Darcy (overcoming aristocratic haughtiness) and Elizabeth (shedding snap prejudice based on Wickham\'s lies).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In Emily Brontë\'s gothic masterpiece "Wuthering Heights" (1847), what are the names of the two contrasting estates representing storm/passion and calm/convention?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Wuthering Heights (Earnshaw family / Heathcliff) and Thrushcross Grange (Linton family)',
        B: 'Thornfield Hall and Gateshead (Jane Eyre)',
        C: 'Lowood and Moor House',
        D: 'Mansfield Park and Sotherton',
      },
      correctAnswer: 'A',
      explanation: 'Wuthering Heights on the wild windblown Yorkshire moors contrasts with the civilized, refined Thrushcross Grange in the valley.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In Charles Dickens\'s "Great Expectations" (1861), who is the secret benefactor who finances Pip\'s rise into high gentlemanly society in London?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Abel Magwitch (the escaped convict whom Pip had aided in the marshes as a boy)',
        B: 'Miss Havisham of Satis House',
        C: 'Uncle Pumblechook',
        D: 'Mr. Jaggers the lawyer',
      },
      correctAnswer: 'A',
      explanation: 'Pip assumes Miss Havisham has made him her wealthy heir for Estella; the shattering revelation that his benefactor is the hunted convict Magwitch triggers Pip\'s moral regeneration.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In James Joyce\'s landmark High Modernist stream-of-consciousness novel "Ulysses" (1922), the entire narrative unfolds during a single ordinary day in Dublin on:',
      questionType: 'Direct MCQ',
      options: {
        A: '16 June 1904 ("Bloomsday")',
        B: '4 July 1914',
        C: '1 January 1900',
        D: '24 December 1922',
      },
      correctAnswer: 'A',
      explanation: 'Joyce maps Leopold Bloom\'s odyssey across Dublin on 16 June 1904 (now celebrated internationally as Bloomsday), paralleling Homer\'s Odyssey.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In Virginia Woolf\'s stream-of-consciousness novel "Mrs. Dalloway" (1925), which shell-shocked World War I veteran suffering from traumatic hallucinations functions as Clarissa Dalloway\'s tragic psychological double?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Septimus Warren Smith',
        B: 'Peter Walsh',
        C: 'Richard Dalloway',
        D: 'Sir William Bradshaw',
      },
      correctAnswer: 'A',
      explanation: 'Septimus commits suicide by leaping from a window to escape Dr. Bradshaw\'s institutional asylum; Clarissa hears of his death at her evening party and understands his sacrifice.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In George Orwell\'s dystopian political masterpiece "Nineteen Eighty-Four" (1949), what are the three official paradox slogans of the Party (Ingsoc) inscribed on the Ministry of Truth?',
      questionType: 'Direct MCQ',
      options: {
        A: '"WAR IS PEACE / FREEDOM IS SLAVERY / IGNORANCE IS STRENGTH"',
        B: '"WORK SETS YOU FREE / OBEDIENCE IS DUTY / STATE IS GOD"',
        C: '"BIG BROTHER IS WATCHING / COMRADES UNITE / VICTORY IS SURE"',
        D: '"COMMUNITY / IDENTITY / STABILITY" (Brave New World)',
      },
      correctAnswer: 'A',
      explanation: 'Orwell details Doublethink, Newspeak, Thoughtcrime, the Two Minutes Hate, and the omnipresent surveillance of Big Brother in Oceania.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In Salman Rushdie\'s Booker of Bookers winning novel "Midnight\'s Children" (1981), what supernatural power does the protagonist Saleem Sinai, born at the exact midnight stroke of India\'s independence (15 August 1947), possess?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Telepathic communication acting as a radio receiver convening all 1,001 midnight children, and an extraordinary all-detecting sense of smell',
        B: 'Invisibility during solar eclipses',
        C: 'Time-travel back to the Mughal era',
        D: 'Physical immortality',
      },
      correctAnswer: 'A',
      explanation: 'Saleem Sinai\'s body and consciousness are intimately tied to the political destiny of modern India via magical realism and historiographical metafiction.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In Chinua Achebe\'s foundational African novel "Things Fall Apart" (1958), the tragic protagonist Okonkwo is a fierce wrestling champion and leader of which Igbo village in Nigeria?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Umuofia',
        B: 'Mbanta (his motherland)',
        C: 'Malindi',
        D: 'Kigali',
      },
      correctAnswer: 'A',
      explanation: 'Achebe tells the story of Okonkwo and the tragic destruction of Umuofia\'s traditional customs under British colonial and missionary intrusion.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In R.K. Narayan\'s classic novel "The Guide" (1958), set in the fictional South Indian town of Malgudi, what transformation does the protagonist Raju undergo throughout the narrative?',
      questionType: 'Direct MCQ',
      options: {
        A: 'From a corrupt tourist guide and theatrical manager of dancer Rosie (Nalini) to an accidental revered ascetic holy man / Sadhu who fasts to death for rain',
        B: 'From a school teacher to an international diplomat',
        C: 'From a railway engineer to a politician',
        D: 'From a temple priest to a cricket player',
      },
      correctAnswer: 'A',
      explanation: 'Raju\'s narrative alternates between his past love affair with Rosie and his imprisonment, culminating in his sacrificial fast on the riverbanks of Sarayu in Mangal village.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 4, 5, 6, 7 & 8: PROSE, LANGUAGE & CRITICAL THEORY (50 Questions: Q31 - Q80)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 4,
      questionText: 'Who is celebrated as the "Father of the English Essay", known for his concise, aphoristic, pragmatic, and Latinate essays such as "Of Truth", "Of Studies", and "Of Revenge"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Francis Bacon',
        B: 'Michel de Montaigne (Father of the Essay)',
        C: 'Charles Lamb (Essays of Elia)',
        D: 'William Hazlitt',
      },
      correctAnswer: 'A',
      explanation: 'Francis Bacon\'s essays are famous for maxims like "Studies serve for delight, for ornament, and for ability" and "Revenge is a kind of wild justice."',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'In John Milton\'s celebrated 1644 prose tract "Areopagitica", what fundamental democratic right is passionately defended before the English Parliament?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Freedom of the Press and the abolition of pre-publication state censorship ("Give me the liberty to know, to utter, and to argue freely according to conscience, above all liberties")',
        B: 'Universal adult suffrage for women',
        C: 'Abolition of private property',
        D: 'Establishment of the Church of England',
      },
      correctAnswer: 'A',
      explanation: 'Milton attacked the Licensing Order of 1643, asserting that truth will always prevail over falsehood in an open and unhindered encounter ("Let her and Falsehood grapple").',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'In historical English linguistics, the massive systematic phonological shift in the pronunciation of Middle English long vowels that occurred roughly between 1400 and 1700 is known as the:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Great Vowel Shift (Otto Jespersen, 1909)',
        B: 'Grimm\'s Law (First Germanic Sound Shift)',
        C: 'Verner\'s Law',
        D: 'Norman French Palatalization',
      },
      correctAnswer: 'A',
      explanation: 'The Great Vowel Shift raised all Middle English long vowels (e.g. /iː/ and /uː/ diphthongized into /aɪ/ and /aʊ/), explaining why English spelling diverges from modern pronunciation.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 6,
      questionText: 'The historic "Macaulay\'s Minute on Indian Education" (2 February 1835), which led to Lord William Bentinck passing the English Education Act 1835, advocated teaching Western science and literature in English to create:',
      questionType: 'Direct MCQ',
      options: {
        A: '"A class of persons, Indian in blood and colour, but English in taste, in opinions, in morals, and in intellect" (Downward Filtration Theory)',
        B: 'Autonomous Sanskrit and Arabic research universities in every district',
        C: 'Free elementary education in local vernacular dialects',
        D: 'Vocational technical training schools for agriculture',
      },
      correctAnswer: 'A',
      explanation: 'Thomas Babington Macaulay dismissed Oriental learning ("a single shelf of a good European library was worth the whole native literature of India and Arabia"), establishing English education.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'Who founded the Centre for Contemporary Cultural Studies (CCCS) at the University of Birmingham in 1964, establishing British Cultural Studies alongside Raymond Williams and Stuart Hall?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Richard Hoggart (author of The Uses of Literacy, 1957)',
        B: 'E.P. Thompson (The Making of the English Working Class)',
        C: 'Terry Eagleton',
        D: 'Frank Raymond Leavis (Scrutiny journal)',
      },
      correctAnswer: 'A',
      explanation: 'Richard Hoggart founded the Birmingham Centre (CCCS), shifting literary analysis toward popular working-class culture, television, youth subcultures, and mass media.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'In Aristotle\'s "Poetics", what term denotes the tragic hero\'s fatal misjudgment, error of judgment, or flaw that leads to their downfall in tragedy?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Hamartia',
        B: 'Catharsis (purgation of pity and fear)',
        C: 'Anagnorisis (recognition/discovery)',
        D: 'Peripeteia (sudden reversal of fortune)',
      },
      correctAnswer: 'A',
      explanation: 'Hamartia is the tragic error of judgment (like Oedipus\'s blindness to his parentage or Othello\'s credulity) that triggers the tragic peripeteia.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'In "Biographia Literaria" (1817), Samuel Taylor Coleridge famously distinguished between:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Primary Imagination (the living power and prime agent of all human perception), Secondary Imagination (the poetic agency that dissolves, diffuses, dissipates to recreate), and Fancy (a mechanical aggregator of memories)',
        B: 'Negative Capability and Egotistical Sublime',
        C: 'Objective Correlative and Dissociation of Sensibility',
        D: 'Apollonian and Dionysian instincts',
      },
      correctAnswer: 'A',
      explanation: 'Coleridge elevated the esemplastic Secondary Imagination as the supreme creative power unifying opposites, distinct from associative Fancy.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'In his 1817 letter to his brothers George and Thomas, which Romantic poet coined the concept of "Negative Capability" (the capacity of a great writer to exist "in uncertainties, Mysteries, doubts, without any irritable reaching after fact & reason") using Shakespeare as the supreme exemplar?',
      questionType: 'Direct MCQ',
      options: {
        A: 'John Keats',
        B: 'Percy Bysshe Shelley (A Defence of Poetry)',
        C: 'William Wordsworth',
        D: 'Lord Byron',
      },
      correctAnswer: 'A',
      explanation: 'Keats defined Negative Capability as artistic selflessness and open receptive contemplation without ideological or philosophical dogmatism.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'In his critical essay "Tradition and the Individual Talent" (1919), T.S. Eliot propounded the "Impersonal Theory of Poetry", famously asserting that:',
      questionType: 'Direct MCQ',
      options: {
        A: '"Poetry is not a turning loose of emotion, but an escape from emotion; it is not the expression of personality, but an escape from personality"',
        B: '"Poetry is the spontaneous overflow of powerful feelings recollected in tranquility" (Wordsworth)',
        C: '"Poets are the unacknowledged legislators of the world" (Shelley)',
        D: '"All art is quite useless" (Oscar Wilde)',
      },
      correctAnswer: 'A',
      explanation: 'Eliot used the chemical catalyst analogy (filament of platinum) to argue that the poet\'s mind transforms experience into art without imposing personal biography.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'In New Criticism, the critical fallacy of evaluating a literary work based on the psychological intention or biographical design of its author was termed the "Intentional Fallacy" (1946) by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'W.K. Wimsatt and Monroe Beardsley',
        B: 'Cleanth Brooks (The Well Wrought Urn)',
        C: 'I.A. Richards (Principles of Literary Criticism)',
        D: 'John Crowe Ransom',
      },
      correctAnswer: 'A',
      explanation: 'Wimsatt and Beardsley also formulated the "Affective Fallacy" (confusing the poem with its emotional effects on readers), demanding close intrinsic textual reading.',
      difficulty: 'MEDIUM',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 9 & 10: CONTEMPORARY THEORY & RESEARCH METHODS (20 Questions: Q81 - Q100)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 9,
      questionText: 'In Structuralist linguistics, Ferdinand de Saussure ("Course in General Linguistics", 1916) established that the linguistic Sign is composed of which two indivisible arbitrary components?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Signifier (Signifiant - the acoustic sound-image) and Signified (Signifié - the mental concept)',
        B: 'Langue and Parole',
        C: 'Syntagm and Paradigm',
        D: 'Denotation and Connotation',
      },
      correctAnswer: 'A',
      explanation: 'Saussure proved that language is a differential system of arbitrary signs where meaning is generated through relational contrasts rather than positive intrinsic essences.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'In Post-Structuralism and Deconstruction, Jacques Derrida delivered his epochal 1966 Johns Hopkins lecture "Structure, Sign, and Play in the Discourse of the Human Sciences" introducing "Différance", meaning:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Simultaneously "to differ" (spatial distinction) and "to defer" (temporal postponement of ultimate meaning / transcendental signified)',
        B: 'The absolute grammatical unity of binary oppositions',
        C: 'The biographical truth behind authorial signatures',
        D: 'The linguistic translation from French into English',
      },
      correctAnswer: 'A',
      explanation: 'Derrida\'s Différance (with an \'a\') demonstrates how meaning in Western logocentric metaphysics is never immediately present but endlessly deferred along a chain of signifiers.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'In his landmark 1967 essay "The Death of the Author", Roland Barthes proclaimed that to give a text an Author is to impose a limit on that text, declaring that:',
      questionType: 'Direct MCQ',
      options: {
        A: '"The birth of the reader must be at the cost of the death of the Author"',
        B: '"The author is the sole master of textual interpretation"',
        C: '"Literature must be destroyed to make way for political speeches"',
        D: '"All literary texts are sacred scriptures"',
      },
      correctAnswer: 'A',
      explanation: 'Barthes showed that a text is a tissue of quotations drawn from innumerable centres of culture; unity lies not in its origin (the author) but in its destination (the reader).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'In Postcolonial Theory, Edward Said\'s foundational text "Orientalism" (1978) utilizes Michel Foucault\'s concept of Discourse to demonstrate that:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The "Orient" is not an objective geographical reality, but an imperial Western epistemological and discursive construct produced to dominate, restructure, and have authority over the East',
        B: 'Eastern and Western cultures have identical literary traditions',
        C: 'Imperialism was solely an economic trade policy without cultural representation',
        D: 'Asian languages cannot be translated into European grammar',
      },
      correctAnswer: 'A',
      explanation: 'Said analyzed European travelogues, novels, and scholarship, showing how the Orient was systematically depicted as exotic, passive, irrational, and feminine to justify colonial domination.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'In Postcolonial Theory, Homi K. Bhabha ("The Location of Culture", 1994) developed which key conceptual terms to analyze the ambivalence of the colonial encounter?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Hybridity, Mimicry ("almost the same, but not quite / not white"), and the Third Space of Enunciation',
        B: 'Subalternity, Strategic Essentialism, and Epistemic Violence (Spivak)',
        C: 'Négritude, National Culture, and Manichean Delirium (Fanon)',
        D: 'Contact Zone and Transculturation (Mary Louise Pratt)',
      },
      correctAnswer: 'A',
      explanation: 'Bhabha analyzes how colonial mimicry produces a subversive double, creating ambivalent in-between interstitial spaces (Third Space) that disrupt colonial authority.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'In Subaltern Studies and Feminist Postcolonialism, who authored the seminal 1988 essay "Can the Subaltern Speak?", analyzing the British colonial abolition of Sati and Bhubaneswari Bhaduri\'s suicide?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Gayatri Chakravorty Spivak',
        B: 'Chandra Talpade Mohanty (Under Western Eyes)',
        C: 'Sara Suleri (Meatless Days)',
        D: 'Aijaz Ahmad (In Theory)',
      },
      correctAnswer: 'A',
      explanation: 'Spivak concludes that the gendered subaltern has no institutional discursive position from which to speak, caught between patriarchal domestic traditions and colonialist legal paternalism.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'In Feminist Literary Criticism, Elaine Showalter coined the term "Gynocritics" in "Towards a Feminist Poetics" (1979) to describe:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The specialized study of women as writers, focusing on female literary history, themes, genres, language, and the female creative imagination',
        B: 'The analysis of male misogyny in classic literature (Feminist Reading)',
        C: 'The psychoanalysis of Freud\'s dream studies',
        D: 'The linguistic study of French romantic poetry',
      },
      correctAnswer: 'A',
      explanation: 'Showalter distinguished between Woman as Reader (feminist critique) and Woman as Writer (Gynocritics), tracing three phases: Feminine, Feminist, and Female.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'In Marxist literary theory, who introduced the concept of the "Political Unconscious" in his 1981 work "The Political Unconscious: Narrative as a Socially Symbolic Act", opening with the famous injunction "Always historicize!"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Fredric Jameson',
        B: 'Terry Eagleton (Marxism and Literary Criticism)',
        C: 'Louis Althusser',
        D: 'Georg Lukács (The Historical Novel)',
      },
      correctAnswer: 'A',
      explanation: 'Fredric Jameson argues that literature serves as a socially symbolic act striving to resolve real historical class contradictions at an imaginary, narrative level.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'In MLA 9th Edition academic documentation and bibliography, which of the following is the standard order of the "Core Elements" for citing a containerized source in the Works Cited list?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Author $\\rightarrow$ Title of source $\\rightarrow$ Title of container $\\rightarrow$ Contributor $\\rightarrow$ Version $\\rightarrow$ Number $\\rightarrow$ Publisher $\\rightarrow$ Publication date $\\rightarrow$ Location (pages/DOI/URL)',
        B: 'Title $\\rightarrow$ Date $\\rightarrow$ Author $\\rightarrow$ Location $\\rightarrow$ Publisher',
        C: 'Publisher $\\rightarrow$ Author $\\rightarrow$ Title $\\rightarrow$ Date',
        D: 'Author $\\rightarrow$ Year in parentheses $\\rightarrow$ Title $\\rightarrow$ City of publication (APA style)',
      },
      correctAnswer: 'A',
      explanation: 'The MLA 9 template of core elements provides a universal 9-part container hierarchy concluding with punctuation marks for academic citations.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'In literary research ethics, what is "Self-Plagiarism" (Text Recycling)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Re-submitting or republishing one\'s own previously published work, data, or significant text passages in a new publication without proper citation, acknowledgment, or publisher permission',
        B: 'Copying lines from an anonymous medieval ballad',
        C: 'Translating an ancient Latin inscription into English verse',
        D: 'Writing a parody of Shakespeare\'s sonnets',
      },
      correctAnswer: 'A',
      explanation: 'Self-plagiarism misleads academic readers and editors regarding the novelty and originality of research contributions by recycling prior publications without citation.',
      difficulty: 'EASY',
    },
  ];

  return {
    subjectCode: '30',
    subjectSlug: 'english',
    mockNumber: 1,
    title: 'English — Mock Test 1: Full Syllabus Simulation (100 Qs)',
    description: 'Authentic 100-question UGC NET English Literature simulation covering Drama, Poetry, Fiction, Prose, English in India, Cultural Studies, Literary Criticism, Contemporary Critical Theory, and Research Methodology across all 10 units.',
    accessTier: 'FREE',
    isFreeBenchmark: true,
    questions,
  };
}
