import { MockTestDefinition, RawMockQuestion } from '../common';

export function getHistoryMockTest(): MockTestDefinition {
  const questions: RawMockQuestion[] = [
    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 1: SOURCES AND EARLY INDIAN HISTORY (10 Questions: Q1 - Q10)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 1,
      questionText: 'Which ancient Harappan port city featured a massive brick tidal dockyard connected to the Sabarmati river channel and extensive bead-making workshops?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Kalibangan',
        B: 'Lothal',
        C: 'Dholavira',
        D: 'Banawali',
      },
      correctAnswer: 'B',
      explanation: 'Lothal in Gujarat (excavated by S.R. Rao) is famous for its sophisticated brick dockyard, bead factory, and evidence of maritime trade with Mesopotamia.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In the Rigveda, the legendary "Battle of the Ten Kings" (Dasharajna Yuddha), wherein King Sudas of the Bharata tribe defeated a confederacy of ten tribes, took place on the banks of which river?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Parushni (Modern Ravi)',
        B: 'Vipash (Modern Beas)',
        C: 'Asikni (Modern Chenab)',
        D: 'Vitasta (Modern Jhelum)',
      },
      correctAnswer: 'A',
      explanation: 'The Battle of the Ten Kings (Rigveda Mandala VII) was fought on the banks of river Parushni (modern Ravi river) under the leadership of Tritsu-Bharata king Sudas assisted by sage Vasishtha.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'Which Ashokan Major Rock Edict provides the direct epigraphic account of the Kalinga War and proclaims the emperor\'s remorse and adoption of "Dhamma Vijaya" over military conquest?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Major Rock Edict X',
        B: 'Major Rock Edict XII',
        C: 'Major Rock Edict XIII',
        D: 'Minor Rock Edict I',
      },
      correctAnswer: 'C',
      explanation: 'Major Rock Edict XIII (found at Shahbazgarhi, Mansehra, Girnar, Kalsi, Erragudi) gives the harrowing account of the Kalinga War (261 BCE) and declares victory through Dhamma.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Which Harappan site is celebrated for its tripartite urban planning (Citadel, Middle Town, Lower Town) and a gigantic rainwater harvesting reservoir system cut into stone?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Dholavira (Khadir Bet, Rann of Kutch)',
        B: 'Rakhigarhi',
        C: 'Chanhudaro',
        D: 'Surkotada',
      },
      correctAnswer: 'A',
      explanation: 'Dholavira in Gujarat (excavated by R.S. Bisht) features a unique 3-tier town planning layout, massive rock-cut water reservoirs, and a large 10-symbol signboard.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Match List I (Ancient Mahajanapada) with List II (Capital City):\nList I:\n(a) Magadha\n(b) Kosala\n(c) Vatsa\n(d) Matsya\nList II:\n(1) Shravasti\n(2) Girivraja / Rajagriha\n(3) Viratnagar\n(4) Kausambi\nChoose the correct code:',
      questionType: 'Matching',
      options: {
        A: '(a)-(2), (b)-(1), (c)-(4), (d)-(3)',
        B: '(a)-(1), (b)-(2), (c)-(3), (d)-(4)',
        C: '(a)-(4), (b)-(3), (c)-(2), (d)-(1)',
        D: '(a)-(2), (b)-(4), (c)-(1), (d)-(3)',
      },
      correctAnswer: 'A',
      explanation: 'Magadha capital was Rajagriha/Girivraja; Kosala capital was Shravasti; Vatsa capital was Kausambi; Matsya capital was Viratnagar.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In Later Vedic society, which sacrificial ritual was performed by a king to establish undisputed imperial sovereignty by letting a consecrated horse roam freely for a year accompanied by warriors?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Rajasuya',
        B: 'Ashvamedha',
        C: 'Vajapeya (Chariot Race)',
        D: 'Agnishtoma',
      },
      correctAnswer: 'B',
      explanation: 'Ashvamedha (Horse Sacrifice) was the supreme Vedic imperial sacrifice establishing unquestioned territorial sovereignty over any territory the horse traversed unchallenged.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Which Greek ambassador visited the court of Chandragupta Maurya at Pataliputra and authored the ethnographical account "Indica"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Megasthenes (sent by Seleucus I Nicator)',
        B: 'Deimachus',
        C: 'Dionysius',
        D: 'Heliodorus',
      },
      correctAnswer: 'A',
      explanation: 'Megasthenes was the Seleucid ambassador to Chandragupta Maurya who described Pataliputra municipal administration, the 7 castes, and military boards in "Indica".',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'The celebrated "Junagarh Rock Inscription" (150 CE) recording the repair of the Sudarshana Lake dam is the earliest long epigraph written in chaste classical Sanskrit by which Shaka ruler?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Rudradaman I',
        B: 'Nahapana',
        C: 'Maues',
        D: 'Chashtana',
      },
      correctAnswer: 'A',
      explanation: 'The Junagarh Inscription of Western Kshatrapa ruler Rudradaman I (150 CE) is famous for its early pure Sanskrit prose and records waterworks by Chandragupta Maurya, Ashoka, and Rudradaman.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'The famous "Prayaga Prashasti" (Allahabad Pillar Inscription) celebrating the military conquests of Gupta Emperor Samudragupta was composed in Champu kavya style by his court poet:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Harishena',
        B: 'Virsen Saba',
        C: 'Kalidasa',
        D: 'Ravikirti',
      },
      correctAnswer: 'A',
      explanation: 'Harishena (Sandhivigrahika and Mahadandanayaka) composed the Prayag Prashasti on the Ashokan pillar in chaste Sanskrit depicting Samudragupta as "Kaviraja" and conqueror of Aryavarta and Dakshinapatha.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Which prehistoric archaeological site in the Kashmir valley is famous for Neolithic pit-dwellings, bone tools, and the unique burial of domestic dogs alongside masters?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Burzahom',
        B: 'Gufkral',
        C: 'Mehrgarh',
        D: 'Chirand',
      },
      correctAnswer: 'A',
      explanation: 'Burzahom near Srinagar (excavated by De Terra and Paterson) is celebrated for subterranean pit dwellings, polished bone harpoons, and dog burials.',
      difficulty: 'MEDIUM',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 2: FROM STATE TO EMPIRE (MAURYAS TO GUPTAS) (10 Questions: Q11 - Q20)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 2,
      questionText: 'In the Arthashastra of Kautilya, the "Saptanga Theory of State" (Seven Limbs) comprises which constituent elements?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Swami (King), Amatya (Ministers), Janapada (Territory/Population), Durga (Fort), Kosha (Treasury), Danda (Army), Mitra (Allies)',
        B: 'King, Priests, Merchants, Artisans, Farmers, Serfs, Slaves',
        C: 'Executive, Legislature, Judiciary, Army, Police, Bureaucracy, Citizenry',
        D: 'Dharma, Artha, Kama, Moksha, Varna, Ashrama, Samskara',
      },
      correctAnswer: 'A',
      explanation: 'Kautilya\'s Saptanga theory (Arthashastra VI.1) outlines the organic state: Swami (Ruler), Amatya (Bureaucrats), Janapada (Land & people), Durga (Fortress), Kosha (Treasury), Danda (Force), and Mitra (Allies).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'Under the Satavahana dynasty, the earliest epigraphical evidence of tax-free land grants (Bramhadeya / Agrahara) to Buddhist monks and Brahmans is recorded in which inscription?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Nanaghat Inscription of Queen Nayanika (Naganika)',
        B: 'Nasik Prasasti of Gautami Balashri',
        C: 'Karle Cave Inscription',
        D: 'Hathigumpha Inscription of Kharavela',
      },
      correctAnswer: 'A',
      explanation: 'The Nanaghat Inscription of Queen Nayanika (1st century BCE) records the earliest epigraphic grant of villages and land exemptions to religious beneficiaries in Indian history.',
      difficulty: 'HARD',
    },
    {
      unitNumber: 2,
      questionText: 'Which Chinese Buddhist pilgrim visited India during the reign of Emperor Harsha (Vardhana dynasty) and documented the grand assemblies at Kannauj and Prayaga in his travelogue "Si-Yu-Ki"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Xuanzang (Hiuen Tsang)',
        B: 'Faxian (Fa-Hien)',
        C: 'Yijing (I-Tsing)',
        D: 'Song Yun',
      },
      correctAnswer: 'A',
      explanation: 'Xuanzang visited Harsha\'s realm (629-645 CE), studied at Nalanda under Shilabhadra, and described the Kannauj religious assembly and the quinquennial Maha Moksha Parishad at Prayag.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'The Aihole Inscription (634 CE) composed in Sanskrit by court poet Ravikirti celebrates the decisive military victory of Pulakeshin II (Chalukyas of Badami) over which north Indian emperor on the banks of Narmada?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Harshavardhana',
        B: 'Devagupta',
        C: 'Shashanka of Gauda',
        D: 'Grahavarman',
      },
      correctAnswer: 'A',
      explanation: 'The Aihole Meguti temple inscription records that Harsha ("whose joy melted away in fear") was defeated by Chalukya king Pulakeshin II at the Narmada frontier.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In ancient Tamil Sangam literature, the landscape and emotional poetry is categorized into five ecological zones (Aintinai). Match List I (Tinai) with List II (Landscape/Mood):\nList I:\n(a) Kurinji\n(b) Mullai\n(c) Marutam\n(d) Neytal\nList II:\n(1) Pastoral / Forest (Patient waiting)\n(2) Mountainous (Lovers\' clandestine union)\n(3) Coastal / Seashore (Anxious pining)\n(4) Agricultural river plains (Wifely sulking / infidelity)\nChoose the correct code:',
      questionType: 'Matching',
      options: {
        A: '(a)-(2), (b)-(1), (c)-(4), (d)-(3)',
        B: '(a)-(1), (b)-(2), (c)-(3), (d)-(4)',
        C: '(a)-(4), (b)-(3), (c)-(2), (d)-(1)',
        D: '(a)-(3), (b)-(4), (c)-(1), (d)-(2)',
      },
      correctAnswer: 'A',
      explanation: 'Kurinji = Hills/Lovers\' union; Mullai = Pastoral/Waiting; Marutam = Agrarian/Sulking; Neytal = Coast/Pining; Palai = Arid desert/Separation.',
      difficulty: 'HARD',
    },
    {
      unitNumber: 2,
      questionText: 'Which Kushana emperor convened the Fourth Buddhist Council at Kundalavana in Kashmir, which resulted in the formal division of Buddhism into Hinayana and Mahayana?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Kanishka I',
        B: 'Kujula Kadphises',
        C: 'Vima Kadphises',
        D: 'Huvishka',
      },
      correctAnswer: 'A',
      explanation: 'Kanishka I (circa 78 CE) patronized the Fourth Buddhist Council presided over by Vasumitra and Ashvaghosha where the Mahavibhasha commentaries were inscribed on copper plates.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'The celebrated iron pillar located at Mehrauli (Qutb complex, Delhi), famous for its rust-resistant metallurgy, bears an inscription eulogizing the military victories of a king named:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Chandra (identified with Chandragupta II Vikramaditya)',
        B: 'Chandragupta Maurya',
        C: 'Samudragupta',
        D: 'Skandagupta',
      },
      correctAnswer: 'A',
      explanation: 'The 4th-century Mehrauli Iron Pillar inscription commemorates King "Chandra", universally identified with Gupta Emperor Chandragupta II Vikramaditya who defeated the Vahlikas across the Indus.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'In Chola administration, the autonomous local self-governing assembly of a tax-free Brahman village (Brahmadeya) was known as the:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Sabha / Mahasabha',
        B: 'Ur (general village assembly)',
        C: 'Nagaram (merchant assembly)',
        D: 'Nadu (district council)',
      },
      correctAnswer: 'A',
      explanation: 'The Uttaramerur Inscriptions of Parantaka I (919 & 921 CE) provide vivid details of the Sabha / Mahasabha, including its Kudavolai (pot-ticket) lottery committee election system (Variyams).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'Which classical Indian astronomer and mathematician authored the "Aryabhatiya" and "Surya Siddhanta", proposing that the Earth is spherical and rotates on its own axis?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Aryabhata I (499 CE)',
        B: 'Varahamihira (author of Brihat Samhita)',
        C: 'Brahmagupta',
        D: 'Bhaskaracharya I',
      },
      correctAnswer: 'A',
      explanation: 'Aryabhata I of Pataliputra stated that day and night are caused by the diurnal rotation of the spherical earth, calculated $\\pi \\approx 3.1416$, and gave scientific explanations of solar and lunar eclipses.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'Which Gupta ruler assumed the title "Kaviraja", issued gold coins depicting himself playing the Veena (lute), and performed the Ashvamedha sacrifice after conquering Aryavarta?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Samudragupta',
        B: 'Chandragupta I',
        C: 'Kumaragupta I',
        D: 'Buddhagupta',
      },
      correctAnswer: 'A',
      explanation: 'Samudragupta issued the Veena-player type gold dinars and the Ashvamedha-type gold coins commemorating his cultural brilliance and imperial conquests.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 3: EARLY MEDIEVAL INDIA TO SULTANATE (10 Questions: Q21 - Q30)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 3,
      questionText: 'The Tripartite Struggle for paramount control over Kannauj and the fertile Gangetic plains in the 8th to 10th centuries involved which three major imperial dynasties?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Gurjara-Pratiharas, Palas, and Rashtrakutas',
        B: 'Cholas, Cheras, and Pandyas',
        C: 'Chalukyas, Pallavas, and Kadambas',
        D: 'Delhi Sultanate, Yadavas, and Kakatiyas',
      },
      correctAnswer: 'A',
      explanation: 'The Gurjara-Pratiharas of Western India, the Palas of Bengal and Bihar, and the Rashtrakutas of Deccan fought a protracted two-century tripartite struggle for control of Kannauj.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'Which Chola monarch assumed the proud title "Gangaikondachola" (Conqueror of the Ganga) and founded the new imperial capital Gangaikondacholapuram with a massive temple and reservoir (Cholagangam)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Rajendra Chola I',
        B: 'Rajaraja Chola I (builder of Brihadisvara)',
        C: 'Kulottunga I',
        D: 'Parantaka I',
      },
      correctAnswer: 'A',
      explanation: 'Rajendra I (1014-1044 CE) led a victorious expedition to the river Ganga in Bengal (defeating Mahipala I) and launched a naval campaign conquering the Srivijaya maritime empire in Southeast Asia.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'The celebrated monolithic rock-cut Kailashanatha Temple at Ellora (Cave 16), carved entirely from top to bottom out of a single basalt cliff, was constructed under which Rashtrakuta king?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Krishna I (756-774 CE)',
        B: 'Dantidurga',
        C: 'Amoghavarsha I',
        D: 'Govinda III',
      },
      correctAnswer: 'A',
      explanation: 'The monolithic Kailash temple at Ellora was excavated under Rashtrakuta king Krishna I and is recognized as one of the greatest architectural feats of ancient world rock-cut engineering.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'Which Persian scholar and polymath accompanied Sultan Mahmud of Ghazni to India and composed the encyclopedic masterwork "Kitab fi Tahqiq ma li\'l-Hind" (Tarikh al-Hind)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Abu Rayhan al-Biruni',
        B: 'Utbi (author of Tarikh-i Yamini)',
        C: 'Firdausi (author of Shahnama)',
        D: 'Minhaj-i Siraj',
      },
      correctAnswer: 'A',
      explanation: 'Al-Biruni spent years studying Sanskrit texts, Indian astronomy, mathematics, philosophy, religion, and caste society, producing the scholarly "Tarikh al-Hind" (circa 1030 CE).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'Who was the founder of the Delhi Sultanate (Mamluk / Slave Dynasty) in 1206 CE, who earned the epithet "Lakhbaksh" (Giver of Lakhs) for his immense generosity and commenced the construction of the Qutb Minar?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Qutbuddin Aibak',
        B: 'Shamsuddin Iltutmish',
        C: 'Ghiyasuddin Balban',
        D: 'Muizzuddin Muhammad Ghori',
      },
      correctAnswer: 'A',
      explanation: 'Qutbuddin Aibak established the Mamluk dynasty at Lahore/Delhi in 1206 CE, built the Quwwat-ul-Islam mosque, and started building the Qutb Minar dedicated to Sufi saint Qutbuddin Bakhtiyar Kaki.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'Which Delhi Sultan organized the corps of forty Turkish slave-nobles known as the "Turkan-i-Chahalgani" (The Forty) and introduced the silver "Tanka" and copper "Jital" coins?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Shamsuddin Iltutmish',
        B: 'Qutbuddin Aibak',
        C: 'Raziya Sultan',
        D: 'Alauddin Khalji',
      },
      correctAnswer: 'A',
      explanation: 'Iltutmish (1211-1236 CE) consolidated the Delhi Sultanate, secured investiture (Manshur) from the Abbasid Caliph of Baghdad, instituted the Iqta system, and formed the Chahalgani.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'Who was the only female Muslim sovereign to sit on the throne of the Delhi Sultanate, nominated by her father Iltutmish despite opposition from orthodox nobles?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Raziya Sultan (1236-1240 CE)',
        B: 'Nur Jahan',
        C: 'Chand Bibi',
        D: 'Gulbadan Begum',
      },
      correctAnswer: 'A',
      explanation: 'Jalalut-ud-Din Raziya (Raziya al-Din) governed Delhi from 1236 to 1240 CE, discarding purdah, holding open court, and leading armies.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'Sultan Ghiyasuddin Balban consolidated royal absolutism in the Delhi Sultanate through his "Blood and Iron" policy and introduced which Persian court rituals to demonstrate imperial majesty?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Sijda (prostration) and Paibos (kissing the monarch\'s feet)',
        B: 'Jharokha Darshan and Tuladan',
        C: 'Zakat and Jizya audits',
        D: 'Mansabdari reviews',
      },
      correctAnswer: 'A',
      explanation: 'Balban claimed descent from the mythical hero Afrasiyab, asserted that the Sultan is Niyabat-i-Khudai (Vicegerent of God) and Zil-i-Ilahi (Shadow of God), and enforced Sijda, Paibos, and the Nauroz festival.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'Which Delhi Sultan implemented comprehensive market control regulations (Shahna-i-Mandi, Diwan-i-Riyasat), fixed commodity prices, and instituted the "Dagh" (horse-branding) and "Chehra" (soldier descriptive rolls)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Alauddin Khalji',
        B: 'Jalaluddin Khalji',
        C: 'Muhammad bin Tughlaq',
        D: 'Firuz Shah Tughlaq',
      },
      correctAnswer: 'A',
      explanation: 'Alauddin Khalji (1296-1316 CE) created a strictly regulated price control system in Delhi, measured agricultural land (Zabita/Biswa), and maintained a massive standing army to repel Mongol invasions.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'Which Moroccan traveler visited India during the reign of Muhammad bin Tughlaq, served as Qazi of Delhi for eight years, and authored the travelogue "Rihla"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Ibn Battuta (Abu Abdullah Muhammad)',
        B: 'Al-Masudi',
        C: 'Nicolo Conti',
        D: 'Abdur Razzaq Samarqandi',
      },
      correctAnswer: 'A',
      explanation: 'Ibn Battuta reached Delhi in 1333 CE, was appointed Qazi by Muhammad bin Tughlaq, later served as ambassador to China, and penned his memoirs in the "Rihla" (Tuhfat al-Nuzzar).',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 4: THE MUGHAL EMPIRE & REGIONAL POWERS (10 Questions: Q31 - Q40)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 4,
      questionText: 'In the First Battle of Panipat (21 April 1526), Zahiruddin Muhammad Babur defeated Ibrahim Lodi through the superior tactical deployment of artillery and which Central Asian military formation?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Tulughma (flanking wheel) and Araba (wagon line)',
        B: 'Guerrilla Ganimi Kava',
        C: 'Phalanx heavy infantry',
        D: 'Elephant shock charge',
      },
      correctAnswer: 'A',
      explanation: 'Babur effectively deployed matchlocks, cannons under Ustad Ali and Mustafa, and the Tulughma flanking strategy tied with chained carts (Rumi system) to shatter Lodi\'s larger army.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'Which Sur dynasty ruler introduced the silver "Rupiya" (standardized at 178 grains), built the Grand Trunk Road (Sadak-i-Azam from Sonargaon to Attock), and created an efficient revenue assessment system based on Jarib measurement?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Sher Shah Suri (Farid Khan)',
        B: 'Islam Shah Suri',
        C: 'Adil Shah Suri',
        D: 'Hemu Vikramaditya',
      },
      correctAnswer: 'A',
      explanation: 'Sher Shah Suri (1540-1545 CE) established the tripartite currency (Rupiya, Mohur, Dam), constructed highway Sarai network, reformed customs, and laid administrative foundations later perfected by Akbar.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'Under Mughal Emperor Akbar, the revenue minister Raja Todar Mal introduced which land revenue system based on 10-year average yield and price calculations?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Ain-i Dahsala / Zabti System (1580 CE)',
        B: 'Batai / Ghalla-Bakshi',
        C: 'Nasaq / Kankut',
        D: 'Ryotwari',
      },
      correctAnswer: 'A',
      explanation: 'The Dahsala system (1580 CE) classified agricultural land into Polaj (annually cultivated), Parauti (fallow for 1-2 years), Chachar (fallow 3-4 years), and Banjar (uncultivated for 5+ years) with fixed cash rates.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'In the Mughal administrative framework, what did the dual ranks "Zat" and "Sawar" represent in the Mansabdari system?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Zat determined personal status, seniority, and base salary; Sawar determined the number of horsemen the mansabdar was required to maintain',
        B: 'Zat was cavalry rank; Sawar was infantry rank',
        C: 'Zat was civil revenue rank; Sawar was judicial court rank',
        D: 'Zat indicated noble birth; Sawar indicated religious title',
      },
      correctAnswer: 'A',
      explanation: 'Akbar introduced the dual rank: Zat fixed the mansabdar\'s personal position and pay scale in the court hierarchy, while Sawar specified the cavalry contingent (horses and troopers) required for state duty.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'In 1575 CE, Akbar constructed the "Ibadat Khana" (House of Worship) at Fatehpur Sikri for theological discussions, and later promulgated the ethical-spiritual code known as:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Tauhid-i-Ilahi / Din-i-Ilahi (1582 CE)',
        B: 'Sulh-i-Kul legal statute',
        C: 'Mahzar decree of 1579',
        D: 'Dara Shikoh Academy',
      },
      correctAnswer: 'A',
      explanation: 'Akbar established the Ibadat Khana to dialogue with Muslim, Hindu, Jain, Parsi, and Christian scholars, culminating in the ethos of universal peace (Sulh-i-Kul) and the syncretic fellowship Din-i-Ilahi.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'Which Sikh Guru was martyred at Chandni Chowk, Delhi in 1675 CE under the orders of Aurangzeb for resisting forced religious persecutions and defending Kashmiri Pandits?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Guru Tegh Bahadur (Ninth Guru)',
        B: 'Guru Arjan Dev (Fifth Guru, martyred under Jahangir)',
        C: 'Guru Gobind Singh (Tenth Guru)',
        D: 'Guru Har Gobind',
      },
      correctAnswer: 'A',
      explanation: 'Guru Tegh Bahadur, the 9th Sikh Guru, was executed at Delhi in 1675 CE where Gurdwara Sis Ganj Sahib stands today.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'Chhatrapati Shivaji Maharaj was formally crowned as Chhatrapati of the independent Maratha Kingdom in 1674 CE at which hill fortress?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Raigad (coronation conducted by Pandit Gaga Bhatt)',
        B: 'Torna',
        C: 'Shivneri',
        D: 'Sinhagad',
      },
      correctAnswer: 'A',
      explanation: 'Shivaji\'s royal coronation (Rajyabhisheka) took place on 6 June 1674 at Raigad Fort, where he assumed the titles of Chhatrapati and Haindava Dharmoddharak.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'In Maratha administration, the council of eight prominent ministers assisting the Chhatrapati was known as the:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Ashtapradhan',
        B: 'Ashtadiggajas (Vijayanagara Telugu literature)',
        C: 'Navaratnas',
        D: 'Panchayat Samiti',
      },
      correctAnswer: 'A',
      explanation: 'Shivaji\'s Ashtapradhan council consisted of: Peshwa (Prime Minister), Amatya (Finance), Sachiv (Secretary), Mantri (Interior), Senapati (Commander), Sumant (Foreign Affairs), Nyayadhish (Chief Justice), and Panditrao (Charities).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'The revenue levy of "Chauth" collected by the Marathas in neighbouring non-Maratha territories amounted to what fraction of the standard land revenue assessment?',
      questionType: 'Direct MCQ',
      options: {
        A: 'One-fourth ($25\\%$)',
        B: 'One-tenth ($10\\%$, Sardeshmukhi)',
        C: 'One-third ($33\\%$)',
        D: 'One-half ($50\\%$)',
      },
      correctAnswer: 'A',
      explanation: 'Chauth was a 25% (one-fourth) levy collected to protect the region from plunder and external aggression, whereas Sardeshmukhi was an additional 10% hereditary claim.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'Which Persian monarch invaded Mughal India in 1739 CE during the reign of Muhammad Shah Rangeela, defeated the Mughal army at Karnal, and carried away the Koh-i-Noor diamond and the Peacock Throne (Takht-i Taus)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Nadir Shah',
        B: 'Ahmad Shah Abdali',
        C: 'Shah Abbas I',
        D: 'Zaman Shah',
      },
      correctAnswer: 'A',
      explanation: 'Nadir Shah sacked Delhi in March 1739, plundered royal treasures including Shah Jahan\'s jewelled Peacock Throne and the Koh-i-Noor, dealing a fatal blow to Mughal authority.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 5: COLONIAL EXPANSION & ECONOMIC IMPACT (10 Questions: Q41 - Q50)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 5,
      questionText: 'The Battle of Plassey (23 June 1757), which laid the foundation of British territorial dominion in India, was fought between the British East India Company forces led by Robert Clive and the Nawab of Bengal named:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Siraj-ud-Daulah',
        B: 'Mir Jafar',
        C: 'Mir Qasim',
        D: 'Alivardi Khan',
      },
      correctAnswer: 'A',
      explanation: 'Siraj-ud-Daulah was betrayed by his commander-in-chief Mir Jafar, Rai Durlabh, and banker Jagat Seth at Plassey, enabling Robert Clive\'s decisive victory.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'Following the decisive British victory at the Battle of Buxar (1764), the Treaty of Allahabad (August 1765) granted the "Diwani Rights" (civil revenue collection) of Bengal, Bihar, and Orissa to the East India Company by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Mughal Emperor Shah Alam II',
        B: 'Nawab Shuja-ud-Daula of Awadh',
        C: 'Mir Qasim',
        D: 'Bahadur Shah I',
      },
      correctAnswer: 'A',
      explanation: 'Robert Clive concluded the Treaty of Allahabad with titular Mughal Emperor Shah Alam II, who granted the perpetual Diwani of Bengal, Bihar, and Orissa in exchange for an annual tribute of 26 lakh rupees.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'The "Permanent Settlement" (Istamarari Bandobast) of Bengal, Bihar, and Orissa, which recognized Zamindars as absolute hereditary owners of land with a fixed revenue demand (10/11th to state, 1/11th to zamindar), was introduced in 1793 by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Lord Cornwallis (with Sir John Shore)',
        B: 'Warren Hastings',
        C: 'Lord Wellesley',
        D: 'Lord William Bentinck',
      },
      correctAnswer: 'A',
      explanation: 'Lord Cornwallis enacted the Permanent Settlement of 1793, establishing fixed state revenue demands in perpetuity and introducing the stringent "Sunset Law".',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'The "Ryotwari System" of land revenue, wherein the British state established direct settlement with individual peasant cultivators (Ryots) without intermediary zamindars, was formulated in the Madras and Bombay Presidencies by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Thomas Munro and Alexander Read',
        B: 'Holt Mackenzie and Robert Merttins Bird (Mahalwari)',
        C: 'Lord Dalhousie',
        D: 'Lord Curzon',
      },
      correctAnswer: 'A',
      explanation: 'Captain Alexander Read and Sir Thomas Munro introduced the Ryotwari system in Baramahal and Madras Presidency, assessing land revenue directly on peasant plots.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'The political strategy of the "Subsidiary Alliance" (under which Indian rulers surrendered foreign relations, maintained a British military subsidiary force, and accepted a British Resident) was aggressively expanded by Governor-General:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Lord Wellesley (1798-1805)',
        B: 'Lord Dalhousie',
        C: 'Lord Hastings',
        D: 'Lord Ellenborough',
      },
      correctAnswer: 'A',
      explanation: 'Lord Wellesley utilized the Subsidiary Alliance system, compelling the Nizam of Hyderabad (1798), the Nawab of Awadh (1801), and the Peshwa (Treaty of Bassein 1802) to surrender sovereign military autonomy.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'Under the imperialistic "Doctrine of Lapse" enforced by Lord Dalhousie, which princely state was annexed FIRST in 1848 upon the death of its ruler without a biological male heir?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Satara',
        B: 'Jhansi (1853)',
        C: 'Nagpur (1854)',
        D: 'Sambalpur (1849)',
      },
      correctAnswer: 'A',
      explanation: 'Satara was the first state annexed under the Doctrine of Lapse in 1848, followed by Jaitpur and Sambalpur (1849), Baghat (1850), Udaipur (1852), Jhansi (1853), and Nagpur (1854).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'Who was the pioneering nationalist economic thinker who formulated the "Drain of Wealth Theory" in his monumental work "Poverty and Un-British Rule in India"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Dadabhai Naoroji (Grand Old Man of India)',
        B: 'Romesh Chunder Dutt (author of Economic History of India)',
        C: 'Mahadev Govind Ranade',
        D: 'Gopal Krishna Gokhale',
      },
      correctAnswer: 'A',
      explanation: 'Dadabhai Naoroji demonstrated how Indian wealth was drained to Britain without adequate economic return via home charges, remittances, pensions, and imperial trade surpluses.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'The Sepoy Mutiny and Great Uprising of 1857 was ignited at Barrackpore on 29 March 1857 by a sepoy of the 34th Bengal Native Infantry named:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Mangal Pandey',
        B: 'Bakht Khan',
        C: 'Nana Saheb',
        D: 'Kunwar Singh',
      },
      correctAnswer: 'A',
      explanation: 'Mangal Pandey revolted against the grease-cartridge Enfield rifles at Barrackpore military cantonment and assaulted British officers.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'Match List I (1857 Uprising Leader) with List II (Main Centre of Revolt):\nList I:\n(a) Begum Hazrat Mahal\n(b) Kunwar Singh\n(c) Nana Saheb and Tatya Tope\n(d) Maulvi Ahmadullah\nList II:\n(1) Kanpur\n(2) Lucknow / Awadh\n(3) Faizabad\n(4) Jagdishpur / Arrah (Bihar)\nChoose the correct code:',
      questionType: 'Matching',
      options: {
        A: '(a)-(2), (b)-(4), (c)-(1), (d)-(3)',
        B: '(a)-(1), (b)-(2), (c)-(3), (d)-(4)',
        C: '(a)-(4), (b)-(3), (c)-(2), (d)-(1)',
        D: '(a)-(3), (b)-(4), (c)-(1), (d)-(2)',
      },
      correctAnswer: 'A',
      explanation: 'Begum Hazrat Mahal led Lucknow; Kunwar Singh led Jagdishpur (Bihar); Nana Saheb and Tatya Tope led Kanpur; Maulvi Ahmadullah led Faizabad.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'The "Government of India Act 1858" (Act for the Better Government of India) transferred the governance of India from the British East India Company to:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The British Crown (Queen Victoria) through the Secretary of State for India and Council of India',
        B: 'The British Indian Association',
        C: 'The Governor of Bengal as absolute sovereign',
        D: 'The Federal Court of Calcutta',
      },
      correctAnswer: 'A',
      explanation: 'The Act of 1858 abolished the Company rule and the Board of Control, placing India directly under the British Crown with Lord Canning becoming the first Viceroy.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 6: SOCIO-RELIGIOUS REFORMS & FREEDOM MOVEMENT (10 Questions: Q51 - Q60)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 6,
      questionText: 'Who is recognized as the "Father of the Modern Indian Renaissance", who founded the Brahmo Sabha (later Brahmo Samaj) in 1828 and campaigned vigorously against Sati?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Raja Ram Mohan Roy',
        B: 'Debendranath Tagore',
        C: 'Keshab Chandra Sen',
        D: 'Ishwar Chandra Vidyasagar',
      },
      correctAnswer: 'A',
      explanation: 'Raja Ram Mohan Roy advocated monotheism, rationalism, modern education, and freedom of the press, leading to Lord William Bentinck\'s abolition of Sati in 1829.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'Which social reformer founded the "Satyashodhak Samaj" (Truth-Seekers\' Society) in Pune in 1873 and authored the radical anti-caste polemic "Gulamgiri" (Slavery)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Jyotirao Phule (Mahatma Phule)',
        B: 'B.R. Ambedkar',
        C: 'Periyar E.V. Ramasamy',
        D: 'Gopal Hari Deshmukh (Lokahitawadi)',
      },
      correctAnswer: 'A',
      explanation: 'Jyotirao Govindrao Phule pioneered women\'s and lower-caste education in Maharashtra, founded the Satyashodhak Samaj, and dedicated "Gulamgiri" to the American abolitionist movement.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'The Arya Samaj was established in Bombay in 1875 with the rallying slogan "Back to the Vedas" (Vedo ki Aur Lauto) by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Swami Dayananda Saraswati (Mula Shankara)',
        B: 'Swami Vivekananda',
        C: 'Ramakrishna Paramahamsa',
        D: 'Swami Shraddhanand',
      },
      correctAnswer: 'A',
      explanation: 'Swami Dayananda Saraswati authored "Satyarth Prakash", condemned idol worship and hereditary caste rigidity, and promoted Vedic education and the Shuddhi movement.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'The Indian National Congress (INC) was established in December 1885 in Bombay at Gokuldas Tejpal Sanskrit College under the initial presidency of:',
      questionType: 'Direct MCQ',
      options: {
        A: 'W.C. Bonnerjee (Womesh Chandra Bonnerjee)',
        B: 'Allan Octavian Hume (General Secretary)',
        C: 'Dadabhai Naoroji',
        D: 'Dinshaw Wacha',
      },
      correctAnswer: 'A',
      explanation: 'The first session of the INC was held on 28-31 December 1885 with 72 delegates, presided over by barrister Womesh Chandra Bonnerjee.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'The Partition of Bengal announced by Viceroy Lord Curzon in 1905 triggered which nationwide mass nationalist upsurge characterized by Boycott and Vande Mataram?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Swadeshi and Boycott Movement',
        B: 'Non-Cooperation Movement',
        C: 'Civil Disobedience Movement',
        D: 'Quit India Movement',
      },
      correctAnswer: 'A',
      explanation: 'The Swadeshi Movement (1905-1908) promoted indigenous industries, national education institutions, boycott of British foreign goods, and popularized the slogan Vande Mataram.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'The historic "Surat Split" of the Indian National Congress in 1907 occurred due to severe ideological clashes between Moderates and Extremists under the presidency of:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Rash Behari Ghosh',
        B: 'Gopal Krishna Gokhale',
        C: 'Bal Gangadhar Tilak',
        D: 'Lala Lajpat Rai',
      },
      correctAnswer: 'A',
      explanation: 'The Surat Congress session (1907) broke down into open conflict over extending the Swadeshi and boycott movement across India, leading to the expulsion of Extremists (Lal-Bal-Pal).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 6,
      questionText: 'Mahatma Gandhi\'s first successful experiment with Satyagraha on Indian soil in 1917 was launched in which region to liberate farmers from the oppressive European indigo planters\' Tinkathia system?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Champaran (Bihar)',
        B: 'Kheda (Gujarat)',
        C: 'Ahmedabad Mill Strike',
        D: 'Bardoli Satyagraha',
      },
      correctAnswer: 'A',
      explanation: 'Persuaded by Rajkumar Shukla, Gandhi visited Champaran in 1917, defied British district magistrate eviction orders, and successfully abolished the Tinkathia system forcing indigo cultivation.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'The brutal Jallianwala Bagh Massacre took place on 13 April 1919 (Baisakhi Day) in Amritsar when British troops opened fire on peaceful demonstrators under the orders of:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Brigadier-General Reginald Dyer',
        B: 'Sir Michael O\'Dwyer (Lieutenant Governor of Punjab)',
        C: 'Lord Chelmsford',
        D: 'General Kitchener',
      },
      correctAnswer: 'A',
      explanation: 'General Dyer blocked the narrow entrance of Jallianwala Bagh and ordered unprovoked firing on a gathered crowd protesting the arrest of Dr. Saifuddin Kitchlew and Dr. Satyapal under the Rowlatt Act.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'The Non-Cooperation Movement (1920-1922) was abruptly called off by Mahatma Gandhi in February 1922 following a violent incident in which a mob burned a police station in:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Chauri Chaura (Gorakhpur, UP)',
        B: 'Kakori',
        C: 'Meerut',
        D: 'Kheda',
      },
      correctAnswer: 'A',
      explanation: 'On 4-5 February 1922 at Chauri Chaura, protestors set fire to a police chowki killing 22 policemen, leading Gandhi to halt the movement to preserve non-violence.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'The historic "Purna Swaraj" (Complete Independence) resolution was adopted by the Indian National Congress in December 1929 at its Lahore session presided over by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Jawaharlal Nehru',
        B: 'Motilal Nehru',
        C: 'Subhash Chandra Bose',
        D: 'Sardar Vallabhbhai Patel',
      },
      correctAnswer: 'A',
      explanation: 'The Lahore Congress (1929) under Jawaharlal Nehru unfurled the tricolour flag on the banks of Ravi and resolved that 26 January 1930 be celebrated as Independence Day (Purna Swaraj Day).',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 7: MASS MOVEMENTS & REVOLUTIONARY NATIONALISM (10 Questions: Q61 - Q70)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 7,
      questionText: 'Mahatma Gandhi launched the Civil Disobedience Movement on 12 March 1930 by undertaking the 241-mile Dandi March from Sabarmati Ashram to break the:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Salt Law (Dandi Salt Satyagraha)',
        B: 'Forest Grazing Laws',
        C: 'Land Tax Assessment',
        D: 'Foreign Cloth Import Tariffs',
      },
      correctAnswer: 'A',
      explanation: 'Gandhi reached the seashore at Dandi on 6 April 1930 and picked up a fistful of natural salt, breaking the British state salt monopoly and triggering nationwide civil disobedience.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'The "Poona Pact" of September 1932 was signed between Dr. B.R. Ambedkar and Mahatma Gandhi (represented by Madan Mohan Malaviya) following Gandhi\'s fast unto death against the:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Communal Award of Ramsay MacDonald granting separate electorates to Depressed Classes',
        B: 'Simon Commission Recommendations',
        C: 'Government of India Act 1935',
        D: 'Wavell Plan',
      },
      correctAnswer: 'A',
      explanation: 'The Poona Pact replaced separate electorates for Depressed Classes with reserved seats within general constituencies, increasing reserved legislative seats from 71 to 148.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 7,
      questionText: 'The revolutionary youth organization "Hindustan Socialist Republican Association" (HSRA) was reorganized at Feroz Shah Kotla, Delhi in September 1928 by Bhagat Singh, Sukhdev, and:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Chandrashekhar Azad',
        B: 'Ram Prasad Bismil',
        C: 'Sachindra Nath Sanyal',
        D: 'Surya Sen',
      },
      correctAnswer: 'A',
      explanation: 'Under Chandrashekhar Azad, Bhagat Singh, and Sukhdev, the HRA was re-christened the HSRA to formally embrace democratic socialism as its guiding ideology.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 7,
      questionText: 'Who led the daring "Chittagong Armoury Raid" on 18 April 1930 under the banner of the Indian Republican Army (Chittagong Branch)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Surya Sen (Masterda)',
        B: 'Pritilata Waddedar',
        C: 'Kalpana Datta',
        D: 'Jatin Das',
      },
      correctAnswer: 'A',
      explanation: 'Surya Sen (Masterda) planned and executed the simultaneous raids on the British police and auxiliary armouries in Chittagong, proclaiming a provisional revolutionary government.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'On 8 August 1942 at the Gowalia Tank Maidan in Bombay, the All India Congress Committee passed the historic "Quit India Resolution", where Mahatma Gandhi gave the immortal call of:',
      questionType: 'Direct MCQ',
      options: {
        A: '"Do or Die" (Karo ya Maro)',
        B: '"Jai Hind"',
        C: '"Inquilab Zindabad"',
        D: '"Dilli Chalo"',
      },
      correctAnswer: 'A',
      explanation: 'Gandhi delivered his famous speech: "We shall either free India or die in the attempt; we shall not live to see the perpetuation of our slavery."',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'Netaji Subhash Chandra Bose revived and commanded the "Indian National Army" (Azad Hind Fauj) and established the Provisional Government of Free India (Arzi Hukumat-e-Azad Hind) in 1943 at:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Singapore',
        B: 'Tokyo',
        C: 'Bangkok',
        D: 'Rangoon',
      },
      correctAnswer: 'A',
      explanation: 'Netaji proclaimed the Provisional Government of Azad Hind in Singapore on 21 October 1943, creating regiments named Gandhi, Nehru, Azad, and the Rani of Jhansi women\'s regiment.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'The historic "INA Trials" (Red Fort Trials) of 1945-46 against Prem Sahgal, Gurbaksh Singh Dhillon, and Shahnawaz Khan were defended by a legal team led by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Bhulabhai Desai, Tej Bahadur Sapru, and Jawaharlal Nehru',
        B: 'Muhammad Ali Jinnah',
        C: 'B.R. Ambedkar',
        D: 'C. Rajagopalachari',
      },
      correctAnswer: 'A',
      explanation: 'The INA Defence Committee organized by the Congress was headed by Bhulabhai Desai, Sir Tej Bahadur Sapru, K.N. Katju, Asaf Ali, and Jawaharlal Nehru.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 7,
      questionText: 'The Royal Indian Navy (RIN) Revolt broke out in February 1946 on the naval ratings training ship named:',
      questionType: 'Direct MCQ',
      options: {
        A: 'HMIS Talwar (Bombay)',
        B: 'HMIS Vikrant',
        C: 'HMIS Godavari',
        D: 'HMIS Hindustan',
      },
      correctAnswer: 'A',
      explanation: 'On 18 February 1946, ratings of HMIS Talwar mutinied against racial discrimination, unpalatable food, and imperial abuse, spreading to 78 ships across Bombay, Karachi, and Calcutta.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'The "Cabinet Mission Plan" sent to India in March 1946 to negotiate constitutional transfer of power comprised which three British Cabinet Ministers?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Lord Pethick-Lawrence, Sir Stafford Cripps, and A.V. Alexander',
        B: 'Lord Mountbatten, Clement Attlee, and Winston Churchill',
        C: 'Lord Wavell, John Simon, and Lord Linlithgow',
        D: 'Lord Curzon, Lord Minto, and Lord Morley',
      },
      correctAnswer: 'A',
      explanation: 'The Cabinet Mission (Pethick-Lawrence, Stafford Cripps, and A.V. Alexander) proposed an undivided Indian federation, grouping of provinces (Groups A, B, C), and the Constituent Assembly.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'Under the "Mountbatten Plan" (3 June 1947 Plan), the boundary demarcation between India and Pakistan in Punjab and Bengal was assigned to boundary commissions chaired by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Sir Cyril Radcliffe',
        B: 'Sir Stafford Cripps',
        C: 'Sir John Simon',
        D: 'Lord Curzon',
      },
      correctAnswer: 'A',
      explanation: 'Sir Cyril Radcliffe headed the Punjab and Bengal Boundary Commissions which delineated the Radcliffe Line partitioning the subcontinent.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 8: POST-INDEPENDENCE NATION BUILDING (10 Questions: Q71 - Q80)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 8,
      questionText: 'Who served as India\'s Deputy Prime Minister and Minister of Home and States, orchestrating the integration of over 565 princely states into the Indian Union with V.P. Menon?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Sardar Vallabhbhai Patel (Iron Man of India)',
        B: 'Jawaharlal Nehru',
        C: 'Dr. B.R. Ambedkar',
        D: 'C. Rajagopalachari',
      },
      correctAnswer: 'A',
      explanation: 'Sardar Patel utilized diplomatic skill, the Instrument of Accession, and decisive action in Junagadh, Hyderabad (Operation Polo), and Kashmir to unify India.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'The States Reorganisation Commission (SRC) appointed by the Government of India in 1953 to examine linguistic reorganization of states was chaired by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Justice Fazal Ali (with K.M. Panikkar and H.N. Kunzru)',
        B: 'Justice S.K. Dhar (Dhar Commission 1948)',
        C: 'Pattabhi Sitaramayya (JVP Committee)',
        D: 'Dr. B.R. Ambedkar',
      },
      correctAnswer: 'A',
      explanation: 'The Fazal Ali Commission submitted its report in 1955, leading to the States Reorganisation Act 1956 creating 14 states and 6 union territories based primarily on linguistic coherence.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'India\'s First Five Year Plan (1951-1956) was based on which economic growth model focusing on capital accumulation and agricultural development?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Harrod-Domar Model',
        B: 'P.C. Mahalanobis Heavy Industrialization Model (Second Plan)',
        C: 'Gadgil Formula',
        D: 'Rao-Manmohan Model',
      },
      correctAnswer: 'A',
      explanation: 'The First Plan adopted the Harrod-Domar model targeting agriculture, irrigation dams (Bhakra-Nangal, Hirakud), and foodgrain self-sufficiency.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'The Non-Aligned Movement (NAM) was formally inaugurated at the Belgrade Conference in 1961 based on the Five Principles of Peaceful Coexistence (Panchsheel 1954) pioneered by Jawaharlal Nehru, Josip Broz Tito, and:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Gamal Abdel Nasser (Egypt), Kwame Nkrumah (Ghana), and Sukarno (Indonesia)',
        B: 'Winston Churchill and Harry Truman',
        C: 'Mao Zedong and Ho Chi Minh',
        D: 'Fidel Castro and Che Guevara',
      },
      correctAnswer: 'A',
      explanation: 'Nehru, Nasser, Tito, Sukarno, and Nkrumah led the founding of NAM to preserve strategic autonomy and avoid alignment with the Cold War superpowers (USA and USSR).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'The "Panchsheel" agreement (Five Principles of Peaceful Coexistence) was signed in 1954 between India and which nation?',
      questionType: 'Direct MCQ',
      options: {
        A: 'People\'s Republic of China (PRC)',
        B: 'Pakistan',
        C: 'Soviet Union',
        D: 'United States',
      },
      correctAnswer: 'A',
      explanation: 'Panchsheel was signed between Prime Minister Jawaharlal Nehru and Premier Zhou Enlai of China regarding mutual respect for territorial integrity, non-aggression, non-interference, equality, and peaceful coexistence.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'The "Green Revolution" in Indian agriculture was initiated in the mid-1960s with High-Yielding Variety (HYV) semi-dwarf wheat seeds developed by Norman Borlaug, spearheaded in India by agricultural scientist:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Dr. M.S. Swaminathan (with C. Subramaniam)',
        B: 'Dr. Verghese Kurien (White Revolution)',
        C: 'Dr. Homi Bhabha',
        D: 'Dr. Vikram Sarabhai',
      },
      correctAnswer: 'A',
      explanation: 'Dr. M.S. Swaminathan led the introduction of Mexican dwarf wheat varieties in Punjab, Haryana, and Western UP, transforming India from a food-deficient nation into a self-reliant agricultural power.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'Operation Blue Star was conducted in June 1984 by the Indian Army under Prime Minister Indira Gandhi to flush out armed Sikh militants from which holy shrine?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Golden Temple (Harmandir Sahib), Amritsar',
        B: 'Anandpur Sahib',
        C: 'Damdama Sahib',
        D: 'Fatehgarh Sahib',
      },
      correctAnswer: 'A',
      explanation: 'Operation Blue Star was launched on 1-8 June 1984 to eliminate Jarnail Singh Bhindranwale and armed separatists entrenched inside the Golden Temple complex.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'The 73rd and 74th Constitutional Amendment Acts enacted in 1992 granted constitutional status and three-tier governance architecture to:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Panchayati Raj Institutions (Rural) and Urban Local Bodies (Municipalities)',
        B: 'Inter-State Council',
        C: 'National Human Rights Commission',
        D: 'Central Information Commission',
      },
      correctAnswer: 'A',
      explanation: 'The 73rd Amendment inserted Part IX (Schedule 11) for Panchayats, while the 74th Amendment inserted Part IXA (Schedule 12) for Municipalities, decentralizing grassroots democracy.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'India carried out its first peaceful underground nuclear detonation test codenamed "Smiling Buddha" (Pokhran-I) on 18 May 1974 during the tenure of Prime Minister:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Indira Gandhi',
        B: 'Jawaharlal Nehru',
        C: 'Lal Bahadur Shastri',
        D: 'Atal Bihari Vajpayee (Pokhran-II, 1998)',
      },
      correctAnswer: 'A',
      explanation: 'Pokhran-I was executed on Buddha Purnima in 1974 under Indira Gandhi, making India the sixth nuclear-capable nation outside the UN Security Council P5.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'The New Economic Policy of Liberalization, Privatization, and Globalization (LPG Reforms) was launched in July 1991 under the government of:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Prime Minister P.V. Narasimha Rao and Finance Minister Dr. Manmohan Singh',
        B: 'Rajiv Gandhi',
        C: 'V.P. Singh',
        D: 'Chandra Shekhar',
      },
      correctAnswer: 'A',
      explanation: 'Facing a severe balance-of-payments crisis in 1991, the Narasimha Rao government dismantled the License Raj, devalued the rupee, opened FDI, and reformed industrial trade policy.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 9 & 10: HISTORICAL METHOD, RESEARCH & HISTORIOGRAPHY (20 Questions: Q81 - Q100)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 9,
      questionText: 'Who is regarded as the "Father of History" in Western intellectual tradition and authored "The Histories" documenting the Greco-Persian Wars?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Herodotus',
        B: 'Thucydides (author of History of the Peloponnesian War)',
        C: 'Polybius',
        D: 'Livius',
      },
      correctAnswer: 'A',
      explanation: 'Herodotus of Halicarnassus (5th century BCE) was titled "Father of History" by Cicero for his systematic collection of materials and narrative inquiry (historia).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'Which 19th-century German historian is considered the founder of modern source-critical, archival, and objective historiography with his maxim "to show what actually happened" (wie es eigentlich gewesen)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Leopold von Ranke',
        B: 'Georg Wilhelm Friedrich Hegel',
        C: 'Karl Marx',
        D: 'Johann Gottfried Herder',
      },
      correctAnswer: 'A',
      explanation: 'Leopold von Ranke established the rigorous critical method based on primary archival records, rejecting speculative philosophy and asserting rigorous empiricism.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'The celebrated phrase "History is past politics and politics present history" is attributed to British historian:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Edward Augustus Freeman',
        B: 'Lord Acton',
        C: 'Thomas Babington Macaulay',
        D: 'Thomas Carlyle',
      },
      correctAnswer: 'A',
      explanation: 'E.A. Freeman inscribed this quote on the walls of Johns Hopkins University, defining 19th-century constitutional-political historiography.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'Which influential French historiographical school, founded in 1929 by Lucien Febvre and Marc Bloch, pioneered "total history", long-term structures (la longue durée), and mentalities over short-term political events?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Annales School (associated with Fernand Braudel)',
        B: 'Positivist Historicism',
        C: 'Frankfurt School',
        D: 'Subaltern Studies Group',
      },
      correctAnswer: 'A',
      explanation: 'The Annales school shifted historical research away from diplomatic battles toward geography, climate, economics, demography, and deep social structures (longue durée).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'The classic philosophical interrogation "What is History?" (1961), defining history as an "unending dialogue between the present and the past", was written by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Edward Hallett Carr (E.H. Carr)',
        B: 'R.G. Collingwood (The Idea of History)',
        C: 'G.M. Trevelyan',
        D: 'Arnold J. Toynbee (A Study of History)',
      },
      correctAnswer: 'A',
      explanation: 'E.H. Carr rejected pure Rankean empiricism, arguing that historical facts are always refracted through the mind of the historian and the social context of the present.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'Who wrote the seminal work "The Idea of History" (1946), arguing that "all history is the history of thought" and that the historian must re-enact past thought in their own mind?',
      questionType: 'Direct MCQ',
      options: {
        A: 'R.G. Collingwood',
        B: 'Benedetto Croce',
        C: 'Wilhelm Dilthey',
        D: 'Arnold Toynbee',
      },
      correctAnswer: 'A',
      explanation: 'R.G. Collingwood established the idealist philosophy of history, proposing that historical inquiry involves the imaginative re-enactment of past human thought.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'In his massive 12-volume comparative study "A Study of History" (1934-1961), Arnold J. Toynbee analyzed the rise and fall of 26 world civilizations through the cyclical mechanism of:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Challenge and Response (under the leadership of a creative minority)',
        B: 'Biological racial superiority',
        C: 'Class struggle alone',
        D: 'Geographical determinism',
      },
      correctAnswer: 'A',
      explanation: 'Toynbee proposed that civilizations emerge and flourish by successfully meeting environmental and human challenges led by creative elites.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'Which 14th-century Arab-North African historian and philosopher founded the science of human civilization (Umran) and formulated the concept of "Asabiyyah" (social solidarity/group cohesion) in the "Muqaddimah"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Ibn Khaldun',
        B: 'Al-Tabari',
        C: 'Al-Masudi',
        D: 'Ibn Battuta',
      },
      correctAnswer: 'A',
      explanation: 'Ibn Khaldun\'s Muqaddimah (1377 CE) revolutionized historiography by introducing sociological laws and cyclical dynamics of dynastic power driven by Asabiyyah.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'In Greek historiography, who is celebrated for his rigorous, forensic, and secular account of the "History of the Peloponnesian War", rejecting divine intervention and analyzing power politics?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Thucydides',
        B: 'Herodotus',
        C: 'Xenophon',
        D: 'Polybius',
      },
      correctAnswer: 'A',
      explanation: 'Thucydides applied strict standards of evidence-gathering, eyewitness analysis, and political realism, famously including the Melian Dialogue and Pericles\' Funeral Oration.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'In Enlightenment historiography, who authored the monumental masterwork "The History of the Decline and Fall of the Roman Empire" (1776-1789)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Edward Gibbon',
        B: 'David Hume',
        C: 'Voltaire',
        D: 'Thomas Macaulay',
      },
      correctAnswer: 'A',
      explanation: 'Edward Gibbon\'s six-volume masterpiece chronicled Roman civilization from the 2nd century CE to the fall of Constantinople in 1453 with magnificent ironic prose.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'The "Subaltern Studies" collective in South Asian historiography, launched in the early 1980s to write history "from below" recovered from the perspective of peasant and working-class agency, was founded by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Ranajit Guha (author of Elementary Aspects of Peasant Insurgency in Colonial India)',
        B: 'Dipesh Chakrabarty',
        C: 'Partha Chatterjee',
        D: 'Gayatri Chakravorty Spivak',
      },
      correctAnswer: 'A',
      explanation: 'Ranajit Guha founded the Subaltern Studies project, criticizing both colonialist and elite nationalist historiography for ignoring autonomous subaltern politics and peasant resistance.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'Which Marxist historian authored "An Introduction to the Study of Indian History" (1956) and "The Culture and Civilisation of Ancient India in Historical Outline", pioneering materialist dialectical analysis in Indian history?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Damodar Dharmananda Kosambi (D.D. Kosambi)',
        B: 'R.S. Sharma (Indian Feudalism)',
        C: 'Romila Thapar',
        D: 'Irfan Habib (Agrarian System of Mughal India)',
      },
      correctAnswer: 'A',
      explanation: 'D.D. Kosambi redefined history as "the presentation in chronological order of successive developments in the means and relations of production" combining field archaeology, ethnography, and numismatics.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'In historical research methodology, "External Criticism" (Heuristics) is concerned with:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Establishing the authenticity, provenance, authorship, and date of a historical document',
        B: 'Evaluating the inner truthfulness and psychological bias of the author\'s statements',
        C: 'Publishing book reviews in contemporary newspapers',
        D: 'Translating oral folklore into computerized statistical charts',
      },
      correctAnswer: 'A',
      explanation: 'External Criticism verifies whether the physical document is genuine or forged, its dating, authorship, and paleographic authenticity. Internal criticism (Hermeneutics) analyzes the credibility and meaning of its contents.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'The debate on "Indian Feudalism" (advancing the thesis that royal land grants, fragmented polity, and peasant subjection formed a feudal social formation from circa 300 to 1200 CE) was pioneered by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Ram Sharan Sharma (R.S. Sharma)',
        B: 'Harbans Mukhia (author of Was There Feudalism in Indian History?)',
        C: 'Burton Stein (Segmentary State model)',
        D: 'Noboru Karashima',
      },
      correctAnswer: 'A',
      explanation: 'R.S. Sharma in "Indian Feudalism" (1965) advanced the thesis of economic de-urbanization, decline of foreign trade, and feudal agrarian relations through agrahara land charters.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'Which monumental 12th-century historical chronicle of Kashmir, composed in Sanskrit verse by Kalhana, is acclaimed as ancient India\'s first genuine historiographical text written with objective detachment?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Rajatarangini ("River of Kings", completed 1149-1150 CE)',
        B: 'Harshacharita of Banabhatta',
        C: 'Vikramankadevacharita of Bilhana',
        D: 'Prithviraj Raso of Chand Bardai',
      },
      correctAnswer: 'A',
      explanation: 'Kalhana\'s Rajatarangini uses inscriptions, coins, royal charters, and critical examination of predecessor chroniclers to document the dynastic history of Kashmir with remarkable intellectual honesty.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'In his influential critique of Eurocentric historical consciousness "Provincializing Europe: Postcolonial Thought and Historical Difference" (2000), which Subaltern Studies scholar explored "History 1" and "History 2"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Dipesh Chakrabarty',
        B: 'Partha Chatterjee (The Nation and Its Fragments)',
        C: 'Gyanendra Pandey',
        D: 'Shahid Amin (Event, Metaphor, Memory)',
      },
      correctAnswer: 'A',
      explanation: 'Dipesh Chakrabarty explored how universalist categories of modernity need to be provincialized by examining life-practices and non-secular subaltern lifeworlds.',
      difficulty: 'HARD',
    },
    {
      unitNumber: 10,
      questionText: 'In Mughal historiographical studies, who authored the foundational economic analysis "The Agrarian System of Mughal India, 1556-1707" (1963)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Irfan Habib',
        B: 'Satish Chandra (Parties and Politics at the Mughal Court)',
        C: 'Athar Ali (The Mughal Nobility under Aurangzeb)',
        D: 'Muzaffar Alam',
      },
      correctAnswer: 'A',
      explanation: 'Irfan Habib analyzed Mughal land revenue demand (Zabt), surplus extraction, and the agrarian crisis leading to peasant rebellions (Jats, Satnamis, Sikhs) that undermined imperial stability.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'Who authored the pioneering critical feminist historical analysis of the Ramayana and Mahabharata traditions in ancient India in "Women in Early Indian Buddhism" and "The Inscriptions of Asoka"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Uma Chakravarti (author of Rewriting History: The Life and Times of Pandita Ramabai)',
        B: 'Tanika Sarkar',
        C: 'Kumkum Roy',
        D: 'Urvashi Butalia',
      },
      correctAnswer: 'A',
      explanation: 'Uma Chakravarti pioneered feminist historical analysis in India, formulating concepts like "Brahmanical Patriarchy" and exploring gender in early Buddhist traditions.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'In historical research methodology, "Quantitative History" and "Cliometrics" refer to:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The systematic application of econometric, statistical, and mathematical models to historical datasets',
        B: 'The chemical dating of rock-cut caves',
        C: 'The artistic evaluation of museum portraits',
        D: 'The linguistic translation of ancient poetry',
      },
      correctAnswer: 'A',
      explanation: 'Cliometrics (associated with Robert Fogel and Douglass North) applies quantitative economic techniques to historical records.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'The concept of "Microhistory" (the intensive historical investigation of a well-defined smaller unit of research, such as a single village or individual trial record) was pioneered by Italian historians Carlo Ginzburg ("The Cheese and the Worms", 1976) and:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Giovanni Levi',
        B: 'Fernand Braudel',
        C: 'Marc Bloch',
        D: 'Michel Foucault',
      },
      correctAnswer: 'A',
      explanation: 'Carlo Ginzburg and Giovanni Levi founded Microstoria (Microhistory) to reconstruct popular culture and subaltern mentalities through detailed courtroom and inquisitorial archives.',
      difficulty: 'HARD',
    },
  ];

  return {
    subjectCode: '06',
    subjectSlug: 'history',
    mockNumber: 1,
    title: 'History — Mock Test 1: Full Syllabus Simulation (100 Qs)',
    description: 'Comprehensive 100-question UGC NET History simulation covering Ancient, Medieval, Modern Indian History, and Historiography across all 10 official units.',
    accessTier: 'FREE',
    isFreeBenchmark: true,
    questions,
  };
}
