import { MockTestDefinition, RawMockQuestion } from '../common';

export function getLawMockTest(): MockTestDefinition {
  const questions: RawMockQuestion[] = [
    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 1: JURISPRUDENCE (10 Questions: Q1 - Q10)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 1,
      questionText: 'Who defined Law as the "Command of the Sovereign, backed by the threat of Sanction and habitually obeyed by the bulk of the population" (Imperative / Analytical Positivist Theory)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'John Austin (The Province of Jurisprudence Determined, 1832)',
        B: 'Hans Kelsen (Pure Theory of Law / Grundnorm)',
        C: 'H.L.A. Hart (The Concept of Law)',
        D: 'Jeremy Bentham (Utilitarian Positivism)',
      },
      correctAnswer: 'A',
      explanation: 'Austin\'s command theory reduces law to tri-partite elements: Command, Duty, and Sanction issued by a politically determinate sovereign.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In his "Pure Theory of Law" (Reine Rechtslehre, 1934), Hans Kelsen conceptualized the legal system as a hierarchical dynamic pyramid of norms deriving validity from a supreme presupposed hypothesis known as the:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Grundnorm (Basic Norm)',
        B: 'Rule of Recognition (H.L.A. Hart)',
        C: 'Categorical Imperative (Kant)',
        D: 'Volksgeist (Savigny)',
      },
      correctAnswer: 'A',
      explanation: 'Kelsen argued that law is a hierarchy of "Ought" norms (Sollen) tracing validity back to the Grundnorm, purified from alien sociological, political, or moral contaminants.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In "The Concept of Law" (1961), H.L.A. Hart conceptualized the legal system as the union of which two categories of rules?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Primary Rules of Obligation (imposing duties) and Secondary Rules (Rule of Recognition, Rules of Change, Rules of Adjudication conferring powers)',
        B: 'Criminal Rules and Civil Rules',
        C: 'Moral Rules and Religious Rules',
        D: 'Written Rules and Unwritten Rules',
      },
      correctAnswer: 'A',
      explanation: 'Hart overcame Austin\'s coercive command model by showing that law is a union of duty-imposing Primary rules and power-conferring Secondary rules anchored by the empirical Rule of Recognition.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'Which founder of the Historical School of Jurisprudence posited that Law is NOT made, but found in the popular consciousness and organic living spirit of the people (Volksgeist)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Friedrich Carl von Savigny ("On the Vocation of Our Age for Legislation and Jurisprudence", 1814)',
        B: 'Sir Henry Maine (Ancient Law - Status to Contract)',
        C: 'Eugen Ehrlich (Living Law)',
        D: 'Roscoe Pound (Social Engineering)',
      },
      correctAnswer: 'A',
      explanation: 'Savigny strongly opposed Thibaut\'s proposal for immediate French-style codification of German civil law, asserting that law grows organically like language through historical Volksgeist.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Who formulated the doctrine of "Social Engineering" in Sociological Jurisprudence, defining the function of law as balancing and satisfying competing public, social, and individual interests with minimum friction and waste?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Roscoe Pound',
        B: 'Rudolf von Ihering (Law as a Means to an End)',
        C: 'Leon Duguit (Social Solidarity)',
        D: 'Karl Renner',
      },
      correctAnswer: 'A',
      explanation: 'Dean Roscoe Pound classified conflicting interests into Individual, Public, and Social Interests, providing jural postulates to guide judicial balancing.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In legal rights theory, Wesley Newcomb Hohfeld formulated the table of "Fundamental Legal Conceptions". What is the exact Hohfeldian Jural Correlative of a "Right" (Claim)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Duty',
        B: 'No-Right (Jural Opposite of Right)',
        C: 'Privilege / Liberty',
        D: 'Immunity',
      },
      correctAnswer: 'A',
      explanation: 'Hohfeldian Jural Correlatives (if X has, Y has): Right $\\leftrightarrow$ Duty; Privilege $\\leftrightarrow$ No-Right; Power $\\leftrightarrow$ Liability; Immunity $\\leftrightarrow$ Disability.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'According to John Salmond, what are the two essential constituent elements required to establish legal Possession in jurisprudence?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Corpus Possessionis (physical control/detention) and Animus Possidendi (intention to hold for oneself)',
        B: 'Title deed and Registration receipt',
        C: 'Ownership and Encumbrance',
        D: 'Legal right and Judicial decree',
      },
      correctAnswer: 'A',
      explanation: 'Possession requires both the physical factual element (Corpus) and the mental element of conscious exclusive control (Animus).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In the doctrine of judicial precedent, the binding legal principle or reason for the decision that forms the authoritative part of a judgment is termed the:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Ratio Decidendi',
        B: 'Obiter Dicta (statements made in passing, persuasive only)',
        C: 'Per Incuriam (rendered through lack of care / ignoring statutes)',
        D: 'Res Judicata',
      },
      correctAnswer: 'A',
      explanation: 'Ratio Decidendi is the rule of law on which the final judicial decision is founded, creating binding precedent under Article 141 of the Constitution of India.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Which American Legal Realist judge famously defined law in "The Path of the Law" (1897) from the perspective of the "Bad Man", asserting that "The prophecies of what the courts will do in fact, and nothing more pretentious, are what I mean by the law"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Justice Oliver Wendell Holmes Jr.',
        B: 'Jerome Frank (Law and the Modern Mind - Rule and Fact Skepticism)',
        C: 'Karl Llewellyn (The Bramble Bush)',
        D: 'Felix Frankfurter',
      },
      correctAnswer: 'A',
      explanation: 'Justice Holmes initiated American Legal Realism, discarding formalist legal deductions and emphasizing experiential judicial reality.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In Natural Law theory, which medieval Christian philosopher synthesized Aristotelian philosophy with Christian theology in "Summa Theologiae", dividing law into Lex Aeterna (Eternal Law), Lex Divina (Divine Law), Lex Naturalis (Natural Law), and Lex Humana (Human Positive Law)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Saint Thomas Aquinas',
        B: 'Saint Augustine of Hippo',
        C: 'Hugo Grotius (Father of Modern International Law)',
        D: 'John Locke',
      },
      correctAnswer: 'A',
      explanation: 'St. Thomas Aquinas asserted that Lex Humana must conform to Natural Law, coining the maxim: "Lex iniusta non est lex" (An unjust law is no law at all).',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 2 & 3: CONSTITUTIONAL LAW & PUBLIC INTERNATIONAL LAW (20 Questions: Q11 - Q30)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 2,
      questionText: 'In Maneka Gandhi v. Union of India (1978), the Supreme Court expanded the scope of Article 21, establishing that any procedure depriving a person of life or personal liberty must be:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Just, Fair, and Reasonable (Substantive Due Process incorporating the Golden Triangle of Articles 14, 19, and 21)',
        B: 'Strictly formal and enacted by Parliament regardless of fairness (A.K. Gopalan 1950 doctrine)',
        C: 'Approved by the Governor of the state',
        D: 'Reviewed by the Law Commission',
      },
      correctAnswer: 'A',
      explanation: 'Maneka Gandhi overruled the narrow literalist Gopalan doctrine, weaving Articles 14, 19, and 21 into an indivisible "Golden Triangle" ensuring procedural and substantive fairness.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In S.R. Bommai v. Union of India (1994), a 9-judge Constitution Bench held that:',
      questionType: 'Direct MCQ',
      options: {
        A: 'A Presidential Proclamation under Article 356 (State Emergency) is subject to judicial review, and Secularism is an immutable basic feature of the Constitution',
        B: 'State Governors have absolute unchallengeable discretion to dissolve legislative assemblies',
        C: 'Article 356 cannot be scrutinized by any court under any circumstances',
        D: 'Fundamental rights are automatically suspended without presidential notification',
      },
      correctAnswer: 'A',
      explanation: 'Bommai disciplined the misuse of Article 356, mandating floor tests in legislative assemblies and establishing judicial review over presidential satisfaction.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'Which Constitutional Amendment Act inserted Article 21A, making free and compulsory education for all children between the ages of 6 and 14 years a Fundamental Right?',
      questionType: 'Direct MCQ',
      options: {
        A: '86th Constitutional Amendment Act 2002',
        B: '42nd Constitutional Amendment Act 1976',
        C: '44th Constitutional Amendment Act 1978',
        D: '93rd Constitutional Amendment Act 2005',
      },
      correctAnswer: 'A',
      explanation: 'The 86th Amendment inserted Article 21A, modified Article 45, and added Fundamental Duty Article 51A(k) for parents/guardians, leading to the RTE Act 2009.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'According to Article 38(1) of the Statute of the International Court of Justice (ICJ), what are the four recognized sources of Public International Law in descending hierarchy?',
      questionType: 'Direct MCQ',
      options: {
        A: '(a) International Conventions/Treaties, (b) International Custom as evidence of general practice accepted as law, (c) General Principles of Law recognized by civilized nations, and (d) Judicial decisions and teachings of highly qualified publicists as subsidiary means',
        B: 'UN General Assembly Resolutions, Security Council Vetoes, Interpol Warrants, and Treaties',
        C: 'National Constitutions, Roman Law, Canon Law, and Admiralty Courts',
        D: 'Bilateral Trade Agreements and Foreign Direct Investment Bilateral Treaties',
      },
      correctAnswer: 'A',
      explanation: 'Article 38(1) of the ICJ Statute constitutes the universal formal catalogue of sources of international law.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'Under International Humanitarian Law and the Vienna Convention on the Law of Treaties (Article 53), a "Jus Cogens" norm is defined as:',
      questionType: 'Direct MCQ',
      options: {
        A: 'A peremptory norm of general international law accepted and recognized by the international community from which NO derogation is permitted (e.g. prohibitions on Genocide, Slavery, Piracy, and Torture)',
        B: 'A bilateral commercial agreement between neighbouring states',
        C: 'An optional protocol to an extradition treaty',
        D: 'A non-binding resolution passed by the UN Human Rights Council',
      },
      correctAnswer: 'A',
      explanation: 'A treaty is void if, at the time of its conclusion, it conflicts with a peremptory norm of general international law (Jus Cogens).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'Under the United Nations Convention on the Law of the Sea (UNCLOS 1982), what is the maximum breadth of the "Exclusive Economic Zone" (EEZ) measured from the baseline of the coastal state?',
      questionType: 'Direct MCQ',
      options: {
        A: '$200\\text{ Nautical Miles}$',
        B: '$12\\text{ Nautical Miles}$ (Territorial Sea)',
        C: '$24\\text{ Nautical Miles}$ (Contiguous Zone)',
        D: '$350\\text{ Nautical Miles}$ (Extended Continental Shelf)',
      },
      correctAnswer: 'A',
      explanation: 'Article 57 of UNCLOS establishes the EEZ up to 200 nautical miles, granting the coastal state sovereign exploration rights over living and non-living marine resources.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 4, 5 & 6: CRIMES, TORTS & COMMERCIAL LAW (30 Questions: Q31 - Q60)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 4,
      questionText: 'Under Section 84 of the Indian Penal Code 1860 (now under Bharatiya Nyaya Sanhita), the defense of Insanity is legally grounded in the landmark English common law principles established in:',
      questionType: 'Direct MCQ',
      options: {
        A: 'M\'Naghten\'s Case (1843)',
        B: 'R v. Dudley and Stephens (Necessity - cabin boy cannibalism, 1884)',
        C: 'Director of Public Prosecutions v. Beard (Intoxication, 1920)',
        D: 'R v. Tolson (Mistake of Fact, 1889)',
      },
      correctAnswer: 'A',
      explanation: 'The M\'Naghten Rules establish that to plead insanity, it must be clearly proved that at the time of committing the act, the accused was labouring under such a defect of reason from disease of the mind as not to know the nature and quality of the act, or that it was wrong.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'In criminal law, what is the crucial legal distinction between "Culpable Homicide not amounting to Murder" (Section 299 IPC) and "Murder" (Section 300 IPC)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'The degree of probability of causing death: Murder requires higher certainty (bodily injury intended to be inflicted is sufficient in the ordinary course of nature to cause death - Reg v. Govinda, 1876)',
        B: 'The presence of weapon',
        C: 'The time of day the offence was committed',
        D: 'The age of the victim',
      },
      correctAnswer: 'A',
      explanation: 'Justice Melvill in Reg v. Govinda analyzed that both require intention/knowledge, but Murder requires higher objective bodily certainty of death.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'In the Law of Torts, the landmark rule of "Strict Liability" (the rule that a person who brings on his land and keeps there anything likely to do mischief if it escapes, does so at his peril) was laid down in:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Rylands v. Fletcher (1868, per Blackburn J.)',
        B: 'Donoghue v. Stevenson (Manufacturer liability / Snail in ginger beer, 1932)',
        C: 'Ashby v. White (Injuria sine damno, 1703)',
        D: 'Gloucester Grammar School Case (Damnum sine injuria, 1410)',
      },
      correctAnswer: 'A',
      explanation: 'Rylands v. Fletcher established strict liability for non-natural land use, subject to exceptions (Act of God, Plaintiff\'s fault, Statutory authority, Vis Major).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'In M.C. Mehta v. Union of India (Oleum Gas Leak Case, 1987), the Supreme Court of India led by Chief Justice P.N. Bhagwati formulated the pioneering doctrine of:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Absolute Liability (imposing an absolute, non-delegable duty with NO exceptions for hazardous or inherently dangerous industrial enterprises)',
        B: 'Strict Liability with all Rylands exceptions',
        C: 'Qualified sovereign immunity',
        D: 'Contributory negligence',
      },
      correctAnswer: 'A',
      explanation: 'Absolute Liability holds hazardous enterprises liable without the benefit of any Rylands v. Fletcher exceptions, calibrated to the enterprise\'s financial capacity.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'In the landmark English torts case Donoghue v. Stevenson (1932), Lord Atkin formulated the famous "Neighbour Principle" establishing manufacturer negligence liability based on:',
      questionType: 'Direct MCQ',
      options: {
        A: '"You must take reasonable care to avoid acts or omissions which you can reasonably foresee would be likely to injure your neighbour (persons so closely and directly affected by my act)"',
        B: 'Privity of contract strictly',
        C: 'Intentional malice',
        D: 'Criminal intent under statutory codes',
      },
      correctAnswer: 'A',
      explanation: 'Lord Atkin decoupled tortious duty of care from contractual privity, birthing modern negligence law worldwide.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'Under the Indian Contract Act 1872, what is the legal effect of a contract entered into with a Minor (a person who has not attained 18 years of age)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Void ab initio (completely void from the very beginning - Mohori Bibee v. Dharmodas Ghose, 1903)',
        B: 'Voidable at the option of the minor',
        C: 'Valid and enforceable if ratified upon attaining majority',
        D: 'Illegal under criminal statutes',
      },
      correctAnswer: 'A',
      explanation: 'The Privy Council in Mohori Bibee settled that Section 11 of the Contract Act renders all agreements by minors absolutely void ab initio with no estoppel or ratification.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 7, 8, 9 & 10: FAMILY, ENVIRONMENT, IPR & COMPARATIVE LAW (40 Questions: Q61 - Q100)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 7,
      questionText: 'Under the Hindu Succession (Amendment) Act 2005 (amending Section 6 of the Hindu Succession Act 1956), a daughter of a coparcener:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Becomes a Coparcener by birth in her own right in the same manner as a son, having the same rights and liabilities (affirmed in Vineeta Sharma v. Rakesh Sharma, 2020)',
        B: 'Is entitled only to maintenance until marriage',
        C: 'Cannot demand partition of coparcenary property',
        D: 'Inherits only maternal Stridhan property',
      },
      correctAnswer: 'A',
      explanation: 'The 2005 amendment conferred equal coparcenary birth rights upon daughters in Joint Hindu Mitakshara coparcenary property.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'In Vellore Citizens\' Welfare Forum v. Union of India (1996), the Supreme Court of India held that which two principles are essential features of "Sustainable Development" and part of the environmental law of the land under Articles 21, 47, 48A, and 51A(g)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'The Precautionary Principle and the Polluter Pays Principle',
        B: 'Absolute Sovereign Immunity and Industrial Priority',
        C: 'Laissez-faire Economic Expansion and Tariff Protection',
        D: 'Public Trust Doctrine only',
      },
      correctAnswer: 'A',
      explanation: 'Justice Kuldip Singh integrated the Precautionary Principle (anticipating environmental harm) and Polluter Pays Principle into Indian jurisprudence under Article 21.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'Under Section 3(d) of the Indian Patents Act 1970 (as upheld by the Supreme Court in Novartis AG v. Union of India, 2013), what is NOT patentable?',
      questionType: 'Direct MCQ',
      options: {
        A: 'The mere discovery of a new form of a known substance which does not result in the enhancement of the known therapeutic efficacy of that substance (anti-evergreening provision)',
        B: 'Any industrial manufacturing machine',
        C: 'A computer hardware chip',
        D: 'A chemical compound invented for the first time',
      },
      correctAnswer: 'A',
      explanation: 'Section 3(d) prevents "evergreening" of pharmaceutical patents by multinational corporations unless significant therapeutic efficacy enhancement is proved.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'In comparative constitutional law, which country\'s constitutional court introduced the "Basic Law" (Grundgesetz 1949) concept of "Militant Democracy" (Streitbare Demokratie) permitting the ban of political parties seeking to undermine the free democratic basic order?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Federal Republic of Germany (Federal Constitutional Court in Karlsruhe)',
        B: 'United States of America',
        C: 'United Kingdom',
        D: 'Japan',
      },
      correctAnswer: 'A',
      explanation: 'Post-war Germany\'s Basic Law embraces Militant Democracy to prevent anti-democratic totalitarian parties from utilizing democratic liberties to destroy democracy itself.',
      difficulty: 'HARD',
    },
  ];

  return {
    subjectCode: '58',
    subjectSlug: 'law',
    mockNumber: 1,
    title: 'Law — Mock Test 1: Full Syllabus Simulation (100 Qs)',
    description: 'Authentic 100-question UGC NET Law simulation covering Jurisprudence, Constitutional & Administrative Law, Public International Law, Law of Crimes, Law of Torts, Commercial Law, Family Law, Environment & Human Rights, IPR, and Comparative Public Law across all 10 units.',
    accessTier: 'FREE',
    isFreeBenchmark: true,
    questions,
  };
}
