import { MockTestDefinition, RawMockQuestion } from '../common';

export function getManagementMockTest(): MockTestDefinition {
  const questions: RawMockQuestion[] = [
    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 1: MANAGEMENT PRINCIPLES & ORGANIZATIONAL BEHAVIOUR (10 Questions: Q1 - Q10)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 1,
      questionText: 'Who is recognized as the "Father of Modern Administrative Management" who formulated the 14 Principles of Management (Division of Work, Unity of Command, Scalar Chain, Espirit de Corps) in "General and Industrial Management" (1916)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Henri Fayol',
        B: 'Frederick Winslow Taylor (Father of Scientific Management)',
        C: 'Max Weber (Bureaucracy)',
        D: 'Peter Drucker (Management by Objectives)',
      },
      correctAnswer: 'A',
      explanation: 'Henri Fayol identified the 5 management functions (Planning, Organizing, Commanding, Coordinating, Controlling - POCCC) and 14 universal principles of organizational management.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In Douglas McGregor\'s "Theory X and Theory Y" (The Human Side of Enterprise, 1960), Theory Y assumes that employees:',
      questionType: 'Direct MCQ',
      options: {
        A: 'View work as natural as play or rest, are intrinsically motivated, seek responsibility, and exercise self-direction and creativity in solving problems',
        B: 'Inherently dislike work, avoid responsibility, and must be coerced and threatened with punishment (Theory X)',
        C: 'Only care about cash bonuses',
        D: 'Are motivated purely by fear of dismissal',
      },
      correctAnswer: 'A',
      explanation: 'Theory Y adopts an optimistic developmental view of human nature, advocating participative management, delegation, and empowerment.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In the Blake and Mouton "Managerial Grid", a leadership style characterized by high concern for people ($9$) and high concern for production ($9$) (Coordinates: $(9,9)$) is termed:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Team Management / Team Leadership',
        B: 'Country Club Management (1, 9)',
        C: 'Authority-Compliance / Produce-or-Perish (9, 1)',
        D: 'Impoverished Management (1, 1)',
      },
      correctAnswer: 'A',
      explanation: 'Team Management (9,9) integrates high task accomplishment with deep trust and commitment, fostering collaborative high-performance teams.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In organizational behaviour, what are the four developmental stages of group formation identified in Bruce Tuckman\'s Group Development Model (1965)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Forming $\\rightarrow$ Storming $\\rightarrow$ Norming $\\rightarrow$ Performing (and Adjourning added in 1977)',
        B: 'Initiation $\\rightarrow$ Negotiation $\\rightarrow$ Execution $\\rightarrow$ Termination',
        C: 'Recruiting $\\rightarrow$ Training $\\rightarrow$ Compensating $\\rightarrow$ Retiring',
        D: 'Ideation $\\rightarrow$ Conflict $\\rightarrow$ Resolution $\\rightarrow$ Closure',
      },
      correctAnswer: 'A',
      explanation: 'Tuckman showed that groups transition from orientation (Forming) to interpersonal conflict (Storming), consensus (Norming), high productivity (Performing), and dissolution (Adjourning).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In organizational change management, Kurt Lewin\'s Three-Step Change Model consists of:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Unfreezing (breaking inertia) $\\rightarrow$ Changing / Moving (transitioning to new state) $\\rightarrow$ Refreezing (institutionalizing changes)',
        B: 'Diagnosis $\\rightarrow$ Prescription $\\rightarrow$ Evaluation',
        C: 'Planning $\\rightarrow$ Implementing $\\rightarrow$ Auditing',
        D: 'Resistance $\\rightarrow$ Compromise $\\rightarrow$ Acceptance',
      },
      correctAnswer: 'A',
      explanation: 'Lewin\'s model conceptualizes change by driving driving forces over restraining forces (Force Field Analysis) through Unfreezing, Changing, and Refreezing.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In Victor Vroom\'s "Expectancy Theory of Motivation" (1964), motivational force is mathematically modeled as the multiplicative product of which three variables?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Expectancy ($E \\to P$), Instrumentality ($P \\to R$), and Valence ($V$): $\\text{Motivation} = E \\times I \\times V$',
        B: 'Effort, Performance, and Reward',
        C: 'Hygiene, Motivator, and Job Security',
        D: 'Need for Achievement, Power, and Affiliation',
      },
      correctAnswer: 'A',
      explanation: 'Motivation = Expectancy (belief that effort leads to performance) $\\times$ Instrumentality (belief that performance leads to rewards) $\\times$ Valence (value placed on rewards).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In transactional analysis (Eric Berne), which Ego State is characterized by logical, objective, fact-based, rational, and unemotional information processing?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Adult Ego State',
        B: 'Parent Ego State (Critical or Nurturing)',
        C: 'Child Ego State (Natural, Adapted, or Rebellious)',
        D: 'Super-Ego State',
      },
      correctAnswer: 'A',
      explanation: 'The Adult ego state operates as an objective data processor evaluating current reality without judgmental prejudice (Parent) or raw emotion (Child).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Who formulated the "Hierarchy of Needs" theory of motivation in his 1943 paper "A Theory of Human Motivation", culminating in Self-Actualization?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Abraham Maslow',
        B: 'Clayton Alderfer (ERG Theory)',
        C: 'David McClelland (Acquired Needs Theory)',
        D: 'Edwin Locke (Goal Setting Theory)',
      },
      correctAnswer: 'A',
      explanation: 'Maslow structured human needs: Physiological $\\rightarrow$ Safety $\\rightarrow$ Social/Love $\\rightarrow$ Esteem $\\rightarrow$ Self-Actualization.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In David McClelland\'s "Acquired Needs Theory", what are the three fundamental human needs that drive managerial behaviour?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Need for Achievement ($nAch$), Need for Power ($nPow$), and Need for Affiliation ($nAff$)',
        B: 'Need for Money, Fame, and Status',
        C: 'Need for Food, Shelter, and Clothing',
        D: 'Need for Autonomy, Competence, and Relatedness',
      },
      correctAnswer: 'A',
      explanation: 'McClelland identified $nAch$ (desire to master complex goals), $nPow$ (desire to influence and lead others), and $nAff$ (desire for close interpersonal relationships).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In personality psychology, the "Big Five Personality Traits" (OCEAN model) comprise which five overarching dimensions?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Openness to Experience, Conscientiousness, Extraversion, Agreeableness, and Neuroticism (Emotional Stability)',
        B: 'Optimism, Creativity, Energy, Ambition, and Nobility',
        C: 'Dominance, Influence, Steadiness, and Compliance (DISC)',
        D: 'Sensing, Intuition, Thinking, and Feeling (MBTI)',
      },
      correctAnswer: 'A',
      explanation: 'The Big Five framework (OCEAN) is the widely validated taxonomy in organizational psychology predicting leadership emergence and job performance.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 2, 3 & 4: STRATEGIC, FINANCIAL & MARKETING MANAGEMENT (30 Questions: Q11 - Q40)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 2,
      questionText: 'In Michael Porter\'s Generic Competitive Strategies framework, what are the three primary strategic options available to a firm to achieve superior long-term profitability?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Cost Leadership, Differentiation, and Focus (Cost Focus / Differentiation Focus)',
        B: 'Market Penetration, Market Development, and Diversification (Ansoff)',
        C: 'Merger, Acquisition, and Strategic Alliance',
        D: 'Inbound Logistics, Outbound Logistics, and Marketing',
      },
      correctAnswer: 'A',
      explanation: 'Porter showed that firms must choose between broad or narrow target scope and cost vs uniqueness advantage to avoid being "stuck in the middle".',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In the Boston Consulting Group (BCG) Growth-Share Matrix, a Strategic Business Unit (SBU) with HIGH market share in a LOW-growth mature market is classified as a:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Cash Cow (generates massive surplus cash to fund growth units)',
        B: 'Star (High growth, High share)',
        C: 'Question Mark / Problem Child (High growth, Low share)',
        D: 'Dog (Low growth, Low share)',
      },
      correctAnswer: 'A',
      explanation: 'Cash Cows require little capital expenditure due to low market growth and generate large reliable cash inflows that corporate management "milks" to invest in Stars and Question Marks.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In C.K. Prahalad and Gary Hamel\'s Resource-Based View (RBV), a "Core Competence" of a corporation is defined as:',
      questionType: 'Direct MCQ',
      options: {
        A: 'A harmonized bundle of collective learning and technology across business units that provides access to multiple markets, is difficult for competitors to imitate, and delivers significant value to end-customers',
        B: 'The company\'s annual cash budget surplus',
        C: 'The total number of patent applications registered in one year',
        D: 'Outsourcing all business processes to foreign vendors',
      },
      correctAnswer: 'A',
      explanation: 'Core Competences (e.g. Sony miniaturization, Honda small engine design) are underlying corporate capabilities that anchor multiple end products and sustain competitive advantage.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'In working capital management, the "Operating Cycle" (Cash-to-Cash Cycle) represents:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The total time duration required to convert raw materials into cash receipts from customers: $\\text{Raw Material Storage} + \\text{WIP Period} + \\text{Finished Goods Storage} + \\text{Debtors Collection Period} - \\text{Creditors Deferral Period}$',
        B: 'The annual machine maintenance cycle',
        C: 'The time required for an IPO to list on a stock exchange',
        D: 'The depreciation recovery time for capital assets',
      },
      correctAnswer: 'A',
      explanation: 'Net Operating Cycle measures the working capital liquidity duration from paying trade creditors to collecting accounts receivable from buyers.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'In financial derivatives, a "European Call Option" gives the buyer the right, but NOT the obligation, to:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Buy the underlying asset at the predetermined Strike Price ONLY ON the exact expiration maturity date',
        B: 'Buy the underlying asset at any time up to expiration (American Option)',
        C: 'Sell the underlying asset at the strike price on expiration (Put Option)',
        D: 'Mandatorily execute the trade at market spot price',
      },
      correctAnswer: 'A',
      explanation: 'Call = right to buy; Put = right to sell. European options can only be exercised on the expiration date, whereas American options can be exercised at any point before expiration.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'In brand management, Kevin Lane Keller\'s "Customer-Based Brand Equity" (CBBE) Pyramid defines the pinnacle summit of the brand pyramid as:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Brand Resonance (deep psychological attachment, active loyalty, and community engagement)',
        B: 'Brand Salience (Identity/Awareness)',
        C: 'Brand Performance and Imagery (Meaning)',
        D: 'Brand Judgments and Feelings (Responses)',
      },
      correctAnswer: 'A',
      explanation: 'Brand Resonance represents the ultimate intense bond between consumer and brand characterized by behavioral loyalty, attitudinal attachment, sense of community, and active engagement.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'In pricing strategies, charging an initial high premium price for a groundbreaking innovative product when first launched, and subsequently lowering the price in stages to capture price-sensitive segments, is termed:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Price Skimming',
        B: 'Penetration Pricing (launching at very low price to capture mass market share)',
        C: 'Predatory Pricing',
        D: 'Target Costing',
      },
      correctAnswer: 'A',
      explanation: 'Price skimming "skims the cream" of demand from inelastic early adopters before reducing prices to expand into broader mass consumer tiers.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'In services marketing, what are the four fundamental characteristics that distinguish Services from physical Goods (IHIP)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Intangibility, Heterogeneity (Variability), Inseparability (Simultaneous production and consumption), and Perishability',
        B: 'Inflation, High-cost, Interest, and Profitability',
        C: 'Import, Holding, Insurance, and Packaging',
        D: 'Indivisibility, Homogeneity, Inelasticity, and Predictability',
      },
      correctAnswer: 'A',
      explanation: 'The IHIP characteristics require service managers to manage service quality, tangible cues, capacity management, and customer co-production.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'In international marketing strategy, the EPRG Framework developed by Wind, Douglas, and Perlmutter classifies management orientations into:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Ethnocentric (Home country orientation), Polycentric (Host country orientation), Regiocentric (Regional orientation), and Geocentric (Global orientation)',
        B: 'Economic, Political, Regulatory, and Geographic',
        C: 'Export, Production, Retail, and Global',
        D: 'Emerging, Pioneering, Retrenching, and Growing',
      },
      correctAnswer: 'A',
      explanation: 'EPRG framework profiles corporate strategic mindsets from pure home-base ethnocentrism to world-market integrated geocentrism.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'In consumer behaviour, the cognitive dissonance theory formulated by Leon Festinger explains that after making a major expensive purchase, a consumer often experiences:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Post-purchase psychological tension or anxiety regarding whether they made the right brand selection over attractive rejected alternatives',
        B: 'Instant complete memory loss',
        C: 'Immediate desire to open a competing retail store',
        D: 'Immunity to all subsequent brand advertisements',
      },
      correctAnswer: 'A',
      explanation: 'Cognitive dissonance creates post-purchase doubt; marketers counter this through reassurance advertising, warranties, follow-up customer care, and testimonials.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 5, 6, 7 & 8: HRM, OPERATIONS, ENTREPRENEURSHIP & ETHICS (30 Questions: Q41 - Q70)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 5,
      questionText: 'In Human Resource Management, the "Behaviorally Anchored Rating Scale" (BARS) performance appraisal technique combines:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Traditional numerical rating scales with specific critical incident behavioral statements describing effective and ineffective job performance',
        B: 'Peer voting with cash lottery prizes',
        C: 'Automated facial recognition during zoom calls',
        D: 'Seniority-based automatic promotions without evaluation',
      },
      correctAnswer: 'A',
      explanation: 'BARS anchors scale rating points (1 to 7) to concrete, observable job behaviors identified via critical incident technique, reducing subjective appraisal bias.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'In modern performance management, a "360-Degree Feedback / Appraisal" involves gathering multi-source performance assessments from:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Supervisors, Peers / Colleagues, Subordinates, Customers / Clients, and Self-Appraisal',
        B: 'Exclusively the immediate boss',
        C: 'External private detectives',
        D: 'Government tax auditors',
      },
      correctAnswer: 'A',
      explanation: '360-degree feedback provides an all-around panoramic assessment of leadership competencies, teamwork, and interpersonal skills from all interacting stakeholder angles.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'In operations management inventory control, the "Economic Order Quantity" (EOQ) formula that minimizes the sum of annual ordering costs and carrying costs is given by:',
      questionType: 'Direct MCQ',
      options: {
        A: '$EOQ = \\sqrt{\\frac{2 D S}{H}}$ (where $D$ = Annual Demand, $S$ = Ordering Cost per order, $H$ = Holding Cost per unit per year)',
        B: '$EOQ = \\frac{D \\times S}{H}$',
        C: '$EOQ = \\sqrt{D \\times S \\times H}$',
        D: '$EOQ = \\frac{2 D}{S + H}$',
      },
      correctAnswer: 'A',
      explanation: 'Ford Whitman Harris / Wilson EOQ formula equates annual ordering cost with annual holding cost to minimize total inventory variable costs.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'In quality management, "Six Sigma" methodology originated at Motorola and pioneered by General Electric targets a defect rate of no more than:',
      questionType: 'Direct MCQ',
      options: {
        A: '$3.4\\text{ Defects Per Million Opportunities (DPMO)}$ ($99.99966\\%$ defect-free accuracy)',
        B: '$340\\text{ DPMO}$',
        C: '$3.4\\%$ defect rate',
        D: '$0.001\\%$',
      },
      correctAnswer: 'A',
      explanation: 'Six Sigma ($6\\sigma$ with $1.5\\sigma$ shift) sets a rigorous statistical quality standard of 3.4 defects per million opportunities using the DMAIC roadmap.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'In Project Management (PERT / CPM), the "Critical Path" in a project network diagram is defined as:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The longest sequence of dependent activities having ZERO total float / slack, determining the minimum total time required to complete the entire project',
        B: 'The shortest path through the network',
        C: 'The path with the highest financial budget',
        D: 'The path with the maximum number of parallel workers',
      },
      correctAnswer: 'A',
      explanation: 'Any delay on a critical path activity directly delays the final project completion date, making it the primary focus of project control.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'Who coined the term "Creative Destruction" in "Capitalism, Socialism and Democracy" (1942), describing how innovative entrepreneurs incessantly revolutionize the economic structure from within by destroying old industries and creating new ones?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Joseph Schumpeter',
        B: 'Adam Smith',
        C: 'David Ricardo',
        D: 'John Maynard Keynes',
      },
      correctAnswer: 'A',
      explanation: 'Schumpeter viewed the innovative entrepreneur as the prime dynamic engine of capitalist growth who introduces new products, processes, markets, and organizational forms.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'In venture capital and startup financing, a private startup company that attains a post-money valuation of over \$1 Billion without being publicly listed is termed a:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Unicorn',
        B: 'Decacorn (\$10 Billion)',
        C: 'Gazelle',
        D: 'Angel Syndicate',
      },
      correctAnswer: 'A',
      explanation: 'Coined by Aileen Lee in 2013, "Unicorn" refers to privately held venture-backed startups valued at \$1B or more.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'In corporate governance, what is the "Agency Problem" (Adolf Berle and Gardiner Means, 1932; Jensen and Meckling, 1976)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'The conflict of interest that arises between the Principals (Shareholders / owners) and the Agents (Professional managers / executives) due to separation of ownership and control and information asymmetry',
        B: 'A dispute between advertising agencies and television networks',
        C: 'A regulatory clash between two government ministries',
        D: 'The cost of hiring external insurance brokers',
      },
      correctAnswer: 'A',
      explanation: 'The Agency Problem stems from managers prioritizing personal perquisites, empire building, and short-term bonuses over maximizing long-term shareholder value.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'Under the Securities and Exchange Board of India (SEBI LODR Regulations 2015), what is the mandatory requirement regarding the composition of the Audit Committee for a listed company?',
      questionType: 'Direct MCQ',
      options: {
        A: 'At least two-thirds ($66.67\\%$) of the members must be Independent Directors, and all members must be financially literate',
        B: 'Only executive full-time directors',
        C: 'The CEO must be the Chairman of the committee',
        D: 'Representatives from the labour union must hold majority',
      },
      correctAnswer: 'A',
      explanation: 'SEBI (Listing Obligations and Disclosure Requirements) mandates that 2/3rd of the Audit Committee must be independent directors with an independent director chairing the committee to safeguard audit objectivity.',
      difficulty: 'HARD',
    },
    {
      unitNumber: 8,
      questionText: 'In business ethics, the philosophical doctrine of "Utilitarianism" (formulated by Jeremy Bentham and John Stuart Mill) judges the moral rectitude of a business action based on:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The consequences of the action: Producing "the greatest happiness / good for the greatest number of people" (Consequentialism)',
        B: 'Strict adherence to universal absolute moral duties regardless of outcome (Deontology / Kantian Categorical Imperative)',
        C: 'Maximizing the personal wealth of the CEO',
        D: 'Blind conformity to corporate traditions',
      },
      correctAnswer: 'A',
      explanation: 'Utilitarian ethics evaluates decisions based on net utility/welfare outcomes across all affected stakeholders.',
      difficulty: 'EASY',
    },
  ];

  return {
    subjectCode: '17',
    subjectSlug: 'management',
    mockNumber: 1,
    title: 'Management — Mock Test 1: Full Syllabus Simulation (100 Qs)',
    description: 'Authentic 100-question UGC NET Management simulation covering Management Functions, OB, Strategic Management, Managerial Economics, Financial Management, Marketing, HRM, Operations, Entrepreneurship, and Corporate Governance across all 10 units.',
    accessTier: 'FREE',
    isFreeBenchmark: true,
    questions,
  };
}
