import { MockTestDefinition, RawMockQuestion } from '../common';

export function getPaper1MockTest(): MockTestDefinition {
  const questions: RawMockQuestion[] = [
    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 1: TEACHING APTITUDE (10 Questions: Q1 - Q10)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 1,
      questionText: 'Which of the following levels of teaching focuses primarily on the critical examination, problem-solving, and creative generation of new ideas by the learner?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Memory Level of Teaching (Herbartian Theory)',
        B: 'Understanding Level of Teaching (Morrison Model)',
        C: 'Reflective Level of Teaching (Hunt Model)',
        D: 'Autonomous Development Level',
      },
      correctAnswer: 'C',
      explanation: 'The Reflective Level of Teaching (proposed by Hunt) represents the highest cognitive level where learners actively engage in problem-solving, critical reflection, evaluation, and creative generation of knowledge.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'Given below are two statements regarding evaluation systems in higher education:\nStatement I: Formative assessment is conducted continuously throughout the instructional process to provide diagnostic feedback.\nStatement II: Summative assessment is primarily terminal in nature and aims to certify learner achievement against predetermined standards.\nIn light of the above statements, choose the most appropriate answer:',
      questionType: 'Statement Based',
      options: {
        A: 'Both Statement I and Statement II are correct',
        B: 'Both Statement I and Statement II are incorrect',
        C: 'Statement I is correct but Statement II is incorrect',
        D: 'Statement I is incorrect but Statement II is correct',
      },
      correctAnswer: 'A',
      explanation: 'Both statements are true. Formative assessment (diagnostic, continuous) guides ongoing learning, whereas summative assessment (evaluative, terminal) certifies outcome mastery at the end of an instructional cycle.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Which of the following learner characteristics is classified as an "affective domain" characteristic according to Bloom\'s taxonomy of educational objectives?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Visual-spatial processing ability',
        B: 'Motivation, attitudes, and internalized value systems',
        C: 'Prior academic conceptual knowledge',
        D: 'Fine motor coordination and psychomotor agility',
      },
      correctAnswer: 'B',
      explanation: 'Bloom, Krathwohl and Masia defined the Affective Domain as encompassing attitudes, emotions, motivation, values, appreciation, and internalization of ethical principles.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In the Choice Based Credit System (CBCS) implemented by the UGC, an "Elective Course" chosen generally from an unrelated discipline to seek broader exposure is termed as:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Discipline Specific Elective (DSE)',
        B: 'Generic Elective (GE) / Open Elective',
        C: 'Ability Enhancement Compulsory Course (AECC)',
        D: 'Skill Enhancement Course (SEC)',
      },
      correctAnswer: 'B',
      explanation: 'Under CBCS guidelines, a Generic Elective (GE) is an elective course chosen from an unrelated discipline/subject to foster multidisciplinary exposure and interdisciplinary breadth.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Which of the following is a non-projected visual teaching aid?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Epidiascope projection',
        B: 'Diorama and Flashcards',
        C: 'Overhead Projector (OHP) transparency',
        D: 'Liquid Crystal Display (LCD) multimedia projector',
      },
      correctAnswer: 'B',
      explanation: 'Dioramas, flashcards, charts, and chalkboards are non-projected visual aids because they display visual information directly without requiring optical lens projection systems.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Match List I (Teaching Method) with List II (Key Characteristic):\nList I:\n(a) Heuristic Method\n(b) Flipped Classroom\n(c) Socratic Seminar\n(d) Programmed Instruction\nList II:\n(1) Active dialogue through continuous disciplined questioning\n(2) Self-paced learning with immediate reinforcement of small steps\n(3) Discovery learning where student assumes role of independent researcher\n(4) Direct instruction consumed before class; collaborative problem-solving during class\nChoose the correct code:',
      questionType: 'Matching',
      options: {
        A: '(a)-(3), (b)-(4), (c)-(1), (d)-(2)',
        B: '(a)-(4), (b)-(3), (c)-(2), (d)-(1)',
        C: '(a)-(1), (b)-(2), (c)-(3), (d)-(4)',
        D: '(a)-(3), (b)-(1), (c)-(4), (d)-(2)',
      },
      correctAnswer: 'A',
      explanation: 'Heuristic method (Armstrong) is discovery-based (3); Flipped Classroom moves direct lecture out of class and active drills into class (4); Socratic method relies on inquiry dialogue (1); Programmed Instruction (Skinner) uses self-paced sequential reinforcement (2).',
      difficulty: 'HARD',
    },
    {
      unitNumber: 1,
      questionText: 'Assertion (A): Criterion-Referenced Assessment is designed to measure student performance against fixed predetermined criteria or learning standards rather than against peers.\nReason (R): Percentile ranks and bell-curve grading distributions are primary outputs of criterion-referenced tests.\nIn light of the above statements, choose the correct answer:',
      questionType: 'Assertion Reasoning',
      options: {
        A: 'Both (A) and (R) are true and (R) is the correct explanation of (A)',
        B: 'Both (A) and (R) are true but (R) is NOT the correct explanation of (A)',
        C: '(A) is true but (R) is false',
        D: '(A) is false but (R) is true',
      },
      correctAnswer: 'C',
      explanation: '(A) is true because Criterion-Referenced tests compare student knowledge against an absolute mastery rubric. (R) is false because percentiles and rank distributions are characteristics of Norm-Referenced Assessment (NRT), not Criterion-Referenced Assessment (CRT).',
      difficulty: 'HARD',
    },
    {
      unitNumber: 1,
      questionText: 'In online blended learning, MOOC stands for:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Modular Open Online Certification',
        B: 'Massive Open Online Courses',
        C: 'Mandatory Open Online Curriculum',
        D: 'Multimodal Online Open Classroom',
      },
      correctAnswer: 'B',
      explanation: 'MOOC stands for Massive Open Online Courses, which provide open-access, web-based distance education for unlimited participation worldwide.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Which quadrant of the SWAYAM 4-quadrant pedagogical model provides structured links to simulation labs, open-access research papers, and reference reading lists?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Quadrant I: e-Tutorial',
        B: 'Quadrant II: e-Content',
        C: 'Quadrant III: Web Resources / Open Links',
        D: 'Quadrant IV: Self-Assessment',
      },
      correctAnswer: 'C',
      explanation: 'SWAYAM comprises: Quadrant 1 (Video lectures), Quadrant 2 (Specially prepared reading material / e-Text), Quadrant 3 (Web resources, open links, case studies), and Quadrant 4 (Self-assessment tests, MCQs, and discussion forums).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'Which factor contributes most significantly to emotional resilience and self-efficacy in adult online learners (andragogy)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Continuous authoritarian external supervision',
        B: 'Internal locus of control and self-directed goal orientation',
        C: 'Strict adherence to rote memorization drills',
        D: 'Passive reception of unidirectional lecture broadcasts',
      },
      correctAnswer: 'B',
      explanation: 'Malcolm Knowles’ theory of Andragogy establishes that adult learners thrive through self-direction, internal motivation, self-regulation, and perceived relevance to real-world tasks.',
      difficulty: 'MEDIUM',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 2: RESEARCH APTITUDE (10 Questions: Q11 - Q20)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 2,
      questionText: 'In hypothesis testing, a Type I error (alpha error) occurs when the researcher:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Rejects the null hypothesis ($H_0$) when it is actually true',
        B: 'Fails to reject the null hypothesis ($H_0$) when it is actually false',
        C: 'Rejects the alternative hypothesis ($H_1$) when it is true',
        D: 'Accepts the null hypothesis without running inferential statistics',
      },
      correctAnswer: 'A',
      explanation: 'A Type I error ($\alpha$) is the false positive decision of rejecting a true null hypothesis. Conversely, a Type II error ($\beta$) is the false negative of failing to reject a false null hypothesis.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'Which qualitative research design is explicitly focused on generating a substantive theory grounded inductively in empirical field data through constant comparative analysis?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Phenomenological Study',
        B: 'Grounded Theory (Glaser and Strauss)',
        C: 'Historical Historiography',
        D: 'Descriptive Survey Design',
      },
      correctAnswer: 'B',
      explanation: 'Grounded Theory (developed by Barney Glaser and Anselm Strauss) develops theory inductively from systematically gathered and analyzed qualitative data using open, axial, and selective coding.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'Which of the following probability sampling techniques ensures that heterogeneous subgroups in the target population are proportionally represented in the drawn sample?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Snowball sampling',
        B: 'Stratified random sampling',
        C: 'Purposive judgmental sampling',
        D: 'Quota sampling',
      },
      correctAnswer: 'B',
      explanation: 'Stratified Random Sampling divides a heterogeneous population into homogeneous mutually exclusive strata (e.g. by gender, region, income) and samples randomly within each stratum.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'A researcher wants to study the immediate practical impact of a new remedial reading intervention to solve a specific classroom literacy bottleneck in a rural school. What type of research is this?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Fundamental / Pure Research',
        B: 'Action Research (Kurt Lewin cycle)',
        C: 'Ex-post Facto Research',
        D: 'Historical Epistemological Research',
      },
      correctAnswer: 'B',
      explanation: 'Action Research (Plan $\\rightarrow$ Act $\\rightarrow$ Observe $\\rightarrow$ Reflect) is specifically conducted by practitioners to diagnose and solve immediate local operational problems in specific institutional settings.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'According to UGC (Promotion of Academic Integrity and Prevention of Plagiarism in Higher Educational Institutions) Regulations, 2018, Level 2 Plagiarism refers to similarities of:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Similarities up to 10%',
        B: 'Similarities above 10% to 40%',
        C: 'Similarities above 40% to 60%',
        D: 'Similarities above 60%',
      },
      correctAnswer: 'C',
      explanation: 'UGC 2018 Plagiarism Regulations define: Level 0 (up to 10% - minor), Level 1 (10% to 40%), Level 2 (40% to 60% - penalty: debarment from publishing/submitting for 1 year), Level 3 (above 60% - cancellation of registration).',
      difficulty: 'HARD',
    },
    {
      unitNumber: 2,
      questionText: 'In scientific research methodology, the epistemological stance that social reality can and should be measured using objective, empirical, value-free, and quantitative methods is known as:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Positivism',
        B: 'Post-Modern Hermeneutics',
        C: 'Constructivism',
        D: 'Critical Deconstruction',
      },
      correctAnswer: 'A',
      explanation: 'Positivism (associated with Auguste Comte) holds that objective truth and causal universal laws can be observed and verified mathematically through empirical, quantitative measurement.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'Which citation style uses parenthetical author-date format in the body text (e.g., Sharma, 2023) and is most widely adopted in the social and behavioural sciences?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Modern Language Association (MLA)',
        B: 'American Psychological Association (APA)',
        C: 'Chicago Manual of Style (Notes & Bibliography)',
        D: 'IEEE Reference Format',
      },
      correctAnswer: 'B',
      explanation: 'The APA style uses the author-date in-text citation format (Author, Year), while MLA primarily uses author-page format (Author Page) and Chicago often uses footnotes/endnotes.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'In an experimental study evaluating a memory drug, the researcher unknowingly exhibits subtle behavioral cues that communicate expectations to participants, altering results. What methodological safeguard eliminates this?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Double-blind randomized experimental design',
        B: 'Post-hoc subjective retrospection',
        C: 'Convenience snowball recruiting',
        D: 'Unstructured narrative interrogation',
      },
      correctAnswer: 'A',
      explanation: 'A Double-Blind procedure—where neither the research participants nor the experimenters administering the intervention know who is in the control or experimental group—eliminates both experimenter expectancy bias and placebo effects.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'Which research metric represents the number of citations a paper receives in a specific period divided by the total number of citable articles published by that journal in the preceding two years?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Journal Impact Factor (JIF)',
        B: 'Hirsch Index (h-index)',
        C: 'Eigenfactor Score',
        D: 'i10-index',
      },
      correctAnswer: 'A',
      explanation: 'Journal Impact Factor (Clarivate Web of Science) is calculated as the total citations in year $Y$ to articles published in years $Y-1$ and $Y-2$, divided by the total number of citable articles published in $Y-1$ and $Y-2$.',
      difficulty: 'HARD',
    },
    {
      unitNumber: 2,
      questionText: 'A variable that is not the primary independent variable but unintentionally varies systematically with the independent variable, thereby obscuring the true causal inference, is called a:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Confounding variable',
        B: 'Categorical dependent variable',
        C: 'Manipulated treatment variable',
        D: 'Latent construct',
      },
      correctAnswer: 'A',
      explanation: 'A confounding variable is an extraneous variable that correlates with both the independent and dependent variables, creating a spurious relationship and compromising internal validity.',
      difficulty: 'MEDIUM',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 3: COMPREHENSION (10 Questions: Q21 - Q30)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 3,
      contextParagraph: 'Academic integrity is the cornerstone of scholarly inquiry and the foundation upon which scientific progress is built. When researchers fabricate empirical data, falsify methodologies, or plagiarize the conceptual breakthroughs of peers, they do not merely commit individual infractions; they poison the collective knowledge ecosystem. Reproducibility crises in modern science stem largely from inadequate peer review, publish-or-perish pressures, and a failure to disclose conflicts of interest. Institutional mechanisms must therefore evolve beyond punitive deterrence towards creating cultures of mentoring, open-science repositories, transparent pre-registration of analytical hypotheses, and rigorous ethical compliance.',
      questionText: 'According to the passage, what constitutes the fundamental consequence of scholarly misconduct such as data fabrication and plagiarism?',
      questionType: 'Direct MCQ',
      options: {
        A: 'It exclusively results in the loss of individual university funding',
        B: 'It damages and corrupts the collective knowledge ecosystem',
        C: 'It completely halts the operation of academic publishers',
        D: 'It permanently eliminates the necessity for empirical peer review',
      },
      correctAnswer: 'B',
      explanation: 'The passage explicitly states that such acts "poison the collective knowledge ecosystem", extending harm far beyond individual penalties.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      contextParagraph: 'Academic integrity is the cornerstone of scholarly inquiry and the foundation upon which scientific progress is built. When researchers fabricate empirical data, falsify methodologies, or plagiarize the conceptual breakthroughs of peers, they do not merely commit individual infractions; they poison the collective knowledge ecosystem. Reproducibility crises in modern science stem largely from inadequate peer review, publish-or-perish pressures, and a failure to disclose conflicts of interest. Institutional mechanisms must therefore evolve beyond punitive deterrence towards creating cultures of mentoring, open-science repositories, transparent pre-registration of analytical hypotheses, and rigorous ethical compliance.',
      questionText: 'Which systemic pressure is identified in the passage as a major contributor to the modern reproducibility crisis?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Excessive open-access repository creation',
        B: 'Publish-or-perish institutional culture and inadequate peer review',
        C: 'Mandatory pre-registration of scientific trial hypotheses',
        D: 'Over-reliance on qualitative field methodologies',
      },
      correctAnswer: 'B',
      explanation: 'The passage identifies "inadequate peer review, publish-or-perish pressures, and a failure to disclose conflicts of interest" as primary causes.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      contextParagraph: 'Academic integrity is the cornerstone of scholarly inquiry and the foundation upon which scientific progress is built. When researchers fabricate empirical data, falsify methodologies, or plagiarize the conceptual breakthroughs of peers, they do not merely commit individual infractions; they poison the collective knowledge ecosystem. Reproducibility crises in modern science stem largely from inadequate peer review, publish-or-perish pressures, and a failure to disclose conflicts of interest. Institutional mechanisms must therefore evolve beyond punitive deterrence towards creating cultures of mentoring, open-science repositories, transparent pre-registration of analytical hypotheses, and rigorous ethical compliance.',
      questionText: 'What proactive transformation do academic institutions need to prioritize according to the author?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Relying exclusively on retroactive legal punishment',
        B: 'Fostering open-science repositories, mentoring, and hypothesis pre-registration',
        C: 'Eliminating all forms of international collaborative publishing',
        D: 'Privatizing university ethics review boards',
      },
      correctAnswer: 'B',
      explanation: 'The author advocates moving beyond punitive deterrence towards mentoring, open-science repositories, transparent pre-registration of hypotheses, and ethical compliance.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      contextParagraph: 'Digital pedagogical technologies have redefined the epistemological boundaries of classroom education. The transition from monolithic chalk-and-talk methods to modular, interactive learning architectures democratizes access to elite instructional materials. However, technological ubiquity carries a severe cognitive shadow: digital distraction, superficial multitasking, fragmentation of sustained attention spans, and algorithmic echo chambers. Without structured metacognitive training, students often conflate instantaneous information retrieval with genuine deep conceptual synthesis. True digital literacy therefore requires not just hardware access, but the cultivation of critical discernment and reflective cognitive endurance.',
      questionText: 'According to the author, what critical distinction do students often fail to recognize in digital learning environments?',
      questionType: 'Direct MCQ',
      options: {
        A: 'The difference between hardware specifications and bandwidth',
        B: 'The difference between rapid information retrieval and deep conceptual synthesis',
        C: 'The boundary between open-source software and proprietary licenses',
        D: 'The distinction between synchronous and asynchronous servers',
      },
      correctAnswer: 'B',
      explanation: 'The passage expressly notes that "students often conflate instantaneous information retrieval with genuine deep conceptual synthesis."',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      contextParagraph: 'Digital pedagogical technologies have redefined the epistemological boundaries of classroom education. The transition from monolithic chalk-and-talk methods to modular, interactive learning architectures democratizes access to elite instructional materials. However, technological ubiquity carries a severe cognitive shadow: digital distraction, superficial multitasking, fragmentation of sustained attention spans, and algorithmic echo chambers. Without structured metacognitive training, students often conflate instantaneous information retrieval with genuine deep conceptual synthesis. True digital literacy therefore requires not just hardware access, but the cultivation of critical discernment and reflective cognitive endurance.',
      questionText: 'What does genuine "digital literacy" demand beyond mere access to hardware and connectivity?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Proficiency in writing proprietary binary code',
        B: 'Critical discernment, metacognitive training, and reflective cognitive endurance',
        C: 'Unrestricted consumption of unverified social media feeds',
        D: 'Complete avoidance of all online instructional platforms',
      },
      correctAnswer: 'B',
      explanation: 'The passage concludes that true digital literacy requires "critical discernment and reflective cognitive endurance" alongside metacognitive training.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'In reading comprehension strategy, the technique of reading rapidly through a text to locate a specific piece of information (such as a date, name, or statistic) is called:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Skimming',
        B: 'Scanning',
        C: 'Critical deconstruction',
        D: 'Extensive reading',
      },
      correctAnswer: 'B',
      explanation: 'Scanning is reading quickly to find specific targeted details (names, dates, figures), whereas skimming is reading quickly to grasp the general gist or main idea of the entire passage.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'When an author implies a conclusion without stating it directly, the reader must make an:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Inference',
        B: 'Interpolation',
        C: 'Anecdote',
        D: 'Alliteration',
      },
      correctAnswer: 'A',
      explanation: 'An inference is a logical deduction or conclusion reached on the basis of evidence and reasoning from facts and context provided in the text.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'Which reading strategy involves generating questions before reading, actively reading to find answers, and summarizing key takeaways in one\'s own words?',
      questionType: 'Direct MCQ',
      options: {
        A: 'SQ3R Method (Survey, Question, Read, Recite, Review)',
        B: 'Passive Linear Scanning',
        C: 'Rote Phonetic Repetition',
        D: 'Blind Skimming',
      },
      correctAnswer: 'A',
      explanation: 'The SQ3R method (developed by Francis P. Robinson) stands for Survey, Question, Read, Recite, Review, and is a proven active reading comprehension framework.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'In evaluative reading, determining whether an author\'s argument is biased requires examining:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Only the length of the bibliography',
        B: 'The tone of language, omission of counter-evidence, and underlying assumptions',
        C: 'The font size and margins of the published journal',
        D: 'The speed at which the reader scans the paragraphs',
      },
      correctAnswer: 'B',
      explanation: 'Detecting author bias involves analyzing loaded language, unbalanced presentation of opposing evidence, presuppositions, and selective data reporting.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'A passage that presents events in the exact chronological sequence in which they occurred employs which organizational pattern?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Spatial order',
        B: 'Temporal / Chronological order',
        C: 'Cause and effect',
        D: 'Problem and solution',
      },
      correctAnswer: 'B',
      explanation: 'Temporal or chronological organizational patterns arrange ideas and historical events sequentially according to time of occurrence.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 4: COMMUNICATION (10 Questions: Q31 - Q40)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 4,
      questionText: 'In the Shannon and Weaver Mathematical Model of Communication, what element is identified as any unwanted disturbance that interferes with or distorts the signal along the channel?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Entropy',
        B: 'Noise',
        C: 'Redundancy',
        D: 'Transducer',
      },
      correctAnswer: 'B',
      explanation: 'Shannon and Weaver introduced the concept of "Noise" as any physical, physiological, psychological, or semantic interference that degrades signal transmission across the channel.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'Communication with oneself, including internal cognitive reflection, silent self-talk, and prayer, is termed:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Interpersonal communication',
        B: 'Intrapersonal communication',
        C: 'Mass communication',
        D: 'Group dynamic communication',
      },
      correctAnswer: 'B',
      explanation: 'Intrapersonal communication refers to communication that takes place within an individual\'s own mind (self-talk, introspection, conceptualization).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'Which study of non-verbal communication examines how individuals unconsciously use interpersonal space, physical distance, and territoriality during social interaction?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Kinesics',
        B: 'Proxemics (Edward T. Hall)',
        C: 'Haptics',
        D: 'Chronemics',
      },
      correctAnswer: 'B',
      explanation: 'Proxemics (coined by anthropologist Edward T. Hall) is the study of human spatial zones (intimate, personal, social, public distance) in communication.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'In effective classroom communication, "paralanguage" refers to:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Written grammatical syntax and vocabulary choice',
        B: 'Vocal tone, pitch, rate, volume, and rhythm accompanying speech',
        C: 'The physical architecture of classroom desks',
        D: 'Computer-mediated digital emojis',
      },
      correctAnswer: 'B',
      explanation: 'Paralanguage (vocalics) encompasses the non-verbal vocal cues that accompany spoken words—including pitch, intonation, volume, tempo, and vocal inflections.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'When a listener selectively attends only to information that confirms their existing preconceptions while ignoring conflicting facts, what communication barrier is operating?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Physiological hearing impairment',
        B: 'Psychological filter / Confirmation bias',
        C: 'Semantic jargon ambiguity',
        D: 'Electromagnetic channel static',
      },
      correctAnswer: 'B',
      explanation: 'Psychological barriers such as confirmation bias, selective perception, and prejudice distort objective decoding of messages to fit existing belief systems.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'Match List I (Communication Concept) with List II (Key Meaning):\nList I:\n(a) Kinesics\n(b) Haptics\n(c) Chronemics\n(d) Oculesics\nList II:\n(1) Communication through touch\n(2) Communication through body posture, gestures, and facial expressions\n(3) Communication through eye contact and gaze behavior\n(4) Communication through the perception and structuring of time\nChoose the correct code:',
      questionType: 'Matching',
      options: {
        A: '(a)-(2), (b)-(1), (c)-(4), (d)-(3)',
        B: '(a)-(1), (b)-(2), (c)-(3), (d)-(4)',
        C: '(a)-(3), (b)-(4), (c)-(1), (d)-(2)',
        D: '(a)-(4), (b)-(3), (c)-(2), (d)-(1)',
      },
      correctAnswer: 'A',
      explanation: 'Kinesics = body language (2); Haptics = touch (1); Chronemics = time usage (4); Oculesics = eye behavior (3).',
      difficulty: 'HARD',
    },
    {
      unitNumber: 4,
      questionText: 'The concept of the "Global Village" in mass media and communication theory was originated by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Marshall McLuhan',
        B: 'Wilbur Schramm',
        C: 'Harold Lasswell',
        D: 'Denis McQuail',
      },
      correctAnswer: 'A',
      explanation: 'Marshall McLuhan coined "Global Village" and "The medium is the message" in understanding how electronic media collapse spatial and temporal barriers worldwide.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'In organizational communication, horizontal (lateral) communication flows primarily between:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Superiors and their direct subordinates',
        B: 'Peers or colleagues at the same hierarchical tier/level',
        C: 'External vendors and board of directors',
        D: 'Junior interns and supreme executive authorities',
      },
      correctAnswer: 'B',
      explanation: 'Horizontal communication occurs laterally among peers, department heads, or colleagues at equivalent administrative or operational levels.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'Which 7 Cs of effective communication principle asserts that a message must contain all necessary facts and information required for the receiver to take informed action?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Conciseness',
        B: 'Completeness',
        C: 'Courtesy',
        D: 'Concreteness',
      },
      correctAnswer: 'B',
      explanation: 'Completeness ensures that the message conveys all relevant details, leaving no questions unanswered so the recipient can make sound decisions.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'Assertion (A): Synchronous communication tools require sender and receiver to be present in real-time interaction.\nReason (R): Email discussion boards and podcast archives are quintessential examples of synchronous communication.\nIn light of the above, choose the correct answer:',
      questionType: 'Assertion Reasoning',
      options: {
        A: 'Both (A) and (R) are true and (R) is the correct explanation of (A)',
        B: 'Both (A) and (R) are true but (R) is NOT the correct explanation of (A)',
        C: '(A) is true but (R) is false',
        D: '(A) is false but (R) is true',
      },
      correctAnswer: 'C',
      explanation: '(A) is true because synchronous communication (live video call, chat) occurs in real time. (R) is false because emails, forums, and recorded podcasts are asynchronous communication tools.',
      difficulty: 'MEDIUM',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 5: MATHEMATICAL REASONING AND APTITUDE (10 Questions: Q41 - Q50)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 5,
      questionText: 'Find the next number in the sequence: $2, 6, 12, 20, 30, 42, \\dots$',
      questionType: 'Direct MCQ',
      options: {
        A: '$52$',
        B: '$56$',
        C: '$60$',
        D: '$64$',
      },
      correctAnswer: 'B',
      explanation: 'The difference between consecutive terms increases by 2: $6-2=4, 12-6=6, 20-12=8, 30-20=10, 42-30=12$. Next term is $42 + 14 = 56$ (or $n(n+1)$ where for $n=7$, $7 \\times 8 = 56$).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'A train 180 meters long crosses a stationary platform 320 meters long in 25 seconds. What is the speed of the train in km/h?',
      questionType: 'Direct MCQ',
      options: {
        A: '$64\\text{ km/h}$',
        B: '$72\\text{ km/h}$',
        C: '$80\\text{ km/h}$',
        D: '$90\\text{ km/h}$',
      },
      correctAnswer: 'B',
      explanation: 'Total distance = $180 + 320 = 500\\text{ m}$. Speed = $500\\text{ m} / 25\\text{ s} = 20\\text{ m/s}$. Converting to km/h: $20 \\times (18/5) = 72\\text{ km/h}$.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'If 12 men can complete a research archiving project in 15 days working 8 hours a day, how many days will 18 men take to complete the same project working 10 hours a day?',
      questionType: 'Direct MCQ',
      options: {
        A: '$6\\text{ days}$',
        B: '$8\\text{ days}$',
        C: '$10\\text{ days}$',
        D: '$12\\text{ days}$',
      },
      correctAnswer: 'B',
      explanation: 'Using $M_1 D_1 H_1 = M_2 D_2 H_2$: $12 \\times 15 \\times 8 = 18 \\times D_2 \\times 10 \\implies 1440 = 180 D_2 \\implies D_2 = 1440 / 180 = 8\\text{ days}$.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'The average age of a group of 30 students is 16 years. When the teacher\'s age is included, the average age of the whole group increases by 1 year. What is the teacher\'s age?',
      questionType: 'Direct MCQ',
      options: {
        A: '$45\\text{ years}$',
        B: '$47\\text{ years}$',
        C: '$49\\text{ years}$',
        D: '$51\\text{ years}$',
      },
      correctAnswer: 'B',
      explanation: 'Initial total sum = $30 \\times 16 = 480$. New average with 31 people = $17$. New total sum = $31 \\times 17 = 527$. Teacher\'s age = $527 - 480 = 47\\text{ years}$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'A shopkeeper marks an item 40% above the cost price and allows a discount of 20% on the marked price. What is the shopkeeper\'s net profit percentage?',
      questionType: 'Direct MCQ',
      options: {
        A: '$12\\%$',
        B: '$15\\%$',
        C: '$18\\%$',
        D: '$20\\%$',
      },
      correctAnswer: 'A',
      explanation: 'Let $\\text{CP} = 100$. $\\text{MP} = 140$. $\\text{Discount} = 20\\% \\text{ of } 140 = 28$. $\\text{SP} = 140 - 28 = 112$. Net profit percentage = $(112 - 100) = 12\\%$.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'In a certain code language, if "SCHOLAR" is coded as "TDIPMBS", how will "STUDENT" be coded in that same language?',
      questionType: 'Direct MCQ',
      options: {
        A: 'TUVEFOU',
        B: 'TUVDEOU',
        C: 'TUVEEOS',
        D: 'RSTCDMS',
      },
      correctAnswer: 'A',
      explanation: 'Each letter is shifted forward by $+1$: S$\\rightarrow$T, T$\\rightarrow$U, U$\\rightarrow$V, D$\\rightarrow$E, E$\\rightarrow$F, N$\\rightarrow$O, T$\\rightarrow$U. Result = "TUVEFOU".',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'A sum of ₹10,000 invested at compound interest compounded annually amounts to ₹12,100 in 2 years. What is the annual interest rate?',
      questionType: 'Direct MCQ',
      options: {
        A: '$8\\%$',
        B: '$10\\%$',
        C: '$11\\%$',
        D: '$12\\%$',
      },
      correctAnswer: 'B',
      explanation: '$A = P(1 + r/100)^t \\implies 12100 = 10000(1 + r/100)^2 \\implies 1.21 = (1 + r/100)^2 \\implies 1.1 = 1 + r/100 \\implies r = 10\\%$.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'Pointing to a photograph, Rohit said, "She is the only daughter of the father of my sister\'s mother." How is the woman in the photograph related to Rohit?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Sister',
        B: 'Mother',
        C: 'Grandmother',
        D: 'Aunt',
      },
      correctAnswer: 'B',
      explanation: 'Rohit\'s sister\'s mother is Rohit\'s mother. The father of Rohit\'s mother is Rohit\'s maternal grandfather. The only daughter of Rohit\'s maternal grandfather is Rohit\'s mother.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'Two numbers are in the ratio $3:5$. If 8 is added to each number, the ratio becomes $2:3$. What is the smaller number?',
      questionType: 'Direct MCQ',
      options: {
        A: '$18$',
        B: '$24$',
        C: '$30$',
        D: '$40$',
      },
      correctAnswer: 'B',
      explanation: 'Let numbers be $3x$ and $5x$. $(3x + 8) / (5x + 8) = 2/3 \\implies 3(3x + 8) = 2(5x + 8) \\implies 9x + 24 = 10x + 16 \\implies x = 8$. Smaller number = $3 \\times 8 = 24$.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'A person travels from city A to city B at an average speed of $60\\text{ km/h}$ and returns from B to A along the same route at $40\\text{ km/h}$. What is the average speed for the entire round trip?',
      questionType: 'Direct MCQ',
      options: {
        A: '$48\\text{ km/h}$',
        B: '$50\\text{ km/h}$',
        C: '$52\\text{ km/h}$',
        D: '$54\\text{ km/h}$',
      },
      correctAnswer: 'A',
      explanation: 'Average speed for equal distances = $\\frac{2xy}{x+y} = \\frac{2 \\times 60 \\times 40}{60 + 40} = \\frac{4800}{100} = 48\\text{ km/h}$.',
      difficulty: 'MEDIUM',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 6: LOGICAL REASONING (10 Questions: Q51 - Q60)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 6,
      questionText: 'In classical Aristotelian Square of Opposition, what is the logical relationship between categorical proposition A ("All philosophers are scholars") and proposition E ("No philosophers are scholars")?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Contradictory',
        B: 'Contrary',
        C: 'Subcontrary',
        D: 'Subalternation',
      },
      correctAnswer: 'B',
      explanation: 'A and E universal propositions are "Contrary". They cannot both be true simultaneously, although they can both be false.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 6,
      questionText: 'In Indian Classical Nyaya Epistemology (Pramana), which pramana refers to cognition of an unperceived object through perception of an invariable sign (Linga/Hetu) associated with it (Sadhya)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Pratyaksha (Direct Perception)',
        B: 'Anumana (Inference)',
        C: 'Upamana (Comparison / Analogy)',
        D: 'Shabda (Verbal Testimony)',
      },
      correctAnswer: 'B',
      explanation: 'Anumana (Inference) is knowing the unperceived probandum (Sadhya - fire) on the hill (Paksha) through the perceived probans/mark (Hetu/Linga - smoke) based on invariable universal concomitance (Vyapti).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 6,
      questionText: 'In Nyaya syllogism (Pancavayava), which step corresponds to the statement: "Because of smoke" (Dhumat)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Pratijna (Proposition)',
        B: 'Hetu (Ground / Reason)',
        C: 'Udaharana (Universal statement with example)',
        D: 'Upanaya (Application)',
      },
      correctAnswer: 'B',
      explanation: 'The 5 members are: (1) Pratijna ("The hill has fire"), (2) Hetu ("Because it has smoke"), (3) Udaharana ("Wherever there is smoke, there is fire, as in a hearth"), (4) Upanaya ("This hill has smoke which is invariably associated with fire"), (5) Nigamana ("Therefore, the hill has fire").',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 6,
      questionText: 'Which formal or informal logical fallacy is committed in the following argument: "Everyone in my university uses this brand of smartphone; therefore, it must be the objectively highest quality phone ever manufactured"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Argumentum ad Misericordiam (Appeal to Pity)',
        B: 'Argumentum ad Populum (Bandwagon / Appeal to the People)',
        C: 'Argumentum ad Hominem (Attack on the Person)',
        D: 'Post Hoc Ergo Propter Hoc',
      },
      correctAnswer: 'B',
      explanation: 'Argumentum ad Populum (Bandwagon fallacy) concludes a proposition must be true or superior simply because many or most people believe or practice it.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'In classical Indian Nyaya logic, the fallacy of "Savyabhicara" (irregular middle / unproved reason) is an example of which category of Hetvabhasa?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Asiddha (Unfounded reason)',
        B: 'Savyabhicara (Inconclusive / Discrepant reason)',
        C: 'Satpratipaksha (Counterbalanced reason)',
        D: 'Badhita (Contradicted by stronger perception)',
      },
      correctAnswer: 'B',
      explanation: 'Savyabhicara is the fallacy of the irregular or inconclusive middle term (where the Hetu is found in both positive instances and counter-instances).',
      difficulty: 'HARD',
    },
    {
      unitNumber: 6,
      questionText: 'If the proposition "All diamonds are precious gems" is assumed to be TRUE, what can be immediately inferred regarding the truth-value of the subaltern proposition "Some diamonds are precious gems" (I)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'It must be True',
        B: 'It must be False',
        C: 'It is Undetermined / Doubtful',
        D: 'It is Self-contradictory',
      },
      correctAnswer: 'A',
      explanation: 'In the Square of Opposition under Subalternation: Truth flows downward (If Universal A is True, Particular I must be True).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'Which classical Indian school of philosophy accepts ONLY Pratyaksha (Perception) as the single valid source of knowledge (Pramana), completely rejecting Anumana, Shabda, and Upamana?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Nyaya',
        B: 'Carvaka (Lokayata Materialism)',
        C: 'Advaita Vedanta',
        D: 'Samkhya',
      },
      correctAnswer: 'B',
      explanation: 'Carvaka (Lokayata) is radical empiricist materialism, accepting only direct sensory perception (Pratyaksha) as valid and rejecting inference and scriptural authority.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'What is the logical equivalent obtained by converting the categorical proposition "No reptiles are warm-blooded animals" (E)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'No warm-blooded animals are reptiles (E)',
        B: 'All warm-blooded animals are reptiles (A)',
        C: 'Some warm-blooded animals are reptiles (I)',
        D: 'Some reptiles are not warm-blooded (O)',
      },
      correctAnswer: 'A',
      explanation: 'The Conversion of an E proposition ("No S is P") is valid by simple conversion to "No P is S" ("No warm-blooded animals are reptiles").',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 6,
      questionText: 'In Nyaya philosophy, the non-apprehension or cognitive absence of an object (such as "there is no jar on the ground") is accepted as an independent sixth pramana (Anupalabdhi) by which school?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Bhatta Mimamsa and Advaita Vedanta',
        B: 'Nyaya and Vaisheshika',
        C: 'Buddhism and Carvaka',
        D: 'Jainism and Samkhya',
      },
      correctAnswer: 'A',
      explanation: 'Anupalabdhi (Non-perception) as an independent sixth pramana is accepted by Kumarila Bhatta\'s Mimamsa school and Shankaracharya\'s Advaita Vedanta school.',
      difficulty: 'HARD',
    },
    {
      unitNumber: 6,
      questionText: 'The fallacy of "Petitio Principii" is commonly known in informal logic as:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Begging the Question (Circular Reasoning)',
        B: 'Straw Man Fallacy',
        C: 'Red Herring Fallacy',
        D: 'Appeal to Ignorance',
      },
      correctAnswer: 'A',
      explanation: 'Petitio Principii (Begging the Question) occurs when an argument\'s premises assume the truth of the conclusion instead of supporting it independently.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 7: DATA INTERPRETATION (10 Questions: Q61 - Q70)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 7,
      contextParagraph: 'Consider the following table showing enrollment of students in 5 academic departments of a central university across 2022 and 2023:\n- Science: 2022 = 400, 2023 = 480\n- Arts: 2022 = 500, 2023 = 550\n- Commerce: 2022 = 300, 2023 = 390\n- Engineering: 2022 = 600, 2023 = 660\n- Management: 2022 = 200, 2023 = 260',
      questionText: 'Which academic department recorded the highest percentage increase in student enrollment from 2022 to 2023?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Science',
        B: 'Commerce',
        C: 'Management',
        D: 'Arts',
      },
      correctAnswer: 'B',
      explanation: 'Percentage increases:\n- Science: $(80/400) \\times 100 = 20\\%$\n- Arts: $(50/500) \\times 100 = 10\\%$\n- Commerce: $(90/300) \\times 100 = 30\\%$\n- Engineering: $(60/600) \\times 100 = 10\\%$\n- Management: $(60/200) \\times 100 = 30\\%$\nBetween Commerce and Management, both grew $30\\%$; Commerce grew by 90 absolute students.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 7,
      contextParagraph: 'Consider the following table showing enrollment of students in 5 academic departments of a central university across 2022 and 2023:\n- Science: 2022 = 400, 2023 = 480\n- Arts: 2022 = 500, 2023 = 550\n- Commerce: 2022 = 300, 2023 = 390\n- Engineering: 2022 = 600, 2023 = 660\n- Management: 2022 = 200, 2023 = 260',
      questionText: 'What is the overall average student enrollment across all 5 departments in the year 2023?',
      questionType: 'Direct MCQ',
      options: {
        A: '$456$',
        B: '$468$',
        C: '$475$',
        D: '$490$',
      },
      correctAnswer: 'B',
      explanation: 'Total in 2023 = $480 + 550 + 390 + 660 + 260 = 2340$. Average = $2340 / 5 = 468$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      contextParagraph: 'Consider the following table showing enrollment of students in 5 academic departments of a central university across 2022 and 2023:\n- Science: 2022 = 400, 2023 = 480\n- Arts: 2022 = 500, 2023 = 550\n- Commerce: 2022 = 300, 2023 = 390\n- Engineering: 2022 = 600, 2023 = 660\n- Management: 2022 = 200, 2023 = 260',
      questionText: 'What is the ratio of total enrollment in Arts and Science combined in 2022 to the total enrollment in Commerce and Management combined in 2023?',
      questionType: 'Direct MCQ',
      options: {
        A: '$18 : 13$',
        B: '$15 : 11$',
        C: '$14 : 9$',
        D: '$20 : 17$',
      },
      correctAnswer: 'A',
      explanation: 'Arts + Science in 2022 = $500 + 400 = 900$. Commerce + Management in 2023 = $390 + 260 = 650$. Ratio = $900 : 650 = 18 : 13$.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 7,
      questionText: 'In a circular pie chart representing a total university research grant expenditure of ₹36 Crores, what angle in degrees represents an expenditure of ₹9 Crores on Laboratory Equipment?',
      questionType: 'Direct MCQ',
      options: {
        A: '$60^\\circ$',
        B: '$75^\\circ$',
        C: '$90^\\circ$',
        D: '$120^\\circ$',
      },
      correctAnswer: 'C',
      explanation: 'Angle = $(9 / 36) \\times 360^\\circ = (1/4) \\times 360^\\circ = 90^\\circ$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'Which statistical graph is specifically suited for displaying continuous frequency distributions grouped into class intervals using adjacent rectangles without gaps?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Bar Chart (discrete categorical)',
        B: 'Histogram',
        C: 'Pie Chart',
        D: 'Scatter Plot',
      },
      correctAnswer: 'B',
      explanation: 'A Histogram represents continuous quantitative data where the area of contiguous bars corresponds to the frequency of data within continuous class intervals.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'If the mean of 5 observations $x, x+3, x+6, x+9, x+12$ is 20, what is the value of $x$?',
      questionType: 'Direct MCQ',
      options: {
        A: '$12$',
        B: '$14$',
        C: '$16$',
        D: '$18$',
      },
      correctAnswer: 'B',
      explanation: 'Sum = $5x + 30$. Mean = $(5x + 30)/5 = x + 6 = 20 \\implies x = 14$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'The median of the sorted dataset $12, 15, 18, 22, 27, 31, 35, 42$ is:',
      questionType: 'Direct MCQ',
      options: {
        A: '$22$',
        B: '$24.5$',
        C: '$27$',
        D: '$25$',
      },
      correctAnswer: 'B',
      explanation: 'With $N = 8$ items, median is the average of the 4th and 5th terms: $(22 + 27)/2 = 49/2 = 24.5$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'In a negatively skewed distribution (skewed to the left), which of the following relationships between measures of central tendency holds true?',
      questionType: 'Direct MCQ',
      options: {
        A: '$\\text{Mean} < \\text{Median} < \\text{Mode}$',
        B: '$\\text{Mode} < \\text{Median} < \\text{Mean}$',
        C: '$\\text{Mean} = \\text{Median} = \\text{Mode}$',
        D: '$\\text{Median} < \\text{Mean} < \\text{Mode}$',
      },
      correctAnswer: 'A',
      explanation: 'In a negatively skewed distribution, extreme low values pull the Mean to the far left: $\\text{Mean} < \\text{Median} < \\text{Mode}$. In positive skew, $\\text{Mean} > \\text{Median} > \\text{Mode}$.',
      difficulty: 'HARD',
    },
    {
      unitNumber: 7,
      questionText: 'Which measure of dispersion is defined as the square root of the arithmetic mean of the squared deviations from the arithmetic mean?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Range',
        B: 'Mean Absolute Deviation',
        C: 'Standard Deviation ($\\sigma$)',
        D: 'Interquartile Range',
      },
      correctAnswer: 'C',
      explanation: 'Standard Deviation (introduced by Karl Pearson in 1893) is $\\sigma = \\sqrt{\\frac{\\sum(X - \\mu)^2}{N}}$.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 7,
      questionText: 'In bivariate correlation analysis, Pearson\'s correlation coefficient $r$ ranges between:',
      questionType: 'Direct MCQ',
      options: {
        A: '$0$ and $+1$',
        B: '$-1$ and $+1$',
        C: '$-\\infty$ and $+\\infty$',
        D: '$-100$ and $+100$',
      },
      correctAnswer: 'B',
      explanation: 'The Pearson correlation coefficient $r$ strictly ranges from $-1.00$ (perfect negative linear correlation) to $+1.00$ (perfect positive linear correlation), with $0$ indicating no linear relationship.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 8: INFORMATION AND COMMUNICATION TECHNOLOGY (ICT) (10 Questions: Q71 - Q80)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 8,
      questionText: 'Which computer storage memory is volatile, fast, directly addressable by the CPU, and loses its contents when power is switched off?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Random Access Memory (RAM)',
        B: 'Read Only Memory (ROM)',
        C: 'Solid State Drive (SSD)',
        D: 'Optical Blu-ray Disc',
      },
      correctAnswer: 'A',
      explanation: 'RAM is primary volatile semiconductor memory that requires continuous electrical power to maintain data state.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'What is the binary representation of decimal number $25_{10}$?',
      questionType: 'Direct MCQ',
      options: {
        A: '$11001_2$',
        B: '$10101_2$',
        C: '$11101_2$',
        D: '$10011_2$',
      },
      correctAnswer: 'A',
      explanation: '$25 = 16 + 8 + 1 = 1 \\cdot 2^4 + 1 \\cdot 2^3 + 0 \\cdot 2^2 + 0 \\cdot 2^1 + 1 \\cdot 2^0 = 11001_2$.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'Which networking protocol is used to translate user-friendly human domain names (such as www.ugc.ac.in) into machine-readable IP addresses?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Dynamic Host Configuration Protocol (DHCP)',
        B: 'Domain Name System (DNS)',
        C: 'Simple Mail Transfer Protocol (SMTP)',
        D: 'File Transfer Protocol (FTP)',
      },
      correctAnswer: 'B',
      explanation: 'DNS (Domain Name System) acts as the phonebook of the internet, mapping human-readable domain names to numerical IP addresses.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'In digital data storage hierarchy, 1 Terabyte (TB) in binary IEC standard is equal to:',
      questionType: 'Direct MCQ',
      options: {
        A: '$1024\\text{ Megabytes (MB)}$',
        B: '$1024\\text{ Gigabytes (GB)}$',
        C: '$1000\\text{ Kilobytes (KB)}$',
        D: '$1024\\text{ Petabytes (PB)}$',
      },
      correctAnswer: 'B',
      explanation: '$1\\text{ TB} = 1024\\text{ GB} = 1024 \\times 1024\\text{ MB} = 2^{40}\\text{ bytes}$.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'Which Government of India national digital initiative provides an interconnected high-speed Gigabit optical fibre network across academic, scientific, and research institutions?',
      questionType: 'Direct MCQ',
      options: {
        A: 'National Knowledge Network (NKN)',
        B: 'DigiLocker',
        C: 'e-ShodhSindhu',
        D: 'National Digital Library (NDLI)',
      },
      correctAnswer: 'A',
      explanation: 'The National Knowledge Network (NKN) is a state-of-the-art multi-gigabit pan-India network connecting knowledge and research institutions.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'Which cybersecurity threat involves masquerading as a trustworthy institutional entity via deceptive emails to fraudulently extract sensitive credentials such as passwords and OTPs?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Phishing',
        B: 'Distributed Denial of Service (DDoS)',
        C: 'Trojan Rootkit',
        D: 'Man-in-the-Middle eavesdropping',
      },
      correctAnswer: 'A',
      explanation: 'Phishing is social engineering deception where fraudulent communications lure victims into divulging sensitive personal credentials.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'What is the full form of the open-access electronic thesis and dissertation repository repository managed by INFLIBNET Centre for Indian universities?',
      questionType: 'Direct MCQ',
      options: {
        A: 'ShodhGanga',
        B: 'ShodhGangotri',
        C: 'ShodhShuddhi',
        D: 'e-PG Pathshala',
      },
      correctAnswer: 'A',
      explanation: 'ShodhGanga is the national reservoir of full-text Indian PhD theses submitted to universities in India, while ShodhGangotri hosts research synopses.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'In computer networking, IPv6 addresses have a bit length of:',
      questionType: 'Direct MCQ',
      options: {
        A: '$32\\text{ bits}$',
        B: '$64\\text{ bits}$',
        C: '$128\\text{ bits}$',
        D: '$256\\text{ bits}$',
      },
      correctAnswer: 'C',
      explanation: 'IPv4 uses 32-bit addresses (allowing ~4.3 billion addresses), while IPv6 uses 128-bit hexadecimal addresses providing $2^{128}$ unique addresses.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'Which audio file format is uncompressed raw waveform audio developed by Microsoft and IBM?',
      questionType: 'Direct MCQ',
      options: {
        A: 'MP3',
        B: 'AAC',
        C: 'WAV',
        D: 'OGG Vorbis',
      },
      correctAnswer: 'C',
      explanation: 'WAV (Waveform Audio File Format) is an uncompressed lossless audio format preserving exact sound waves, whereas MP3 and AAC are lossy compressed formats.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'Assertion (A): Cloud computing allows on-demand network access to a shared pool of configurable computing resources (servers, storage, applications).\nReason (R): In Software as a Service (SaaS), end-users must manually compile operating system kernels on physical client machines.\nIn light of the above statements, choose the correct answer:',
      questionType: 'Assertion Reasoning',
      options: {
        A: 'Both (A) and (R) are true and (R) is the correct explanation of (A)',
        B: 'Both (A) and (R) are true but (R) is NOT the correct explanation of (A)',
        C: '(A) is true but (R) is false',
        D: '(A) is false but (R) is true',
      },
      correctAnswer: 'C',
      explanation: '(A) is the standard NIST definition of Cloud Computing. (R) is false because in SaaS (e.g. Google Docs, Office 365), software applications run entirely in the cloud and are accessed via web browsers without user maintenance of OS kernels.',
      difficulty: 'MEDIUM',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 9: PEOPLE, DEVELOPMENT AND ENVIRONMENT (10 Questions: Q81 - Q90)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 9,
      questionText: 'Under the United Nations 2030 Agenda for Sustainable Development, how many Sustainable Development Goals (SDGs) and associated targets were adopted in 2015?',
      questionType: 'Direct MCQ',
      options: {
        A: '8 Goals and 21 Targets',
        B: '17 Goals and 169 Targets',
        C: '15 Goals and 150 Targets',
        D: '20 Goals and 200 Targets',
      },
      correctAnswer: 'B',
      explanation: 'The UN 2030 Agenda established 17 Sustainable Development Goals (SDGs) and 169 specific targets to succeed the 8 Millennium Development Goals (MDGs).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'Under the National Action Plan on Climate Change (NAPCC) launched by India in 2008, which of the following is NOT one of the 8 Core National Missions?',
      questionType: 'Direct MCQ',
      options: {
        A: 'National Solar Mission',
        B: 'National Mission for Enhanced Energy Efficiency',
        C: 'National Mission on Nuclear Power Modernization',
        D: 'National Mission for Sustaining the Himalayan Ecosystem',
      },
      correctAnswer: 'C',
      explanation: 'The 8 NAPCC Missions are: (1) Solar, (2) Enhanced Energy Efficiency, (3) Sustainable Habitat, (4) Water, (5) Himalayan Ecosystem, (6) Green India, (7) Sustainable Agriculture, and (8) Strategic Knowledge for Climate Change. Nuclear power modernization is not one of them.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'Which international treaty signed in 1987 is universally hailed as the most successful global environmental agreement for phasing out Ozone Depleting Substances (ODSs) such as CFCs?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Kyoto Protocol',
        B: 'Montreal Protocol',
        C: 'Basel Convention',
        D: 'Rotterdam Convention',
      },
      correctAnswer: 'B',
      explanation: 'The Montreal Protocol on Substances that Deplete the Ozone Layer (1987) successfully phased out the production and consumption of chlorofluorocarbons (CFCs) and halons.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'Which secondary air pollutant is formed in the troposphere when Nitrogen Oxides ($NO_x$) and Volatile Organic Compounds (VOCs) react in the presence of solar ultraviolet sunlight (Photochemical Smog)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Carbon Monoxide ($CO$)',
        B: 'Ground-level Ozone ($O_3$) and Peroxyacetyl Nitrate (PAN)',
        C: 'Sulphur Dioxide ($SO_2$)',
        D: 'Lead particulates',
      },
      correctAnswer: 'B',
      explanation: 'Ground-level ozone ($O_3$) and PAN are classic secondary photochemical smog pollutants generated when primary precursors ($NO_x$ and VOCs) react photochemically under sunlight.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'Under the National Air Quality Index (AQI) framework in India, which 8 criteria pollutants are monitored?',
      questionType: 'Direct MCQ',
      options: {
        A: '$PM_{10}, PM_{2.5}, NO_2, SO_2, CO, O_3, NH_3, Pb$',
        B: '$CO_2, CH_4, N_2O, SF_6, HFC, PFC, PM_{10}, SO_2$',
        C: '$PM_{10}, PM_{2.5}, O_2, N_2, CO_2, Argon, Neon, Helium$',
        D: '$SO_2, NO_2, CO_2, Chlorine, Fluorine, Bromine, Iodine, Lead$',
      },
      correctAnswer: 'A',
      explanation: 'CPCB National AQI tracks 8 pollutants: Particulate Matter ($PM_{10}$ and $PM_{2.5}$), Nitrogen Dioxide ($NO_2$), Sulphur Dioxide ($SO_2$), Carbon Monoxide ($CO$), Ozone ($O_3$), Ammonia ($NH_3$), and Lead ($Pb$).',
      difficulty: 'HARD',
    },
    {
      unitNumber: 9,
      questionText: 'The International Solar Alliance (ISA), an intergovernmental treaty-based organization for scaling solar energy, was jointly launched by India and France in 2015 with its global headquarters located at:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Paris, France',
        B: 'Gurugram (Haryana), India',
        C: 'Nairobi, Kenya',
        D: 'Geneva, Switzerland',
      },
      correctAnswer: 'B',
      explanation: 'The International Solar Alliance (ISA) is headquartered at the National Institute of Solar Energy (NISE) campus in Gurugram, Haryana, India.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'Which biogeochemical cycle does NOT have a significant gaseous atmospheric reservoir phase and circulates predominantly through terrestrial rocks and aquatic sediments?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Carbon cycle',
        B: 'Nitrogen cycle',
        C: 'Phosphorus cycle',
        D: 'Oxygen cycle',
      },
      correctAnswer: 'C',
      explanation: 'The phosphorus cycle is a sedimentary biogeochemical cycle because phosphorus exists primarily in mineral deposits, rocks, and ocean sediments without a gaseous atmospheric phase.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'Minamata disease, a neurological disease characterized by severe sensory disturbance and ataxia, is caused by chronic toxic poisoning from water contaminated with:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Cadmium (Itai-Itai disease)',
        B: 'Methylmercury',
        C: 'Arsenic (Blackfoot disease)',
        D: 'Fluoride (Fluorosis)',
      },
      correctAnswer: 'B',
      explanation: 'Minamata disease (first discovered in Minamata Bay, Japan in 1956) was caused by the release of industrial wastewater containing toxic methylmercury which bioaccumulated in marine fish and shellfish.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'What is the targeted total renewable energy generation capacity set by India under its updated Nationally Determined Contributions (NDCs) / COP26 Panchamrit goals for 2030?',
      questionType: 'Direct MCQ',
      options: {
        A: '$175\\text{ GW}$',
        B: '$350\\text{ GW}$',
        C: '$500\\text{ GW}$ non-fossil energy capacity',
        D: '$1000\\text{ GW}$',
      },
      correctAnswer: 'C',
      explanation: 'India announced at COP26 Glasgow that it aims to achieve 500 GW of non-fossil energy capacity by 2030 and meet 50% of its energy requirements from renewable energy.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'Eutrophication in freshwater lakes and water bodies is primarily accelerated by excessive anthropogenic runoff containing high concentrations of:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Nitrates and Phosphates from agricultural fertilizers and untreated sewage',
        B: 'Heavy copper and zinc particulates from mining',
        C: 'Dissolved atmospheric oxygen',
        D: 'Sodium chloride from sea salt',
      },
      correctAnswer: 'A',
      explanation: 'Cultural eutrophication occurs when excessive nutrient loading (nitrogen and phosphorus from fertilizers and detergents) triggers explosive algal blooms, depleting dissolved oxygen and killing aquatic life.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 10: HIGHER EDUCATION SYSTEM (10 Questions: Q91 - Q100)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 10,
      questionText: 'Which ancient Indian seat of higher learning, located in modern-day Bihar, was renowned worldwide for Buddhist scholasticism and had its library called "Dharmaganja" comprising the Ratnasagara, Ratnodadhi, and Ratnaranjaka buildings?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Takshashila (Taxila)',
        B: 'Nalanda Mahavihara',
        C: 'Vikramashila',
        D: 'Valabhi',
      },
      correctAnswer: 'B',
      explanation: 'Nalanda Mahavihara (founded under the Gupta Empire by Kumaragupta I) housed the grand library complex Dharmaganja, comprising the three legendary multi-storey buildings Ratnasagara, Ratnodadhi, and Ratnaranjaka.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'The National Education Policy (NEP) 2020 proposes replacing the existing regulatory architecture with a single overarching apex body named:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Higher Education Commission of India (HECI)',
        B: 'National Council for Higher Education and Research (NCHER)',
        C: 'National Higher Education Regulatory Board (NHERB)',
        D: 'University Grants Commission of Bharat (UGCB)',
      },
      correctAnswer: 'A',
      explanation: 'NEP 2020 envisions setting up the Higher Education Commission of India (HECI) with four independent verticals: NHERC (regulation), NAC (accreditation), HEGC (funding), and GEC (general education / learning outcomes).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'Which landmark historical dispatch of 1854 is universally referred to as the "Magna Carta of English Education in India", recommending the establishment of universities at Calcutta, Bombay, and Madras?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Macaulay\'s Minute of 1835',
        B: 'Wood\'s Despatch of 1854',
        C: 'Hunter Commission Report of 1882',
        D: 'Sadler Commission Report of 1917',
      },
      correctAnswer: 'B',
      explanation: 'Charles Wood\'s Despatch of 1854 laid down the comprehensive blueprint for modern secular education in India and led to the establishment of the Universities of Calcutta, Bombay, and Madras in 1857.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'Under NEP 2020, what is the targeted Gross Enrolment Ratio (GER) in higher education, including vocational education, to be achieved by 2035?',
      questionType: 'Direct MCQ',
      options: {
        A: '$35\\%$',
        B: '$50\\%$',
        C: '$65\\%$',
        D: '$75\\%$',
      },
      correctAnswer: 'B',
      explanation: 'NEP 2020 targets increasing the Gross Enrolment Ratio (GER) in higher education to 50% by 2035 (up from ~27.1% in 2019-20).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'The National Assessment and Accreditation Council (NAAC), responsible for evaluating institutional quality in higher education institutions, is an autonomous body established by UGC with headquarters in:',
      questionType: 'Direct MCQ',
      options: {
        A: 'New Delhi',
        B: 'Bengaluru (Karnataka)',
        C: 'Hyderabad',
        D: 'Pune',
      },
      correctAnswer: 'B',
      explanation: 'NAAC was established in 1994 by the UGC with its headquarters located in Bengaluru, Karnataka.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'Which Government of India framework ranks higher education institutions across India using parameters such as Teaching Learning & Resources (TLR), Research & Professional Practice (RPC), Graduation Outcomes (GO), Outreach & Inclusivity (OI), and Perception (PR)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'National Institutional Ranking Framework (NIRF)',
        B: 'Atal Ranking of Institutions on Innovation Achievements (ARIIA)',
        C: 'NAAC Institutional Grade Metric',
        D: 'AICTE Quality Matrix',
      },
      correctAnswer: 'A',
      explanation: 'NIRF was launched by the Ministry of Education (formerly MHRD) in 2015 to rank universities, colleges, and specialized institutions across 5 objective metric pillars.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'Which Post-Independence commission is formally titled the "University Education Commission (1948-49)" and was chaired by Dr. S. Radhakrishnan?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Radhakrishnan Commission',
        B: 'Mudaliar Commission (Secondary Education, 1952-53)',
        C: 'Kothari Commission (Education & National Development, 1964-66)',
        D: 'National Knowledge Commission (Sam Pitroda, 2005)',
      },
      correctAnswer: 'A',
      explanation: 'The Radhakrishnan Commission (1948-49) was independent India\'s first educational commission, recommending the establishment of the University Grants Commission (UGC).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'Under the Academic Bank of Credits (ABC) envisioned by NEP 2020, what is the primary role of the digital depository?',
      questionType: 'Direct MCQ',
      options: {
        A: 'To issue financial loans to university students at subsidized interest rates',
        B: 'To digitally store, transfer, and redeem academic credits earned from recognized HEIs to facilitate multiple entry and exit pathways',
        C: 'To conduct centralized entrance examinations for all degree programs',
        D: 'To publish copyright licenses for faculty textbooks',
      },
      correctAnswer: 'B',
      explanation: 'The Academic Bank of Credits (ABC) digitally stores credits awarded to students from recognized higher education institutions to enable seamless student mobility and multiple entry-exit options.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'The Kothari Commission (1964-66) famously recommended that public expenditure on education in India should be at least what percentage of the Gross Domestic Product (GDP)?',
      questionType: 'Direct MCQ',
      options: {
        A: '$3\\%$ of GDP',
        B: '$6\\%$ of GDP',
        C: '$10\\%$ of GDP',
        D: '$12\\%$ of GDP',
      },
      correctAnswer: 'B',
      explanation: 'The Kothari Commission (1964-66) famously recommended that India allocate at least 6% of its GDP towards education, a goal reiterated by NEP 1968, NEP 1986, and NEP 2020.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'Which statutory body established under an Act of Parliament in 1987 is responsible for proper planning and coordinated development of the technical and management education system throughout India?',
      questionType: 'Direct MCQ',
      options: {
        A: 'All India Council for Technical Education (AICTE)',
        B: 'National Medical Commission (NMC)',
        C: 'Bar Council of India (BCI)',
        D: 'National Council for Teacher Education (NCTE)',
      },
      correctAnswer: 'A',
      explanation: 'AICTE was given statutory status by an Act of Parliament in 1987 to regulate and coordinate technical, engineering, architectural, and management education in India.',
      difficulty: 'EASY',
    },
  ];

  return {
    subjectCode: '00',
    subjectSlug: 'paper-1',
    mockNumber: 1,
    title: 'General Paper 1 — Mock Test 1: Full Syllabus Simulation (100 Qs)',
    description: 'Authentic 100-question UGC NET General Paper 1 simulation covering all 10 core units: Teaching, Research, Reading Comprehension, Communication, Mathematical Reasoning, Logical Reasoning, DI, ICT, Environment, and Higher Education.',
    accessTier: 'FREE',
    isFreeBenchmark: true,
    questions,
  };
}
