import { MockTestDefinition, RawMockQuestion } from '../common';

export function getPoliticalScienceMockTest(): MockTestDefinition {
  const questions: RawMockQuestion[] = [
    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 1: POLITICAL THEORY (10 Questions: Q1 - Q10)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 1,
      questionText: 'Who formulated the concept of "Justice as Fairness" and the "Original Position" behind the "Veil of Ignorance" in his seminal 1971 work "A Theory of Justice"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'John Rawls',
        B: 'Robert Nozick (author of Anarchy, State, and Utopia)',
        C: 'Michael Sandel (Liberalism and the Limits of Justice)',
        D: 'Michael Walzer (Spheres of Justice)',
      },
      correctAnswer: 'A',
      explanation: 'John Rawls revived normative political philosophy with his principles of justice: Equal Basic Liberties Principle and the Difference Principle (maximizing advantage of least advantaged).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Which political philosopher made the classic distinction between "Negative Liberty" (freedom from external interference) and "Positive Liberty" (capacity and self-realization to act) in his 1958 lecture "Two Concepts of Liberty"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Isaiah Berlin',
        B: 'John Stuart Mill',
        C: 'Charles Taylor',
        D: 'Friedrich Hayek',
      },
      correctAnswer: 'A',
      explanation: 'Isaiah Berlin analyzed how negative liberty protects a sphere of non-interference, whereas positive liberty relates to self-mastery and democratic participation.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'In Marxist political philosophy, who developed the theory of "Cultural Hegemony" explaining how the ruling capitalist class maintains power through civil society institutions and manufactured consent rather than direct coercion?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Antonio Gramsci (Prison Notebooks)',
        B: 'Louis Althusser (Ideological State Apparatuses)',
        C: 'Karl Kautsky',
        D: 'Herbert Marcuse',
      },
      correctAnswer: 'A',
      explanation: 'Antonio Gramsci argued that the bourgeoisie uses cultural hegemony (manufactured common sense via media, schools, churches) to win consent, necessitating a "War of Position" by subaltern classes.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Which libertarian thinker advocated the minimal / "night-watchman state" and rejected redistributive taxation as equivalent to forced labour in "Anarchy, State, and Utopia" (1974)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Robert Nozick',
        B: 'Milton Friedman',
        C: 'Friedrich Hayek',
        D: 'Murray Rothbard',
      },
      correctAnswer: 'A',
      explanation: 'Robert Nozick\'s entitlement theory of justice asserts that any state exceeding the narrow functions of protection against force, theft, and contract breach violates individual rights.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'The communitarian critique of Rawlsian liberalism, arguing that individuals are "encumbered selves" embedded in constitutive community traditions and moral horizons, was formulated by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Michael Sandel, Charles Taylor, Alasdair MacIntyre, and Michael Walzer',
        B: 'Karl Popper and Isaiah Berlin',
        C: 'Michel Foucault and Jacques Derrida',
        D: 'Jürgen Habermas and Hannah Arendt',
      },
      correctAnswer: 'A',
      explanation: 'Communitarians rejected Rawls\'s "unencumbered self", asserting that identity, moral agency, and conceptions of the good are deeply rooted in communal practices.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'Who formulated the theory of "Communicative Action" and the concept of the "Ideal Speech Situation" free from domination in deliberative democracy?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Jürgen Habermas',
        B: 'Theodor Adorno',
        C: 'Max Horkheimer',
        D: 'Walter Benjamin',
      },
      correctAnswer: 'A',
      explanation: 'Jürgen Habermas developed Communicative Rationality, arguing that democratic legitimacy arises from uncoerced deliberative consensus in the public sphere.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'The feminist political declaration "The Personal is Political" (challenging the patriarchal separation of private domestic sphere and public political sphere) emerged prominently during:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Second-Wave Feminism (Carol Hanisch, 1969)',
        B: 'First-Wave Suffragette Movement',
        C: 'Third-Wave Postmodern Feminism',
        D: 'Fourth-Wave Digital Feminism',
      },
      correctAnswer: 'A',
      explanation: 'Second-wave feminism highlighted how power relations, domestic labour, reproductive rights, and violence within the private sphere are fundamentally political issues.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'Which post-structuralist thinker developed the concepts of "Disciplinary Power", "Panopticism", and "Biopolitics / Biopower" in works like "Discipline and Punish" and "The History of Sexuality"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Michel Foucault',
        B: 'Jacques Derrida',
        C: 'Gilles Deleuze',
        D: 'Jean-François Lyotard',
      },
      correctAnswer: 'A',
      explanation: 'Michel Foucault demonstrated how modern power is diffused through knowledge regimes, clinical discourses, surveillance mechanisms, and normalization rather than centralized in sovereign monarchs.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 1,
      questionText: 'In democratic theory, the concept of "Polyarchy" (rule by multiple competing elite minorities and interest groups in open electoral competition) was coined and elaborated by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Robert Dahl (author of Who Governs? and Polyarchy)',
        B: 'Joseph Schumpeter (Capitalism, Socialism and Democracy)',
        C: 'Giovanni Sartori',
        D: 'Arend Lijphart',
      },
      correctAnswer: 'A',
      explanation: 'Robert Dahl defined modern representative democracies as Polyarchies, characterized by high inclusion (universal suffrage) and extensive contestation (free electoral competition).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 1,
      questionText: 'The concept of "Ecological Modernization" and the environmental philosophy of "Deep Ecology" (attributing intrinsic value to all living beings regardless of utility to humans) was founded in 1973 by Norwegian philosopher:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Arne Næss',
        B: 'Murray Bookchin (Social Ecology)',
        C: 'Vandana Shiva (Ecofeminism)',
        D: 'James Lovelock (Gaia Hypothesis)',
      },
      correctAnswer: 'A',
      explanation: 'Arne Næss distinguished between shallow anthropocentric environmentalism and radical biocentric Deep Ecology which respects the richness and diversity of all life forms.',
      difficulty: 'MEDIUM',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 2: POLITICAL THOUGHT (WESTERN & INDIAN) (10 Questions: Q11 - Q20)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 2,
      questionText: 'In Plato\'s "Republic", the ideal state is ruled by Philosopher Kings based on which tri-partite division of the human soul?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Rational / Reason (Gold), Spirited / Courage (Silver), and Appetitive / Desire (Bronze/Iron)',
        B: 'Ego, Superego, and Id',
        C: 'Sattva, Rajas, and Tamas',
        D: 'Monarchy, Aristocracy, and Democracy',
      },
      correctAnswer: 'A',
      explanation: 'Plato mapped justice as harmonious hierarchy where Reason rules with the aid of the spirited Guardian class over the commercial/producing Appetitive class.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'Which political philosopher famously characterized life in the state of nature as "solitary, poor, nasty, brutish, and short" and justified absolute sovereign power in "Leviathan" (1651)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Thomas Hobbes',
        B: 'John Locke (Two Treatises of Government)',
        C: 'Jean-Jacques Rousseau (The Social Contract)',
        D: 'Niccolò Machiavelli (The Prince)',
      },
      correctAnswer: 'A',
      explanation: 'Thomas Hobbes argued that in the pre-political state of nature, the war of all against all (bellum omnium contra omnes) compels rational individuals to surrender rights to an absolute sovereign (Leviathan).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'Who is recognized as the "Father of Classical Liberalism", who posited that governments are established solely to protect the natural rights of "Life, Liberty, and Estate (Property)"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'John Locke',
        B: 'Thomas Hobbes',
        C: 'Adam Smith',
        D: 'Jean-Jacques Rousseau',
      },
      correctAnswer: 'A',
      explanation: 'John Locke formulated limited constitutional government, consent of the governed, and the right to revolution if the government violates fundamental natural property rights.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'Jean-Jacques Rousseau\'s political philosophy asserts that true sovereign freedom consists in obedience to the:',
      questionType: 'Direct MCQ',
      options: {
        A: 'General Will (Volonté Générale)',
        B: 'Will of All (Volonté de Tous)',
        C: 'Will of the Monarchy',
        D: 'Corporate Will of Nobles',
      },
      correctAnswer: 'A',
      explanation: 'Rousseau\'s General Will represents the collective moral interest aiming at the common good, distinct from the "Will of All" which is merely the sum of private selfish interests.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'In "On Liberty" (1859), John Stuart Mill formulated the "Harm Principle" stating that:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The only purpose for which power can be rightfully exercised over any member of a civilized community, against his will, is to prevent harm to others',
        B: 'The state must enforce religious morality on all consenting adults',
        C: 'Majority opinion must always suppress eccentric minority viewpoints',
        D: 'Economic wealth must be equally divided regardless of individual effort',
      },
      correctAnswer: 'A',
      explanation: 'Mill\'s Harm Principle defends absolute sovereignty over one\'s own body and mind for self-regarding actions, permitting state intervention only for other-regarding actions causing harm.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'Which 19th-century German philosopher formulated the Dialectical Idealism asserting that "The State is the march of God in the world" (der Gang Gottes in der Welt)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Georg Wilhelm Friedrich Hegel',
        B: 'Immanuel Kant (Perpetual Peace)',
        C: 'Johann Gottlieb Fichte',
        D: 'Arthur Schopenhauer',
      },
      correctAnswer: 'A',
      explanation: 'Hegel viewed the modern constitutional state as the ultimate ethical realization of Geist (Universal Spirit) reconciling family particularity and civil society egoism.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'In classical Indian political thought, the "Matsya Nyaya" (Law of the Fish) refers to:',
      questionType: 'Direct MCQ',
      options: {
        A: 'A state of absolute anarchy where the strong devour the weak in the absence of Danda and Raja',
        B: 'A maritime treaty system of coastal kingdoms',
        C: 'Monastic rules for Buddhist ascetics',
        D: 'Vedic rules of non-violent fishing',
      },
      correctAnswer: 'A',
      explanation: 'Matsya Nyaya in Kautilya and Manusmriti describes pre-political chaos where big fish eat small fish, justifying the creation of royal sovereign authority (Danda) to enforce Dharma.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'Who propounded the concept of "Radical Humanism" and "Partyless Democracy" after transitioning from revolutionary Marxism to philosophical humanism in India?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Manabendra Nath Roy (M.N. Roy)',
        B: 'Jayaprakash Narayan',
        C: 'Rammanohar Lohia',
        D: 'Aurobindo Ghosh',
      },
      correctAnswer: 'A',
      explanation: 'M.N. Roy founded the Radical Democratic Party, published "New Orientation" and the 22 Theses, advocating decentralized grassroots democracy without political party intermediation.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 2,
      questionText: 'In his 1936 undelivered presidential address "Annihilation of Caste", Dr. B.R. Ambedkar asserted that caste is not merely a division of labour, but a:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Division of labourers (graded inequality without mobility)',
        B: 'Natural biological necessity',
        C: 'Temporary feudal economic stage',
        D: 'Spiritual blessing for societal stability',
      },
      correctAnswer: 'A',
      explanation: 'Ambedkar dismantled orthodox defences of caste, arguing it is an involuntary, hierarchical division of labourers based on religious sanction and graded inequality.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 2,
      questionText: 'Mahatma Gandhi expounded his comprehensive critique of Western industrial civilization, parliamentary government, and railway-driven urbanization in his foundational 1909 Gujarati text:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Hind Swaraj (Indian Home Rule)',
        B: 'My Experiments with Truth',
        C: 'Satyagraha in South Africa',
        D: 'Constructive Programme',
      },
      correctAnswer: 'A',
      explanation: 'Gandhi wrote Hind Swaraj aboard the ship Kildonan Castle, advocating moral Swaraj (self-rule/self-control), village swadeshi, and rejecting modern mechanistic materialism.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 3: INDIAN POLITICAL THOUGHT (10 Questions: Q21 - Q30)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 3,
      questionText: 'In the Shanti Parva of the Mahabharata, the discourse on Rajadharma (the duties and statecraft of kings) is delivered from a bed of arrows to Yudhishthira by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Bhishma Pitamaha',
        B: 'Vidura (author of Vidura Niti)',
        C: 'Dronacharya',
        D: 'Krishna',
      },
      correctAnswer: 'A',
      explanation: 'Bhishma expounds on Rajadharma, Apaddharma, and Mokshadharma in the Shanti Parva, detailing the origin of kingship, taxation, and imperial diplomacy.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In his theory of the "Seven Revolutions" (Sapta Kranti), socialist thinker Rammanohar Lohia advocated simultaneous struggles against which social and economic injustices?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Gender inequality, Caste hierarchy, Colonial racism, Economic exploitation, Imperialist armament, Encroachment on privacy, and Unjust weapons',
        B: 'Capitalism, Feudalism, Imperialism, Fascism, Anarchism, Monarchism, and Oligarchy',
        C: 'Ignorance, Poverty, Disease, Illiteracy, Homelessness, Unemployment, and Corruption',
        D: 'Monarchy, Bureaucracy, Judiciary, Police, Army, Media, and Religion',
      },
      correctAnswer: 'A',
      explanation: 'Lohia\'s Sapta Kranti outlined a comprehensive radical socialist transformation against gender bias, caste oppression, racial imperialism, economic disparity, and state violence.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'Which social reformer from Maharashtra established the "Sharada Sadan" and "Mukti Mission" for young widows and authored "The High-Caste Hindu Woman" (1887)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Pandita Ramabai Saraswati',
        B: 'Savitribai Phule',
        C: 'Tarabai Shinde (author of Stri Purush Tulana)',
        D: 'Anandibai Joshi',
      },
      correctAnswer: 'A',
      explanation: 'Pandita Ramabai was an extraordinary scholar who critically analyzed the oppression of women in upper-caste patriarchal Hinduism and provided pioneering shelter institutions.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'Aurobindo Ghosh conceptualized the nation of India not merely as a territory, but as a living spiritual deity (Bhavani Bharati / Mother India) and developed the political doctrine of:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Passive Resistance (in Bande Mataram, 1907) and Integral Yoga',
        B: 'Scientific Socialism',
        C: 'Radical Utilitarianism',
        D: 'Legal Positivism',
      },
      correctAnswer: 'A',
      explanation: 'Sri Aurobindo formulated the strategy of Passive Resistance (boycott of courts, schools, and foreign goods) before Gandhi and developed the theory of spiritual nationalism.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'Who founded the Dravidian Self-Respect Movement (Suyamariyathai Iyakkam) in 1925 in Tamil Nadu to eliminate Brahminical hegemony, caste oppression, and superstitious rituals?',
      questionType: 'Direct MCQ',
      options: {
        A: 'E.V. Ramasamy (Periyar)',
        B: 'C.N. Annadurai',
        C: 'C. Iyothee Thass',
        D: 'Rettamalai Srinivasan',
      },
      correctAnswer: 'A',
      explanation: 'Periyar E.V. Ramasamy championed radical rationalism, women\'s liberation, anti-Hindi agitations, and social equality through the Self-Respect Movement and Dravidar Kazhagam.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In his landmark work "The Reconstruction of Religious Thought in Islam", which modern Islamic philosopher and poet advocated "Ijtihad" (independent reasoning) and dynamic spiritual reconstruction?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Sir Muhammad Iqbal',
        B: 'Sir Syed Ahmad Khan',
        C: 'Maulana Abul Kalam Azad',
        D: 'Altaf Hussain Hali',
      },
      correctAnswer: 'A',
      explanation: 'Allama Muhammad Iqbal analyzed Islamic philosophy in dialogue with modern Western thinkers like Bergson and Nietzsche, advocating Khudi (Selfhood) and dynamic spiritual evolution.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'Who authored the monumental ideological treatise "Hindutva: Who is a Hindu?" (1923), defining Hindutva through the tripartite matrix of Pitribhumi (Fatherland), Punyabhumi (Holyland), and shared culture?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Vinayak Damodar Savarkar (Veer Savarkar)',
        B: 'K.B. Hedgewar',
        C: 'M.S. Golwalkar',
        D: 'Shyama Prasad Mukherjee',
      },
      correctAnswer: 'A',
      explanation: 'V.D. Savarkar wrote Hindutva while imprisoned in the Andaman Cellular Jail/Ratnagiri, defining the Hindu nation based on shared blood, common civilization, and emotional attachment to the sacred land.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'Maulana Abul Kalam Azad, independent India\'s first Education Minister, established his theological philosophy of universal religious unity and pluralist nationalism in his commentary on the Quran titled:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Tarjuman al-Quran (The Meaning of the Quran)',
        B: 'India Wins Freedom',
        C: 'Ghubar-e-Khatir',
        D: 'Al-Hilal Archives',
      },
      correctAnswer: 'A',
      explanation: 'In "Tarjuman al-Quran", Maulana Azad expounded "Wahdat-e-Deen" (essential unity of all revealed religions) and strongly opposed the partition of India.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 3,
      questionText: 'Which medieval Indian poet-saint belonging to the Nirguna Bhakti movement challenged caste hierarchy, untouchability, and ritualism with his unsparing satirical couplets (Sakhis and Bijak)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Sant Kabir Das',
        B: 'Tulsidas',
        C: 'Surdas',
        D: 'Chaitanya Mahaprabhu',
      },
      correctAnswer: 'A',
      explanation: 'Kabir rejected all institutionalized orthodoxy (both Hindu and Muslim), proclaiming direct mystical devotion to the formless Divine (Nirguna Rama).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 3,
      questionText: 'In his 1974 mass movement in Bihar, Jayaprakash Narayan (JP) called for a "Total Revolution" (Sampoorna Kranti) encompassing which spheres of societal reconstruction?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Social, Economic, Political, Cultural, Ideological, Educational, and Spiritual transformations',
        B: 'Exclusively armed guerrilla warfare against the state',
        C: 'Privatization of all public educational universities',
        D: 'Elimination of parliamentary electoral democracy',
      },
      correctAnswer: 'A',
      explanation: 'JP\'s Total Revolution was a non-violent mass movement targeting corruption, authoritarianism, and systemic decay across 7 dimensions of social life.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 4: COMPARATIVE POLITICAL ANALYSIS (10 Questions: Q31 - Q40)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 4,
      questionText: 'In comparative politics, the "Structural-Functional Approach" which posits that every political system performs input functions (socialization, interest articulation) and output functions (rule making, rule application) was developed by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Gabriel Almond and G. Bingham Powell',
        B: 'David Easton (Input-Output Black Box Model)',
        C: 'Karl Deutsch (Cybernetics / Information Theory)',
        D: 'Harold Lasswell',
      },
      correctAnswer: 'A',
      explanation: 'Almond and Powell\'s structural-functionalism provided a framework to compare diverse modern and traditional political systems across structural performance.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'Which comparative political scientist formulated the theory of "Consociational Democracy" (power-sharing coalitions, mutual veto, proportional representation, and segmental autonomy in deeply divided societies)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Arend Lijphart',
        B: 'Robert Dahl',
        C: 'Samuel P. Huntington',
        D: 'Juan Linz',
      },
      correctAnswer: 'A',
      explanation: 'Arend Lijphart analyzed how plural societies with deep ethnic/religious cleavages (such as the Netherlands, Switzerland, Lebanon) achieve stability through elite power-sharing.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'In "The Third Wave: Democratization in the Late Twentieth Century" (1991), Samuel P. Huntington identified the commencement of the Third Wave of global democratization with which historic event in 1974?',
      questionType: 'Direct MCQ',
      options: {
        A: 'The Carnation Revolution in Portugal (1974)',
        B: 'The Fall of the Berlin Wall (1989)',
        C: 'The End of Apartheid in South Africa (1994)',
        D: 'The Collapse of the Soviet Union (1991)',
      },
      correctAnswer: 'A',
      explanation: 'Huntington traced the Third Wave beginning with Portugal\'s Carnation Revolution in 1974, spreading to Southern Europe, Latin America, Asia, and Eastern Europe.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'Maurice Duverger\'s classic sociological law ("Duverger\'s Law") in electoral systems states that:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The Simple Majority Single-Ballot (First-Past-The-Post) system favours a two-party system',
        B: 'Proportional representation inevitably leads to a single-party dictatorship',
        C: 'Presidential regimes always collapse into military juntas',
        D: 'Bicameral legislatures eliminate coalition governments',
      },
      correctAnswer: 'A',
      explanation: 'Duverger demonstrated through comparative empirical data that FPTP creates mechanical and psychological barriers against third parties, consolidating two-party competition.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'In "Dependency Theory" of underdevelopment (associated with Andre Gunder Frank, Samir Amin, and Fernando Henrique Cardoso), underdevelopment in the Global South is explained as:',
      questionType: 'Direct MCQ',
      options: {
        A: 'A structural condition actively produced by the unequal capitalist extraction of economic surplus by the Core / Metropole from the Periphery / Satellite',
        B: 'A natural traditional stage that countries pass through before modernizing',
        C: 'Solely the result of domestic administrative corruption',
        D: 'A consequence of insufficient integration into global financial markets',
      },
      correctAnswer: 'A',
      explanation: 'Dependency theorists rejected Western modernization theory, demonstrating how colonial and post-colonial global capitalism reproduces "the development of underdevelopment".',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'In comparative constitutional systems, which nation operates an "Unwritten / Uncodified Constitution" grounded in statutes, common law conventions, royal prerogatives, and parliamentary sovereignty?',
      questionType: 'Direct MCQ',
      options: {
        A: 'United Kingdom (UK)',
        B: 'United States of America (USA)',
        C: 'Federal Republic of Germany',
        D: 'France (Fifth Republic)',
      },
      correctAnswer: 'A',
      explanation: 'The United Kingdom possesses an uncodified constitution comprising historical documents (Magna Carta 1215, Bill of Rights 1689), parliamentary acts, judicial precedents, and constitutional conventions.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 4,
      questionText: 'Which type of executive system exists in France under the Fifth Republic Constitution of 1958, featuring a directly elected powerful President alongside a Prime Minister responsible to the National Assembly?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Semi-Presidential Executive (Dual Executive)',
        B: 'Pure Parliamentary Westminster System',
        C: 'Pure Presidential System',
        D: 'Collegial Directorate (Swiss Model)',
      },
      correctAnswer: 'A',
      explanation: 'France combines presidential authority in foreign and defence policy with a prime minister leading the domestic legislative agenda (permitting "Cohabitation" when different parties hold the presidency and assembly).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'In "The Civic Culture" (1963), Gabriel Almond and Sidney Verba identified which three ideal-type political cultures across nations?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Parochial Political Culture, Subject Political Culture, and Participant Political Culture',
        B: 'Capitalist, Socialist, and Mixed Cultures',
        C: 'Authoritarian, Totalitarian, and Democratic Cultures',
        D: 'Traditional, Charismatic, and Rational-Legal Cultures',
      },
      correctAnswer: 'A',
      explanation: 'Almond and Verba analyzed how a balanced Civic Culture (combining participant democratic activism with subject loyalty and parochial attachments) sustains stable democracies.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'Which institutional mechanism allows citizens in Switzerland to propose constitutional amendments directly by gathering a required threshold of 100,000 voter signatures within 18 months?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Popular Initiative (Volksinitiative)',
        B: 'Mandatory Referendum',
        C: 'Recall Election',
        D: 'Plebiscite',
      },
      correctAnswer: 'A',
      explanation: 'Switzerland\'s direct democracy incorporates the Popular Initiative (enabling citizens to amend the Federal Constitution) and the Optional/Mandatory Referendum (vetoing parliamentary legislation).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 4,
      questionText: 'In comparative political economy, Immanuel Wallerstein\'s "World-Systems Theory" divides the capitalist world-economy into which three spatial-economic zones?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Core, Semi-Periphery, and Periphery',
        B: 'First World, Second World, and Third World',
        C: 'North, South, and Equator',
        D: 'Developed, Developing, and Least Developed',
      },
      correctAnswer: 'A',
      explanation: 'Wallerstein showed how the Core extracts surplus value from the Periphery, while the Semi-Periphery acts as an economic buffer with mixed production processes.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 5 & 6: INTERNATIONAL RELATIONS & FOREIGN POLICY (20 Questions: Q41 - Q60)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 5,
      questionText: 'In International Relations, who is considered the father of Classical Realism with his foundational "Six Principles of Political Realism" expounded in "Politics Among Nations" (1948)?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Hans J. Morgenthau',
        B: 'Kenneth Waltz (Theory of International Politics)',
        C: 'E.H. Carr (The Twenty Years\' Crisis)',
        D: 'John Mearsheimer (The Tragedy of Great Power Politics)',
      },
      correctAnswer: 'A',
      explanation: 'Hans Morgenthau asserted that international politics is governed by objective laws rooted in human nature, and that states pursue national interest defined in terms of power.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'Kenneth Waltz\'s "Structural Realism / Neorealism" (1979) asserts that the primary cause of war, conflict, and balance of power in international relations is the:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Anarchic structure of the international system (absence of central global sovereign)',
        B: 'Innate biological aggressive instincts of individual human leaders',
        C: 'Economic conflict between domestic trade unions',
        D: 'Cultural differences between civilizations',
      },
      correctAnswer: 'A',
      explanation: 'Neorealism explains state behaviour through systemic structural anarchy, where self-help is the imperative principle of action for sovereign states seeking survival.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'The "Democratic Peace Theory" (proposing that democratic states rarely or never go to war against one another) is rooted philosophically in which classic 1795 essay by Immanuel Kant?',
      questionType: 'Direct MCQ',
      options: {
        A: '"Perpetual Peace: A Philosophical Sketch" (Zum ewigen Frieden)',
        B: 'Critique of Pure Reason',
        C: 'The Metaphysics of Morals',
        D: 'Idea for a Universal History',
      },
      correctAnswer: 'A',
      explanation: 'Kant argued that a federation of constitutional republics with universal hospitality and commercial interdependence would produce perpetual peace.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 5,
      questionText: 'In Constructivist International Relations theory, which scholar famously asserted that "Anarchy is what states make of it" in his 1992 article and 1999 book "Social Theory of International Politics"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Alexander Wendt',
        B: 'Nicholas Onuf',
        C: 'Martha Finnemore',
        D: 'Friedrich Kratochwil',
      },
      correctAnswer: 'A',
      explanation: 'Alexander Wendt challenged neorealist materialism, demonstrating that identities, shared norms, and social interactions construct the meaning of anarchy (Hobbesian, Lockean, or Kantian).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 5,
      questionText: 'Joseph Nye introduced the concept of "Soft Power" in 1990, defining it as the ability of a country to persuade and attract others to want what it wants through:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Culture, political values, and legitimate foreign policies',
        B: 'Military intimidation and naval carrier strike groups',
        C: 'Economic trade sanctions and currency embargoes',
        D: 'Nuclear deterrence capabilities',
      },
      correctAnswer: 'A',
      explanation: 'Soft power rests on intangible resources of co-optive attraction (cultural diplomacy, democratic ideals, international law adherence) contrasted with hard power (coercion and payments).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'The "Gujral Doctrine" of Indian foreign policy (formulated in 1996 by I.K. Gujral) established which core diplomatic principle regarding India\'s South Asian neighbours?',
      questionType: 'Direct MCQ',
      options: {
        A: 'India does not ask for reciprocity from smaller neighbours (such as Bhutan, Maldives, Nepal, Sri Lanka, and Bangladesh), but gives and accommodates what it can in good faith',
        B: 'Mandatory military intervention in domestic political disputes of all neighbours',
        C: 'Strict dollar-for-dollar tariff retaliation on all cross-border commerce',
        D: 'Refusal to sign bilateral river water-sharing treaties',
      },
      correctAnswer: 'A',
      explanation: 'The Gujral Doctrine based South Asian diplomacy on non-reciprocal generosity, non-interference, respect for territorial integrity, and peaceful bilateral dialogue.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'In 2014, the Government of India upgraded the historical "Look East Policy" (initiated in 1991 by P.V. Narasimha Rao) into which proactive strategic and economic framework?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Act East Policy',
        B: 'Neighbourhood First Policy',
        C: 'Connect Central Asia Policy',
        D: 'Security and Growth for All in the Region (SAGAR)',
      },
      correctAnswer: 'A',
      explanation: 'The Act East Policy enhances deep economic, strategic, connectivity, and cultural ties with ASEAN and East Asian nations (Japan, South Korea, Australia).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'The Quadrilateral Security Dialogue (QUAD) is a strategic diplomatic partnership comprising which four Indo-Pacific nations?',
      questionType: 'Direct MCQ',
      options: {
        A: 'India, United States of America, Japan, and Australia',
        B: 'India, Russia, China, and South Africa',
        C: 'United States, United Kingdom, Australia, and New Zealand',
        D: 'India, France, UAE, and Israel',
      },
      correctAnswer: 'A',
      explanation: 'The QUAD focuses on a free, open, inclusive, and rules-based Indo-Pacific maritime order, vaccine diplomacy, climate resilience, and supply chain security.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'Which landmark bilateral civil nuclear agreement was signed between India and the United States in 2008, terminating India\'s international nuclear isolation without India signing the NPT?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Indo-US 123 Agreement (Civil Nuclear Cooperation Agreement)',
        B: 'Camp David Accords',
        C: 'Simla Agreement',
        D: 'Tashkent Declaration',
      },
      correctAnswer: 'A',
      explanation: 'The 123 Agreement (signed under Prime Minister Manmohan Singh and President George W. Bush) enabled global civil nuclear commerce and secured an India-specific waiver from the Nuclear Suppliers Group (NSG).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 6,
      questionText: 'The permanent secretariat and headquarters of the South Asian Association for Regional Cooperation (SAARC), founded in 1985 in Dhaka, is located in:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Kathmandu (Nepal)',
        B: 'New Delhi (India)',
        C: 'Colombo (Sri Lanka)',
        D: 'Islamabad (Pakistan)',
      },
      correctAnswer: 'A',
      explanation: 'The SAARC Secretariat was established in Kathmandu, Nepal in January 1987 to coordinate regional cooperation among its 8 member states.',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 7 & 8: INDIAN CONSTITUTION & POLITICAL INSTITUTIONS (20 Questions: Q61 - Q80)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 7,
      questionText: 'In which landmark judgment did the Supreme Court of India formulate the "Basic Structure Doctrine", ruling that Parliament cannot alter the essential foundational features of the Constitution under Article 368?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Kesavananda Bharati v. State of Kerala (1973)',
        B: 'Golaknath v. State of Punjab (1967)',
        C: 'Minerva Mills v. Union of India (1980)',
        D: 'Maneka Gandhi v. Union of India (1978)',
      },
      correctAnswer: 'A',
      explanation: 'A historic 13-judge bench in Kesavananda Bharati ruled (7-6) that while Parliament has wide amending powers under Article 368, it cannot destroy the basic structure (supremacy of Constitution, secularism, separation of powers, judicial review).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'Under Article 32 of the Constitution of India, which prerogative writ is issued by the Supreme Court to secure the immediate physical release of a person unlawfully detained by the state or private entities?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Habeas Corpus ("To have the body")',
        B: 'Mandamus ("We command")',
        C: 'Quo Warranto ("By what authority")',
        D: 'Certiorari ("To be certified")',
      },
      correctAnswer: 'A',
      explanation: 'Habeas Corpus is the premier constitutional bulwark against arbitrary arrest and illegal detention, protecting individual personal liberty under Article 21.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'The concept of "Public Interest Litigation" (PIL) was institutionalized in the Indian judicial system in the late 1970s and 1980s by pioneering Supreme Court judges:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Justice P.N. Bhagwati and Justice V.R. Krishna Iyer',
        B: 'Justice H.R. Khanna and Justice M.H. Beg',
        C: 'Justice J.S. Verma and Justice Y.V. Chandrachud',
        D: 'Justice K. Subba Rao and Justice M. Patanjali Sastri',
      },
      correctAnswer: 'A',
      explanation: 'Justices Bhagwati and Krishna Iyer relaxed traditional locus standi rules, permitting any public-spirited citizen or letter to petition the court to enforce fundamental rights for marginalized communities.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 7,
      questionText: 'Under Article 356 of the Constitution of India, President\'s Rule (State Emergency) can be imposed in a state on the grounds of:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Failure of constitutional machinery in the state based on Governor\'s report or otherwise',
        B: 'Armed rebellion within a single municipality',
        C: 'Financial bankruptcy of a state public corporation',
        D: 'Loss of majority in an intra-party election',
      },
      correctAnswer: 'A',
      explanation: 'Article 356 permits the President to assume all executive powers of a state if satisfied that governance cannot be carried on in accordance with the provisions of the Constitution (strictly disciplined by the S.R. Bommai judgment 1994).',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'The "Election Commission of India" is an autonomous constitutional body established directly under which Article of the Constitution of India?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Article 324',
        B: 'Article 280 (Finance Commission)',
        C: 'Article 315 (Union Public Service Commission)',
        D: 'Article 148 (Comptroller and Auditor General)',
      },
      correctAnswer: 'A',
      explanation: 'Article 324 vests the superintendence, direction, and control of elections to Parliament, State Legislatures, and the offices of President and Vice-President in the Election Commission.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'Which Constitutional Amendment Act replaced the 65-year-old Planning Commission of India with the "NITI Aayog" (National Institution for Transforming India) in January 2015?',
      questionType: 'Direct MCQ',
      options: {
        A: 'It was established via a Cabinet Resolution (Executive Order), not through a Constitutional Amendment Act',
        B: '99th Constitutional Amendment Act',
        C: '101st Constitutional Amendment Act (GST)',
        D: '86th Constitutional Amendment Act',
      },
      correctAnswer: 'A',
      explanation: 'NITI Aayog is a non-constitutional, non-statutory extra-constitutional think-tank created on 1 January 2015 via a Union Cabinet resolution to promote cooperative federalism.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'The Anti-Defection Law was incorporated into the Constitution of India via the 52nd Constitutional Amendment Act 1985 in which Schedule?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Tenth Schedule',
        B: 'Eighth Schedule (Official Languages)',
        C: 'Seventh Schedule (Union, State, Concurrent Lists)',
        D: 'Eleventh Schedule (Panchayats)',
      },
      correctAnswer: 'A',
      explanation: 'The Tenth Schedule disqualifies legislators who voluntarily give up party membership or vote contrary to party whips, amended by the 91st Amendment (2003) to eliminate split exemptions.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'The "Inter-State Council", established to investigate, discuss, and deliberate on subjects of common interest between the Union and the States, is constituted by the President under:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Article 263',
        B: 'Article 262 (Inter-State Water Disputes)',
        C: 'Article 275',
        D: 'Article 301',
      },
      correctAnswer: 'A',
      explanation: 'Following the recommendations of the Sarkaria Commission (1988), the Inter-State Council was formally established under Article 263 by Presidential Order in May 1990.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 8,
      questionText: 'Under Article 75(3) of the Constitution of India, the Union Council of Ministers is collectively responsible to:',
      questionType: 'Direct MCQ',
      options: {
        A: 'The House of the People (Lok Sabha)',
        B: 'The Council of States (Rajya Sabha)',
        C: 'The President of India',
        D: 'The Prime Minister individually',
      },
      correctAnswer: 'A',
      explanation: 'Collective responsibility is the bedrock of parliamentary democracy in India: the Council of Ministers falls immediately if it loses the confidence of the Lok Sabha.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 8,
      questionText: 'Which Supreme Court judgment held that the Right to Privacy is an intrinsic part of the Right to Life and Personal Liberty under Article 21 and the freedoms guaranteed by Part III of the Constitution?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Justice K.S. Puttaswamy (Retd.) v. Union of India (2017)',
        B: 'Navtej Singh Johar v. Union of India (2018)',
        C: 'Joseph Shine v. Union of India (2018)',
        D: 'Shreya Singhal v. Union of India (2015)',
      },
      correctAnswer: 'A',
      explanation: 'A unanimous 9-judge bench in Puttaswamy (2017) declared privacy a fundamental constitutional right, overturning M.P. Sharma (1954) and Kharak Singh (1962).',
      difficulty: 'EASY',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // UNIT 9 & 10: PUBLIC ADMINISTRATION & GOVERNANCE (20 Questions: Q81 - Q100)
    // ═════════════════════════════════════════════════════════════════════════
    {
      unitNumber: 9,
      questionText: 'Who is recognized as the "Father of Public Administration" as an independent academic discipline following his pioneering 1887 essay "The Study of Administration"?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Woodrow Wilson',
        B: 'Frank J. Goodnow (Politics and Administration, 1900)',
        C: 'Leonard D. White',
        D: 'Frederick Winslow Taylor',
      },
      correctAnswer: 'A',
      explanation: 'Woodrow Wilson established the politics-administration dichotomy, advocating that administration lies outside the proper sphere of politics and should be run on professional business lines.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'Max Weber\'s Ideal-Type Bureaucracy is characterized by which structural features?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Hierarchical authority, fixed jurisdiction, written documentation (files), impersonal rule-governed action, and merit-based career tenure',
        B: 'Charismatic personal loyalty and hereditary titles',
        C: 'Democratic lottery of administrative roles',
        D: 'Informal verbal instructions and nepotistic hiring',
      },
      correctAnswer: 'A',
      explanation: 'Weber\'s rational-legal bureaucracy operates on legal authority, objective impersonal proceduralism, jurisdictional competency, and technical specialization.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'The "Hawthorne Studies" conducted between 1924 and 1932 at Western Electric Company by Elton Mayo and his Harvard colleagues gave birth to which administrative management theory?',
      questionType: 'Direct MCQ',
      options: {
        A: 'Human Relations Movement (Theory of Informal Organizations)',
        B: 'Scientific Management (Taylorism)',
        C: 'Administrative Management (Henri Fayol)',
        D: 'Bureaucratic Theory',
      },
      correctAnswer: 'A',
      explanation: 'Elton Mayo proved that informal social groups, interpersonal recognition, emotional security, and psychological factors motivate workers far more than mere physical working conditions.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 9,
      questionText: 'Herbert Simon revolutionized decision-making theory in "Administrative Behavior" (1947) by rejecting the classical "economic man" and proposing the concept of:',
      questionType: 'Direct MCQ',
      options: {
        A: '"Bounded Rationality" and "Satisficing Behavior" (Administrative Man)',
        B: 'Absolute optimizing rationality',
        C: 'Random irrational choice',
        D: 'Pure ideological determinism',
      },
      correctAnswer: 'A',
      explanation: 'Herbert Simon showed that due to cognitive limits, imperfect information, and time constraints, administrators do not maximize optimal outcomes; they select the first satisfactory alternative (satisficing).',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 9,
      questionText: 'The "New Public Administration" (NPA) movement, focusing on Social Equity, Relevance, Values, and Change in public service, was launched at the First Minnowbrook Conference (1968) convened by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Dwight Waldo',
        B: 'H. George Frederickson',
        C: 'Vincent Ostrom',
        D: 'Nicholas Henry',
      },
      correctAnswer: 'A',
      explanation: 'Dwight Waldo organized Minnowbrook I at Syracuse University, challenging value-free positivist administration and establishing NPA centered on social justice and client responsiveness.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'The "Right to Information Act" (RTI Act 2005) mandates that a Public Information Officer (PIO) must provide requested information to a citizen within a statutory time limit of:',
      questionType: 'Direct MCQ',
      options: {
        A: '30 days (or 48 hours if concerning life or liberty of a person)',
        B: '60 days',
        C: '90 days',
        D: '15 days',
      },
      correctAnswer: 'A',
      explanation: 'Section 7(1) of the RTI Act 2005 requires information to be supplied within 30 days of application receipt, or within 48 hours if it concerns the life or liberty of a citizen.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'The institutional concept of the "Lokpal and Lokayuktas" (Ombudsman) in India to investigate allegations of corruption against public functionaries was first officially recommended in 1966 by the:',
      questionType: 'Direct MCQ',
      options: {
        A: 'First Administrative Reforms Commission (First ARC chaired by Morarji Desai / K. Hanumanthaiah)',
        B: 'Second ARC (chaired by Veerappa Moily, 2005)',
        C: 'Santhanam Committee on Prevention of Corruption (1964, recommended CVC)',
        D: 'Sarkaria Commission (1988)',
      },
      correctAnswer: 'A',
      explanation: 'The First ARC Interim Report (1966) recommended establishing an Ombudsman at the Centre (Lokpal) and in the States (Lokayuktas), culminating in the Lokpal and Lokayuktas Act 2013.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'Under the "Citizens\' Charter" initiative (first introduced in the UK by John Major in 1991 and adopted in India in 1997), what is the core objective?',
      questionType: 'Direct MCQ',
      options: {
        A: 'To declare institutional commitments regarding standards, quality, time frames, grievance redressal, and transparency of public services',
        B: 'To provide monetary cash bonuses to senior bureaucrats',
        C: 'To privatize municipal water supply corporations',
        D: 'To conduct secret surveillance on trade unions',
      },
      correctAnswer: 'A',
      explanation: 'A Citizen\'s Charter is a public declaration of an organization\'s service standards, choice, accessibility, accountability, and grievance redressal mechanisms.',
      difficulty: 'EASY',
    },
    {
      unitNumber: 10,
      questionText: 'In public policy analysis, the "Incremental Model" of decision-making (describing policy as "muddling through" with small marginal adjustments to existing policies rather than grand synoptic overhauls) was propounded by:',
      questionType: 'Direct MCQ',
      options: {
        A: 'Charles E. Lindblom ("The Science of \'Muddling Through\'", 1959)',
        B: 'Yehezkel Dror (Optimal Model)',
        C: 'Amitai Etzioni (Mixed Scanning Model)',
        D: 'Thomas R. Dye',
      },
      correctAnswer: 'A',
      explanation: 'Charles Lindblom argued that comprehensive rational planning is impossible in practice; real-world policy makers make small incremental comparisons based on past experience.',
      difficulty: 'MEDIUM',
    },
    {
      unitNumber: 10,
      questionText: 'Which landmark 73rd Constitutional Amendment Act provision made direct reservation of NOT less than what proportion of total seats for women in Panchayati Raj Institutions mandatory across India?',
      questionType: 'Direct MCQ',
      options: {
        A: 'One-third ($33.33\\%$ of total seats and chairpersons)',
        B: 'One-tenth ($10\\%$)',
        C: 'One-half ($50\\%$ mandatory nationally, though several states like Bihar have raised it to $50\\%$)',
        D: 'Two-thirds ($66\\%$)',
      },
      correctAnswer: 'A',
      explanation: 'Article 243D(3) mandates that not less than one-third of the total number of seats to be filled by direct election in every Panchayat shall be reserved for women.',
      difficulty: 'EASY',
    },
  ];

  return {
    subjectCode: '02',
    subjectSlug: 'political-science',
    mockNumber: 1,
    title: 'Political Science — Mock Test 1: Full Syllabus Simulation (100 Qs)',
    description: 'Authentic 100-question UGC NET Political Science simulation covering Political Theory, Western & Indian Thought, Comparative Analysis, IR, Foreign Policy, Indian Polity, and Public Administration across all 10 units.',
    accessTier: 'FREE',
    isFreeBenchmark: true,
    questions,
  };
}
